adoptium/infrastructure

ansible/Vagrantfile.Win2012, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/README.md, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
Fixes: #1858 
Also updates the comments to better reflect what's happening in the VF
=> vagrant: Force win2012r2 to use tls1.2 in provision script

.github/workflows/build_mac.yml
ref: #1790 
Changes a few lines in `.github/workflows/build_mac.yml` file, so the GitHub Check can actually run.
=> GHCheck: Fix Brew issues for macOS

ansible/inventory.yml
Ref: #1781 
From what I can see, the machines have been removed, and the issue has been closed, however they're still in the Inventory / Nagios / Jenkins.
=> inventory: Remove decommisioned GoDaddy machines

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Debian.yml
Ansible will dynamically determine the name of the release installed on the target host. So on a system with buster, the apt source will correctly point to the repository for buster and not for jessie.
=> unixPB: Do not hardcode releases in apt (Debian)

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Get_Vendor_Files/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Get_Vendor_Files/tasks/main.yml
Fixes: #1850 
In cases where `dotgpg` can't be used, or we need to automate running the playbooks, (such as AWX, see the referenced issue), currently, there's no way to run the `adoptopenjdk` tagged roles (or any roles requiring vendor file material). To fix this, I've adapted the `Get_Vendor_Files` role to allow  the use of the local vendor files, or retrieving them from the secrets repo in the case that the machine doesn't have local vendor files.
This assumes that the local vendor files:
1) Follow the same structure as the vendor_files in the secrets repo (i.e. https://github.com/AdoptOpenJDK/secrets/blob/master/vendor_files/Nagios_User_SSHKey.gpg --> /Vendor_Files/Nagios_User_SSHKey)
2) aren't gpg encrypted.
=> unix/winPB: Allow use of local Vendor_Files folder

.github/workflows/build_vagrant.yml
Fixes: #1879 
The reason the check is failing due to `brew` when the check is regarding Solaris, is due to Solaris being run as a VM, on a macOS machine. The `brew cask install` command was failing when trying to install Virtualbox/Vagrant, as `brew cask install` has been swapped for `brew install --cask`.
Kept in draft until I can confirm this has fixed the issue.
=> Github: Fix Solaris check brew-cask error

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/main.yml
Fixes: #1888 
Ref: #1870 (Hopefully a future enhancement we can do on the AIX PB)
Adds the adoptopenjdk tags, so people without Vendor_Files can run the playbooks without it failing.
@aixtools , I could only find 3 roles that used the Vendor_Files, let me know if there's any I missed :-)
=> aixPB: Add adoptopenjdk tags for Vendor_File roles

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/RedHat.yml
Fixes: #1890 
`!` doesn't symbolize `not` in yaml, apparently. Testing on `build-maritst-rhel77-s390x-2`, the condition now skips as expected :-)
=> unixPB: Fix condition for numactl RHEL7/S390x

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_MacOSX.yml
Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1716#issuecomment-764713146
For some reason, `brew` doesn't like installing anything as the `administrator` user via ansible, without the `become: yes` and `become_user: "{{ ansible_user }}"` lines - I just copied what was done in the Common role for installing build/test tool packages.
I've also added an additional task for ARM64, to symlink to the plugins for ARM64. As ARM64 MacOSX requires homebrew to be installed in `/opt/homebrew/`, as opposed to `/usr/local/` for `x64` , the original symlink task doesn't work.
=> unixPB: Update Nagios_Plugins install for macOSX

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml
Ref: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1005/OS=CentOS6,label=vagrant/console
Docker repo checksum is wrong.
=> unixPB: Update Checksum for Docker CentOS/RHEL7 x64

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NVidia_Cuda_Toolkit/tasks/main.yml
Fixes: #1889 
Updates the URL to install the base repo for CUDA.
=> unixPB: Update U16/PPC64LE Cuda Repo URL

FAQ.md
This doc needs more of an overhaul to ensure it's useful for a new person on the project which I don't want to do in this PR - this is purely to make sure the docs refer people to AWX in the "Add new machine" checklist.
=> docs: update machine addition section of FAQ with AWX info

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml
ref https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1856
Without Test::Simple, test-ibmcloud-rhel6-x64-1 and rhel7 will fail jdk 8 openj9 functional special tests (EDIT: on x86-64_xl), https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/6736/console. (rhel6)
```
15:13:14  FAILED test targets:
15:13:14  	MBCS_Tests_pref_ja_JP_linux_0
15:13:14  	MBCS_Tests_pref_ko_KR_linux_0
15:13:14  	MBCS_Tests_pref_zh_CN_linux_0
15:13:14  	MBCS_Tests_pref_zh_TW_linux_0
15:13:14  	MBCS_Tests_coin_ja_JP_linux_0
15:13:14  	MBCS_Tests_coin_ko_KR_linux_0
15:13:14  	MBCS_Tests_coin_zh_CN_linux_0
15:13:14  	MBCS_Tests_coin_zh_TW_linux_0
```
After installing the module, the tests passed 
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/6737/console
=> UnixPB: install perl-test-simple on rhel

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/MacOSX.yml
fixes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1282
Grinder before change: https://ci.adoptopenjdk.net/job/Grinder/5835/tapResults/
Grinder after change: https://ci.adoptopenjdk.net/job/Grinder/5837/tapResults/
=> unixPB enable core dumps on macOS

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/RedHat.yml
Fixes: #1915 
Sets the locale list command based on the `ansible_major_distribution_version`. The `if` statement is required because ansible will register variables even if a task is skipped - otherwise I would have had 2 separate tasks that register to `localeList`, as that'd be easier to read.
=> unixPB: Find Locale-list based on RHEL major_version

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_Ubuntu.yml
Ref: #1901 
The condition wasn't correctly skipping the role, which probably wasn't helping the referenced issue. @sxa , could you test this to see if this fixes the issue - If your `ansible_distribution_major_version` variable really was undefined, there would presumably be failures much sooner in the playbook than Nagios.
=> unixPB: Fix U20 condition in Nagios_Plugins

ansible/pbTestScripts/testJDK.sh
ref https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1927#issuecomment-778289501
I have added the MBCS_Tests_pref_ja_JP_linux_0 test as a quick test to ensure that the required perl modules are on a machine after the playbook runs on them, since installing perl from yum seems to sometimes omit certain perl modules.
I was initially going to add this test as something optional, but ive instead replaced the existing MachineInfo test altogether as the MachineInfo test's only purpose is to see if a test _can_ run
What do you think @Willsparker?
=> VPC: add MBCS test for vagrant playbook check job

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml
Replacement for https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1931 as I'd put the checksum in the x64 one instead of s390x in there (Git won't let me reopen the old PR)
=> unixPB: Update checksum for CentOS/RHEL s390x docker repo

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
We no longer require the boot JDKs for previous releases to be on the machines
=> Remove JDK13/14, Add JDK15 to the machines for bootstrapping current releases

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Common/tasks/main.yml
Fixes: #1945 
Ignores the errors when creating shortnames. Reasoning for this is that, if the playbook is run on a machine that's already setup, the task in question will fail as there will be processes running in the Program Files (x86) folder. This will occur, even if the folder already has it's shortname. 
If, on an initial playbook run, the task fails and is ignored, the problem will be evident when the machine is tested, and manual intervention would be required anyway.
=> winPB: Ignore Program Files (x86) shortname errors

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/bootjdk8/tasks/main.yml
The symlink should be pointing at /usr/java8_64/jre/bin/java not /usr/java8_64/, causing aix machines to use java6 as a default
=> UnixPB: symlink /usr/bin/java to /usr/java8_64/jre/bin/java

ansible/inventory.yml
I may split these out from regular "docker" systems in the future, but this is one of the x64 machines that is hosted docker containers as per https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1809
=> inventory: add AMD dockerhost system

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Jenkins/tasks/main.yml
Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1884#issuecomment-784008308
Although this is the case for Ansible 2.10.6, the problem may have no occur with earlier versions of ansible (and may be why I didn't see this issue when setting up machines for #1932 ). This is the formatting suggested in the documentation (https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_user_module.html#examples) so I doubt it would be an issue for earlier versions of Ansible.
=> winPB: List Jenkins user groups

.ansible-lint, .github/workflows/linter.yml
Fixes: #1926 
I was able to recreate the issue locally - Something is making ansible-lint run `ansible-playbook --syntax-check adoptopenjdk_variables.yml` - which is wrong because adoptopenjdk_variables is not a playbook. When the file is renamed, it complains that it can't find it, so somewhere, it is hardcoded that adoptopenjdk_variables.yml is a playbook and it's in the playbooks directory. I couldn't find anywhere that would suggest this, unfortunately, but excluding the path to the variable file manually seems to stop the error anyway.
=> GHChecks: Ansible-lint Ignore variables file

ansible/inventory.yml
=> inv: Add build-azure-win2016-x64-1

ansible/Dockerfile.CentOS6, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Python2.7/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml
Fixes: #1877 
IT WORKS! (in VPC at least: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1067/ )
Installs Python 2.7 on CentOS6 and then uses that Python to run the `adoptopenjdk_install` tasks. See the referenced issue for what other things were tried or suggested. This solution also adds some future proofing somewhat, in that we can just use the Python2.7 whenever we have another `unarchive` / `get_url` cert issue because CentOS6 is old.
=> unixPB: Install Python2.7 on C6; Use it to install JDKs

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml
Patrick Reinhart from the JMC team complained that the Centos machines have mercurial but the rhel ones do not. This PR adds this.
=> unixPB: add missing mercurial package to rhel machines

ansible/pbTestScripts/buildJDK.sh, ansible/pbTestScripts/buildJDKWin.sh
Not a clue if I've stripped too much out or not, but might as well give it a shot ... Now possible thanks to https://github.com/AdoptOpenJDK/openjdk-build/pull/2167 https://github.com/AdoptOpenJDK/openjdk-build/pull/2479 https://github.com/AdoptOpenJDK/openjdk-build/pull/2482 but requires https://github.com/AdoptOpenJDK/openjdk-build/pull/2478 but weill require https://github.com/AdoptOpenJDK/openjdk-build/pull/2478 to be merged before testing
=> pbTests: Allow use of default values for make-adopt-build-farm.sh

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/yum/tasks/main.yml
Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/2492
=> aixPB: Lock cmake from yum to 3.14.3

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Crontab/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.alp311, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.alp312, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/tasks/main.yml
I've largely followed #1925. I copy and pasted the CPU/RAM config. Please adjust as you see fit. 
The SSH key and the password are baked into the container image (as it's done in #1925). If we want to change that, I'd rather do it for all containers in a separate PR. I did a test run with `_sanity.openjdk`.
Fixes #1929.
=> unixPB: Add static Alpine containers for tests

ansible/pbTestScripts/qemuPlaybookCheck.sh
Ref: #1966 
Another problem I found when clearing the infra-vagrant box was that QPC runs didn't clear up their images once they were finished. These build up fast! The images won't be removed if the VM isn't intended to be destroyed. 
This also removes the archive from the workspace once it's been extracted, as that's more space that doesn't need to be used.
=> QPC: Remove image files after run

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/zulu7/tasks/main.yml
Fixes: #1983 
Adds U16 to the list of OSs that install Zulu-7. This PR also removes the unnecessary `openjdk-8-jdk` in the `Ubuntu1604 Only` package list, as it's already in the Common build packages list.
=> UnixPB: Install Zulu-7 on Ubuntu1604

ansible/inventory.yml
Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1963#issuecomment-787903034
=> inventory: Remove test-azure-win2012r2-x64-2

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_RedHat.yml
Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1990#issuecomment-790422413
Various issues found when running the playbooks on all the machines:
- Remove installation of locales for RHEL, entirely. `glibc-common` provides the locale specific functions now, it seems.
- Update some URLs for dependencies for RHEL7 aarch64 (The version has been updated in the package repo)
- Install `nagios-plugins` for RHEL8/x64, as opposed to `nagios-plugins-all`, as the latter has some dependencies that can be fulfilled.
I'm sure there will be more once I've done the AWX `test*centos*` and `test*ubuntu*` runs, so I'll keep this in draft for now.
=> unixPB: Various small fixes to get AWX running cleanly

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Swap_File/tasks/main.yml
Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1990#issuecomment-789549739
This _should_ fix the Swap File issue we're having, see the referenced issue. The issue for the affected machine(s) (`build-scaleway-ubuntu1604-armv7-*`) was that when running `$ cat /etc/fstab`, this was being returned: `# UNCONFIGURED FSTAB FOR BASE SYSTEM` - so the `grep` check failed, so the tasks following attempted to create the swapfile whilst it's in use.
I also changed some of the tasks to fit the format we have for the rest of the playbooks.
=> unixPB: Fix Swapfile detection

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Debug/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adopt_etc/tasks/main.yml
ref https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1994
On some machines (build-scaleway-ubuntu1604-armv7-1 and -2) ansible_default_ipv4.address isnt able to detect the public ip, but instead detects the private ip.
This causes problems with the `hosts_file` tagged tasks which enter lines in `/etc/hosts` based on the ansible_default_ipv4.address variable. Therefore I have changed this variable to ansible_ssh_host, which I have found better detects the public ipv4 of a machine. 
The line that ive added to the `Debug` role will be removed after I have adequately tested this pr
Tests list:
=> UnixPb: change ansible_default_ipv4.address variable to ansible_host

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Python2.7/tasks/main.yml
ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1990#issuecomment-792653280
RHEL6 needs Python 2.7.* on it too, for the `adoptopenjdk_install` role.
=> UnixPB: Install Python 2.7.18 on RHEL6

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml
ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1990#issuecomment-793480995
As the comment says, RHEL6 needs to install AdoptOpenJDK with the same task that CentOS6 uses, so it can use the right interpreter.
=> unixPB: Use alt JDK install for RHEL6

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_RedHat.yml
Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1990#issuecomment-792649133
The reason this task failed was because the plugins for RHEL8 were already there. Therefore, it should be checked if the plugins are already there, before we make the symlinks. I didn't make this specific to any one distribution, as I don't know if this will change depending on various architectures (or different versions of the `nagios-plugins` package).
=> unixPB: Check Nagios Plugins folder for RedHat

ansible/inventory.yml
inventory file cannot be parsed due to the presence of `:` characters in the ipv6 field - I thought we had a check for this somewhere - if not we should create one
```
[sxa@sainz ansible]$ ./plugins/inventory/adoptopenjdk_yaml.py
while scanning a plain scalar
in "/home/sxa/git/openjdk-infrastructure/ansible/inventory.yml", line 166, column 51
found unexpected ':'
in "/home/sxa/git/openjdk-infrastructure/ansible/inventory.yml", line 166, column 55
Please check http://pyyaml.org/wiki/YAMLColonInFlowContext for details.
Traceback (most recent call last):
File "./plugins/inventory/adoptopenjdk_yaml.py", line 223, in <module>
main()
File "./plugins/inventory/adoptopenjdk_yaml.py", line 63, in main
export = parse_yaml(load_yaml_file(inventory_path), config)
File …
```
=> inventory: Quote IPV6 addresss since adoptopenjdk_yaml.py cannot parse inventory

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/MacOSX.yml
Ref https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1910#issuecomment-795907758
The condition should compare the stdout of the variable, not the whole variable. Else it fails with this error
```
fatal: [test-macstadium-macos1014-x64-1]: FAILED! => {"msg": "The conditional check 'not macos_version | regex_search(\"10.12\")' failed. 
The error was: Unexpected templating type error occurred on ({% if not macos_version | 
regex_search(\"10.12\") %} True {% else %} False {% endif %}): expected string or bytes-like object\n\n
The error appears to be in '/tmp/awx_763_m5aop2n8/project/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/MacOSX.yml': 
line 93, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\n
The offending line appears …
```
=> UnixPb: add stdout of registered variable

ansible/Vagrantfile.Debian10
Fixes: #1980 
As mentioned in the issue, the Debian10 Vagrant VM wants to upgrade `grub-pc` when running the upgrade task from the playbook, however, that causes a popup, which Ansible can't handle. The reason I have specifically put in a Vagrantfile fix as opposed to a playbook fix is because if this were a _real_ machine, the `grub-pc` package could be installed manually - and I don't know of the complications that not upgrading `grub-pc` can cause - however, that doesn't matter on a VPC run.
=> vagrant: apt-mark hold grub-pc on Debian10

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/debug/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Debug/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Debug/tasks/main.yml
Print `ansible_version` into the logs for debugging purposes
=> unixPB/winPB: Add ansible_version to debug info

ansible/playbooks/scripts/AIX_filesystem_config.sh
=> aixPB: fix minimum size test to real minimum of 60G, exit 1 on fail

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.alp311, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.alp312
Adds missing dependencies to static Alpine containers for testing. Should resolve https://github.com/AdoptOpenJDK/openjdk-tests/issues/2223#issuecomment-801995589 and probably supersedes #2026.
=> unixPB: Add missing deps to Alpine for testing

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/crontab/tasks/main.yml
=> aixPB: Add crontab entries to ensure stale (jenkins) files and directories are removed

.github/workflows/linter.yml
Required now that `aix.yml` no longer exists now that https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/2053 has been merged
=> github: make linter use the correct file for checking AIX playbook

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.f33, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.u1604, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.u1804, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.u2004, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.u2010
Required as per https://github.com/eclipse/openj9/issues/11915 (and others) to make `LambdaFileEncodingSerialization` work
=> Ensure en_US.utf8 is in static docker test containers

README.md
- [ x other documentation is changed or added (if applicable)
The lists in here need a general cleanup bu this does the minimum to add the current admins ([including Andreas](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2074)) and fix the name of the github team :-)
=> doc: Update README with current list of machine admins

ansible/Vagrantfile.Debian10, ansible/pbTestScripts/buildJDK.sh
Fixes: #2033
Stops building the debug images when running the Unix playbooks, as it just takes up unnecessary space, and doesn't require any more deps for VPC to test.
=> pbTests: Stop build debug images on Unix

README.md
As it turns out Martijn wasn't in the `infrastructure-core` team (a formality as he has admin access anyway!) so I missed him from the list in https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/2075 - this PR corrects that :-)
=> doc: Add Martijn to core team in README.md

ansible/inventory.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_MacOSX.yml
closes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1290
=> inventory: Replace build-macstadium-macos1010-x64-1 with build-macstadium-macos10104-x64-3

ansible/inventory.yml
The DTK program has ended and Macstadium sent them back. See
https://www.macrumors.com/2021/02/03/apple-asks-developers-to-return-dtk/.
=> inventory: Remove DTK machines

README.md
Split out (ish) from https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1974 - I think it's preferable not to have to manually update all of the github lists explcitly when people are onboarded.
=> doc: updates to README.md

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/yum/tasks/main.yml
Two aix yum tasks were missing `yum` tags. They are no longer missing `yum` tags
=> AixPb: add missing yum tags

ansible/pbTestScripts/vagrantPlaybookCheck.sh
Ref: #1504 
Rearms the Win 2012 VM before running the playbook on it. [As mentioned](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2056#issuecomment-806527619) this could be in the Vagrantfile, but this causes issues with the reboot that's required for the re-arm to take effect.
This is to go towards making the Win2012 VPC run more stable.
=> pbTests: Rearm Windows 2012 VF before playbook

ansible/pbTestScripts/qemuPlaybookCheck.sh
No reason to hide the logs - it can assist with debugging if the machine hasn't started for some reason
=> pbTests: Log console output of QEMU VM on first boot

ansible/inventory.yml, ansible/plugins/inventory/adoptopenjdk_yaml.py
Split off from #1483 
As we have the machines connected in Jenkins, for the inventory to continue reflecting what we actually have, these should be added now, before the playbooks fully support the RISC-V platform.
=> inv: Add gdams RISC-V machines

ansible/inventory.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/scripts/install-fiddle.sh, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/MacOSX.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/MacOSX.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Xcode/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml
=> inventory: add m1 build macOS machines + playbook support for m1

ansible/pbTestScripts/vagrantPlaybookCheck.sh
Fixes: #2056 
For awhile the Windows VPC run has been unstable - it seemed to be an issue with the Python script that starts builds/tests on the Windows VM, and I think it's the port numbers that the script is attempting to use. For some (stupid) reason, in #1509 , I thought it'd be better to find the `winrm_ssl` port using an arithmetic expression, instead of just.. looking up which port it was .. :facepalm: . I imagine this has caused some issues, in the cases where the `winrm_ssl` port wasn't `winrm_port - 1`. This, in conjunction with #2104 , seems to have made the Win VPC run more stable:
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1125/
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1124/
=> pbTests: Ensure use of correct port when running Win build

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/macos_codesign/tasks/main.yml
Fixes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2120
=> unixPB: disable macOS keychain timeout

.github/workflows/build_mac.yml
Recently GitHub changed its preinstalled environment to pull the adoptopenjdk binaries from the API rather than homebrew https://github.com/actions/virtual-environments/blob/main/images/macos/provision/core/openjdk.sh. This broke our PR tester because it was trying to remove the packages that didn't exist.
This PR simply removes the brew uninstall step.
=> actions: remove homebrew adopt cleanup block

ansible/pbTestScripts/buildJDK.sh, ansible/pbTestScripts/qemuPlaybookCheck.sh
ref: #2121 
Currently QPC is failing on a few platforms that should be stable. It was due to #1962 not updating the script to reflect `buildJDK.sh`'s arguments. Amazing how the author of that PR didn't realise .. :eyes: .
In my testing, I noticed that often the `make-adopt-build-farm.sh` wouldn't pickup on variables that were being set as part of `buildJDK.sh`. When the build scripts started defaulting most arguments,  This just needed those variables exported. I've gone back to making `openj9` the default as this tests more dependencies for our playbooks.
=> pbTests: Fixup buildJDK arguments in QPC & export buildJDK vars

ansible/inventory.yml
=> inventory: Remove two OSUOSL Ubuntu 16.04 hosts

ansible/inventory.yml
Follow on to https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1861 now that https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1932 has been completed to replace both AWS windows systems that we had.
=> inventory: Remove final AWS Windows machine

ansible/inventory.yml, ansible/plugins/inventory/adoptopenjdk_yaml.py
These systems warrant a separate category as unlike the others (including `docker`) we will generall not be running things on the host so they will not have the full playbooks deployed. See the FAQ for more details and links on how these systems are used.
Resolves https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2046
All but nagios set up ... Although I want to have a separate discussion on exactly how we monitor these in Nagios so it will be added later.
=> inventory: add dockerhost systems

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Common/tasks/main.yml
Fixes: #2133 
Tested on the Windows 2012 VM. These tasks will check to ensure that the hostname doesn't end in a hyphen. If it does, it will remove the hyphen and restart the machine so those changes take effect.
ping @lumpfish
EDIT: The VPC run got through the hostname changes fine (so this is an example of where the tasks are skipped when they're meant to).
=> winPB: Ensure hostnames don't end in a hyphen

ansible/inventory.yml
Adding just one for now in order to run some ansible deployments on it to verify whether the problems seen in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2119 are specific to docker containers. Not currently added to nagios as this may be a temporary installation.
=> ansible: Add CentOS Altra from equinix

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NTP_TIME/tasks/main.yml
ref https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2143
The tasks https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/a4d8543253f2cf3edbe9b606b809a3ad5fd6beab/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml#L84 and https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/a4d8543253f2cf3edbe9b606b809a3ad5fd6beab/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NTP_TIME/tasks/main.yml#L5 fail on ubuntu versions 20.04 and 21.04, and so need to be skipped on these versions
=> UnixPB: change conditions to include Ubuntu versions greater and equal to 20

ansible/inventory.yml
Part of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1986
NOTE: This also removes a centos build system from OSUOSL which no longer exists but was still in the inventory
More TBC - jenkins and bastillion updates done, nagios not yet updated with new hostnames
=> inventory: Remove first set of Ubuntu 16.04 systems

ansible/pbTestScripts/buildJDK.sh
Fixes: #2176 
Adds logic to detect JDK7 in circumstances of building JDK8. Not all platforms share the same process of getting a JDK7 (i.e. it may be to install it from the package manager, install zulu-7, or it may be that JDK-7 isn't available), so they often have different names within `/usr/lib/jvm`, so  `buildJDK.sh` needs to set `JDK7_BOOT_DIR` depending on the situation.
In the case of some platforms (i.e. Ubuntu1804 on S390x and PPC64LE), there is no JDK7, so JDK8 is set as a last resort.
[VPC Run](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1163/)
[QPC Run](https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/258/) (See Ubuntu1804/s390x to see the build start)
=> pbTests: Autodetect JDK-7 or default to JDK8 when building JDK8

ansible/Vagrantfile.Ubuntu2104, ansible/pbTestScripts/vagrantPlaybookCheck.sh, ansible/pbTestScripts/vmDestroy.sh
Ref: #2143
Adds support for U21 to VPC. In draft until VPC definitely works: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1145/OS=Ubuntu2104,label=vagrant/console
=> pbTests: Add Ubuntu21.04 VPC support

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.cent8, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.f33, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.u1604, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.u1804, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.u2004, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.u2010
Fixes https://github.com/AdoptOpenJDK/openjdk-tests/issues/2357 (Once deployed to all existing systems)
=> unixPB: Add fontconfig to DockerStatic Dockerfiles

ansible/pbTestScripts/vagrantPlaybookCheck.sh
Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/2164#issuecomment-830009275
Also fixes a bunch of indentation issues ...
=> pbTests: Ignore VPC '--test' argument instead of failing

CODE_OF_CONDUCT.md, CONTRIBUTING.md, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/nagios/nagios_aix.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/additional_plugins/check_pkg, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/additional_plugins/check_sw_up, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/additional_plugins/check_yum, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/additional_plugins/check_zypper, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_Debian.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_FreeBSD.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_MacOSX.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_SLES.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_Ubuntu.yml, ansible/playbooks/nagios/nagios_aix.yml.old
I've double-checked both the official plugins provided by nagios as well as doing a full GitHub search. I've found no evidence to suggest that these files are licensed with the GPL license (especially considering the typo)
=> remove GPL headers and add COC

ansible/pbTestScripts/qemuPlaybookCheck.sh
Ref: #2121 
Debian10/aarch64 doesn't have enough time to boot in 120 seconds, however it was able to after 180s.
=> pbTests: Increase QPC.sh sleep time

ansible/inventory.yml
Part of https://github.com/adoptium/infrastructure/issues/2078
This covers the ThunderX and D05 systems. For now I'm retaining the (newer) eMag one as there are still some things running on it.
=> inventory: Remove old Packet/aarch64 systems

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Solaris.yml
Fixes: 
```bash
bash-3.2# ssh -T git@github.com
Client and server could not agree on a key exchange algorithm:
client: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
server: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256
```
Once installed you need to set `GIT_SSH=/opt/csw/bin/ssh`
=> install openssh on Solaris machines

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Solaris.yml
Also swaps the Solaris studio check to be before the secrets to make it easier to run without vendor files
=> unixPB: create ensure that gconfd-2 is in the correct location for TCK

ansible/pbTestScripts/qemuPlaybookCheck.sh, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Debian.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Debian.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml
Ref: #2123 
Adds support for debain11/RISC-V. Tested in QPC throughout the process, see the referenced issue for details.
=> UnixPB: Add support for Debian11/RISC-V

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NTP_TIME/tasks/main.yml
It caused a playbook failure on at least one machine for temurin-compliance.
=> ansible: ignore errors on check for disabled timesyncd

ansible/pbTestScripts/testJDK.sh
ref https://github.com/adoptium/infrastructure/issues/2121
The latest failure on the QEMU ppc64le job produces this failure
```
00:17:27 TESTDIR: /home/linux/testLocation/openjdk-tests is invalid. Please use --testdir|-t to set valid TESTDIR under aqa-tests. Default value current dir (pwd) is used if not provided.
00:17:32 /home/linux/openjdk-infrastructure/ansible/pbTestScripts/testJDK.sh: line 15: cd: /home/linux/testLocation/openjdk-tests/TKG: No such file or directory
00:17:32 + grep -q 'FAILED: 0' /home/vagrant1/workspace/QEMUPlaybookCheck/ARCHITECTURE/ppc64le/OS/ubuntu18/label/vagrant/ansible/pbTestScripts/qemu_pbCheck/logFiles/UBUNTU18.PPC64LE.test_log
00:17:32 + echo TEST FAILED
```
The other QEMU jobs would produce the same failure if they get to the test stage, but they keep …
=> pbTests: Change any occurrence of openjdk-tests to aqa-tests in the test script

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/bootjdk16/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
VPC not run yet due to VPC failing.
Related AIX enhancement request to maek the role parameterised as per other platforms has been raised at https://github.com/adoptium/infrastructure/issues/2239
=> Install boot JDk16 for bootstrapping JDK17 builds.

ansible/docker/Dockerfile.Ubuntu1604
Currently the jobs are failing with:
```bash
ERROR! the playbook: /ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml could not be found
```
=> docker: remove backslash from ansible-playbook command

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/ccache/tasks/main.yml
ref https://github.com/adoptium/infrastructure/issues/2091
The unix playbook compiles Git, Cmake and Ccache to versions 2.15, 3.11.4, 3.4.2, respectively. On OS's whose default repos offer these packages at versions equal to or greater than the compiled versions, I have made it so that these packages are downloaded from there instead. See https://github.com/adoptium/infrastructure/issues/2091#issuecomment-869578801
The packages are installed from the repos in the `Common` role, which occurs before any of the roles in which these packages would otherwise be compiled, so theres no risk of duplicate installation. However, the `ccache` role checks for an already installed version of ccache by checking the `/usr/local/bin/ccache` directory. It needs to be made sure that the ccache downloaded …
=> UnixPb: Install packages from repositories instead of compiling when necessary

ansible/pbTestScripts/vagrantPlaybookCheck.sh, ansible/pbTestScripts/vmDestroy.sh
Fixes: #2215 
VPC currently isn't running cleanly, due to a new issue with `vmDestroy.sh`. While I can't see that it's related to #2211 , `vpc.sh`, it suddenly started being an issue after this was merged. Irrespective, `vpc.sh` needs to be updated to reflect the changes in that PR anyway.
Keeping in Draft until VPC runs are (mostly) green: 
https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/1183/
=> pbTests: Update Vagrantfile paths in VPC/vmDestroy

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.f33
Fixes https://github.com/adoptium/infrastructure/issues/2175
=> docker: Add which and hostname to Fedora33 static containers

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/macos_codesign/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/CodesignCert/tasks/main.yml
We no longer need these codesign certs. The safest option is to fully remove them from the machines to prevent us signing an Adoptium build with the wrong cert
=> Remove LJC codesign certs from all machines

FAQ.md
Documentation update was missed in https://github.com/adoptium/infrastructure/pull/2211
Spotted while investigating https://github.com/adoptium/infrastructure/issues/2253
=> doc: Update FAQ after dockerfiles were moved to another location

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml
When I merged I had misread the comment in https://github.com/adoptium/infrastructure/pull/2241 as the ccache CentOS7 VPC problem being an expected failure. But it looks like it was almost certainly a typo, so fixing ...
=> unixPB: Fix typo in ccache name in CentOS playbook

ansible/pbTestScripts/vagrantPlaybookCheck.sh
Hopefully fixes https://github.com/adoptium/infrastructure/issues/2244
=> pbTests: Reset Solaris host key after playbook completion

ansible/README.md
Updated the README to include sections for installing Vagrant on a Windows machine, and installing and running Ansible within the Vagrant virtual machine.
=> doc: README updated to include information on installing and using Vagrant and Ansible on a  Windows machine

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml
Ubuntu 16 users will now just have to source their own JDK7, or use the installed JDK8 as the boot JDK
=> unixPB: Remove openjdk-7-jdk from Ubuntu as it is no longer in the repositories

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml
Fixes: https://github.com/adoptium/infrastructure/issues/2262
=> unixPB: remove gcc-7 from ubuntu armv7l playbook

Jenkinsfile
fixes:
```bash
docker manifest annotate adoptopenjdk/ubuntu1604_build_image adoptopenjdk/ubuntu1604_build_image:linux-armv7l --arch armv7l --os linux
manifest entry for image has unsupported os/arch combination: linux/armv7l
```
=> Fix manifest command in jenkinsfile

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adopt_etc/tasks/main.yml
On Solaris where we use a jumpbox ansible_host is set to cloud.siteox.com rather than the IPv4 address so the machine is unable to resolve its hostname
=> unixPB: set /etc/hosts to use IPV4 address rather than ansible_host

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Jenkins_User/tasks/main.yml
The issue has been raised a couple of time already on temurin-compliance. I guess it's worth adding for both regular and temurin-compliance nodes.
=> ansible: Added task to add github.com to known_hosts

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Thunderbird/tasks/main.yml
This is after request https://bugs.eclipse.org/bugs/show_bug.cgi?id=574777.
I've created a `jck` tag that should be skipped for regular (ie non temurin-compliance) nodes.
=> ansible: Added Thunderbird role to Windows playbook

.github/PULL_REQUEST_TEMPLATE.md
The repo links in the pull request template are outdated, I've updated them.
Q for reviewers: I have a branch to change all other `AdoptOpenJDK/openjdk-infrastructure` references to this repo; is that something desirable?
- n/a ~[FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate~
- n/a ~other documentation is changed or added (if applicable)~
- n/a ~playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)~
- n/a ~for inventory.yml changes, bastillion/nagios/jenkins updated accordingly~
=> github: Fix repo links in template

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/MacOSX.yml
Ref https://github.com/adoptium/infrastructure/issues/1910#issuecomment-879759594
On our Macos machines which have an OS of 10.13 or older, the playbooks hit an error when trying to upgrade the packages on the machine using brew
```
fatal: [test-macstadium-macos1013-x64-1]: FAILED! => {"changed": false, "msg": "Warning: You are using macOS 10.13.\n
We (and Apple) do not provide support for this old version.\n
You will encounter build failures with some formulae.\nPlease create pull requests instead of asking for help on Homebrew's GitHub,\nTwitter or any other official channels. You are responsible for resolving\n
any issues you experience while you are running this\n
old version.\n\n
Error: Your Command Line Tools are too outdated.\nUpdate them from Software Update in the App Store or …
```
=> UnixPb: Add condition which skips brew upgrade on macos versions 10.13 or older

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/jckservices_iptables/tasks/main.yml
=> unixPB: allow internal azure hosts to reach jckservices

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/yum/tasks/main.yml
ref https://github.com/adoptium/infrastructure/issues/2126
Discovered the `yum-config-manager` command which, amongst other things, allows a user to enable and disable repos. Tested on ojdk06. Works as expected
=> AIXPb: Ensure AIX repos are enabled

ansible/docker/Dockerfile.CentOS6
ref https://github.com/adoptium/infrastructure/issues/2301
The centos 6 docker build and push github check has been failing when it tries to install ansible, https://github.com/adoptium/infrastructure/pull/2300/checks?check_run_id=3442260626 for example. I've changed it to a simple yum install. I've tested this on one of the dockerhost machine, the changes build without fail
=> Github: change python and ansible install to yum

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Jenkins_User/tasks/main.yml
Signed-off-by: Frederic Gurr <frederic.gurr@eclipse-foundation.org>
=> ansible: Change ownership of jenkins' ~/.ssh/known_hosts

ansible/inventory.yml
OS level in the name was wrong and misleading - fairly obvious fix :-)
=> inventory: Fix name of Altra which had incorrect Ubuntu version

ansible/pbTestScripts/buildJDK.sh, ansible/pbTestScripts/buildJDKWin.sh, ansible/pbTestScripts/vagrantPlaybookCheck.sh
ref https://github.com/adoptium/infrastructure/issues/2295
I've added a check to determine whether the fork is labelled either `openjdk-infrastructure` or `infrastructure`.
This code works when run separately, but not when I add it to the vagrantPlaybookCheck.sh script; the script seems to get caught on the curl commands. Hence I'm keeping this as a WIP for now
=> pbTests: Add check to see if fork exists

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/jckservices_iptables/tasks/main.yml
=> unixPB: add esmv4-macos11-arm64 to jckservices iptables

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml
ref https://github.com/adoptium/infrastructure/issues/2312
=> UnixPb: add fakeroot to centos and ubuntu

ansible/inventory.yml
Provisioned via the new prototype Marist Cloud interface. This will expand our available test coverage to RHEL8 and SLES15 (And also RHEL7 since the current RHEL7 build machine was deactiveated - by label - for testing)
=> inventory: Add three extra Marist Cloud test machines

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.cent8
The install of fakeroot, later in the dockerfile, will fail if epel-release is not installed
=> UnixPb: add epel-release to centos8 dockerfile

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/bootjdk/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
ref https://github.com/adoptium/infrastructure/issues/2337
=> Playbooks: Add java 17 bootstrap to Unix, Windows and AIX playbooks

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/CentOS6-Cent7SSL/tasks/main.yml
Ref:  [VPC-1331](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1331/OS=CentOS6,label=vagrant/console ), #2342
For some reason, the CentOS6_Cent7SSL role was implemented but has never seemingly worked for VPC. The issue was that you can't install `openssl-1.0.2` or `openssl-libs-1.0.2` separately, they _need_ to be installed together, as suggested by the post that inspired the role in the first place: https://forums.centos.org/viewtopic.php?f=13&p=328731
This has been updated to reflect that. I also updated the checksum as that was wrong (I checked 3 times to ensure that it wasn't just a dodgy download).
=> UnixPB: Install OpenSSL102 & lib pkgs together

ansible/pbTestScripts/README.md, ansible/pbTestScripts/updateBoxes.sh
Ref: #2375 , https://ci.adoptopenjdk.net/job/Will-VagrantBoxUpdate/
The new Jenkins job can be found in the above link. While it is still unable to trigger VPC (hence only referencing the issue), I don't believe that will require any script changes, hence the PR. [Run 2](https://ci.adoptopenjdk.net/job/Will-VagrantBoxUpdate/2/console) shows the job working as expected.
=> pbTests: Add updateBoxes script.

.github/workflows/build_vagrant.yml, ansible/vagrant/Vagrantfile.Solaris10
Fixes: #2349 , Ref: [VPC-1336](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1336/)
This resolves the issue that VPC has been having, in that updating  `sudo` to the latest version, causes it to stop working. The error message says: 
```
sudo: unable to resolve host adoptopenjdkSol10: node name or service name not known\r\r\nsudo: error initializing audit plugin sudoers_audit\r\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error
```
For some reason, the 'unable to resolve host' message had never caused `sudo` to fail, however with the newest update (`1.9.8p2`) it does. When I set `adoptopenjdkSol10` as the hostname, and add it to `/etc/hosts`, the error no longer occurs.
This PR should fix both the GitHub check and VPC, as they use the same Vagrantfile.
=> vagrant: Configure hosts & hostname in Sol10 VF

ansible/inventory.yml
I've renamed test-packet-ubuntu1604-x64-2 to test-packet-ubuntu2004-x64-2 in the inventory.yml file and in jenkins, https://ci.adoptopenjdk.net/computer/test-packet-ubuntu2004-x64-2/ (It was 1804 in jenkins before I changed it)
I think the machine was upgraded to 2004 recently
```
root@test-packet-ubuntu1604-x64-2:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
```
=> Inventory: change testpacket machine name to 2004

ansible/pbTestScripts/updateBoxes.sh, ansible/vagrant/Vagrantfile.Debian8
Ref: https://adoptium.slack.com/archives/C53GHCXL4/p1637069847046900
Turns out updating Vagrant boxes was a bad idea... This is a temporary fix whilst I figure out how to fix it :-)
=> pbtests: Don't update Debian8 boxes

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/CodesignCert/tasks/main.yml
Fixes: #2315, ref: [VPC-1339](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1339/) 
Just simple module name change.
=> winPB: Correct codesign cert win_file module

ansible/inventory.yml
Scaleway armv7l machines have [not been available for a while](https://github.com/adoptium/infrastructure/issues/2192) but were still in our inventory. They have now been removed from jenkins, bastillion and nagios, so this is the only remaining place to remove them from.
=> inventory: Remove scaleway armv7l machines

ansible/inventory.yml
- Add new systems at OSUOSL to inventory - using aix7RT-ppc-N -
- where R is release, T is Technology Level, N is node number
=> aixPB: Update inventory with new hostnames (replace 'ojdk' with 'adopt')

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Debian.yml
Ref: [VPC-1345](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Debian8,label=vagrant/1345/console)
The LetsEncrypt DST_Root_CA_X3 ca-certificate [expired on the 30th of September](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/). This doesn't appear to be an issue for newer distributions of Debian, but it affects Debian8. To fix, according to [OpenSSL](https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/), machines running OpenSSL-1.0.2 need to remove this certificate from their trust store, in `/etc/ca-certificates.conf`, and then refresh them. 
Only thing I'm not 100% sure of, is the `regexp` field for the `replace` module. This will work for the Vagrant box, as the listing is `mozilla/DST_Root_CA_X3.crt`; however, I'm not sure if it …
=> UnixPB: Remove DST_Root_CA_X3 cert for Deb8

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Alpine.yml
Currently, Alpine comes installed with a version of sed that isn't compatible with the JDK8u build scripts:
```bash
bash-5.1# sed --version
This is not GNU sed version 4.0
```
This PR switches sed to be the GNU sed version:
```bash
bash-5.1# sed --version
sed (GNU sed) 4.8
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Jay Fenlason, Tom Lord, Ken Pizzini,
Paolo Bonzini, Jim Meyering, and Assaf Gordon.
This sed program was built without SELinux support.
GNU sed home page: <https://www.gnu.org/software/sed/>.
General help using GNU software: <https://www.gnu.org/gethelp/>.
E-mail …
```
=> unixPB: install GNU sed on Alpine

.github/workflows/build_vagrant.yml
`macos-latest` now provides macOS 11 which doesn't have vagrant pre-installed. This PR pins the macOS version to fix the CI failure
=> github: pin vagrant executor to macos-10.15

ansible/pbTestScripts/buildJDK.sh, ansible/pbTestScripts/buildJDKWin.sh
Ref: [VPC-1350](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1350/OS=Solaris10,label=vagrant/console) , #2405 
With the work being done to create a new Solaris10 Vagrantfile, we're finding out some quirks about the old box. The old box had a bunch of tools installed in `/usr/xpg4/bin`, which are apparently a variant of commands (such as awk, grep, etc.) that will comply with a different standard: 'POSIX.2/POSIX.2a/SUS/SUSv2/XPG4' , according to [this thread](https://www.unix.com/solaris/164073-what-difference-between-xpg4-bin-usr-bin.html).
While the new box also has this, the changes to the `awk` command that this PR does, will work for the standard `awk` in `/usr/bin/awk` as well, making the scripts more portable and easier to read.
Note: I can't test this on the new Solaris box …
=> pbTests: Replace gsub in awk command

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/yum/tasks/main.yml
ref https://github.com/adoptium/infrastructure/issues/2364#issuecomment-984629665
The build process only seems to detect freetype on the system when freetype is kept at version 2.8
=> AixPb: keep freetype2 and autoconf at desired versions

ansible/pbTestScripts/testJDK.sh
This fixes:
```
12:44:54 find: bad option -maxdepth
12:44:55 find: [-H | -L] path-list predicate-list
```
and the resulting:
```
12:48:36 makefile:20: *** Please provide TEST_JDK_HOME value..  Stop.
12:48:42 makefile:20: *** Please provide TEST_JDK_HOME value..  Stop.
```
which shows up in the Solaris VPC checks
=> pbTests: Stop using find -maxdepth as it is nonstandard

ansible/pbTestScripts/testJDK.sh, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_10/tasks/main.yml
Fixes #2386 
Change to testVPC.sh was due to a bug when building later JDKs which made the process pick up the `static-libs` directory instead of the JDK, which causd a test failure (described in the comments below)
=> unixPB: Install gcc 10.3 into /usr/local/gcc10

FAQ.md
Obvious fix to remove travis which we are not using for this task and just confuses anyone trying to debug issues.
=> doc: Update FAQ with correct location of CentOS7 docker build image creation

Jenkinsfile
fixes: https://github.com/adoptium/infrastructure/issues/2432
=> jenkinsfile: switch dockerfile push to use jenkins tooling

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_48/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_7/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_9/tasks/main.yml
Ref: #2422 
As per my comment in the [referenced issue](https://github.com/adoptium/infrastructure/issues/2422#issuecomment-1008772277), these queries are not changing the machine state, so they shouldn't report `changed`. 
I prioritized these GCC roles, so they accurately reflect the new GCC-10 role from #2420.
=> unixPB: Add changed_when fields to shell modules, in gcc roles

ansible/vagrant/Vagrantfile.CentOS8
Fixes: #2462 
Updates the `baseurl` for the BaseOS and Appstream repos in CentOS8, as CentOS8 is now EOL.
=> VFs: Update yum repos for C8

ansible/inventory.yml
Fixes https://github.com/adoptium/infrastructure/issues/2475
=> inventory: Reallocate build-macstadium-macos1014-x64-3 to test

ansible/inventory.yml
rename aix71-ppc64-1 to aix715-ppc64-1
to be like the other AIX test systems (-2, -3, -4).
Add current oslevel -s that fits bos.mp64 (kernel) level install to description:
As AIX 7.2 level is fluid - for consistent naming have all system labels as:
aix72-ppc64-N (-1, -2, -3, -4)
Note:
- aix72-ppc64-1 is at 7200-04-02-2028
- aix72-ppc64-2 is at 7200-02-05-1938
- aix72-ppc64-{3,4} are not installed yet (for jenkins usage)
- I (don't think I am) am not able to modify any of bastillion, nagios, or jenkins. If those files are also in this repository - please point me at them - and I'll do my best to update them as well.
=> inventory: update AIX systems: remove test-ibm:, rename some osuosl systems

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/yum/tasks/main.yml
update task code for accurate ansible reporting on changed: or ok:
Rewrite comments so they better fit with 80 character line length.
=> aixPB: remote 'set -o pipefail' as lint measure (yum role)

ansible/inventory.yml
The expectation is the the older two macincloud systems will be removed once these new ones are activated since they are running old operating systems, so this effectively fixes: https://github.com/adoptium/infrastructure/issues/2476 and https://github.com/adoptium/infrastructure/issues/1922
=> inventory: add new macincloud Monterey/x64 systems

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/disable_gui/tasks/main.yml
ref https://github.com/adoptium/infrastructure/issues/2468
Right now running `systemctl set-default multi-user` only works on centos 7+ and ubuntu18+
Other distros should have similar commands which I will add to this pr shortly
=> UnixPb: Turn off unnecessary desktop environment

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Xcode/tasks/main.yml
ref https://github.com/adoptium/temurin-build/pull/2876 and https://adoptium.slack.com/archives/C09NW3L2J/p1646743526526249
The xcode switch path can be set to "/Applications/Xcode.app" for jdk8, 11 and 17+. Hence this can be set as the default path in the playbooks, without having to execute the commands in the build scripts
=> UnixPb: Set xcode switch path to full path on build machines

ansible/inventory.yml
As per PMC call this week, decomission the original macincloud 10.10 systems, and also the ones we have from macstadium that are at a lower level from the one listed on our [supported platforms page](https://adoptium.net/supported_platforms.html).
Fixes https://github.com/adoptium/infrastructure/issues/2496
=> inventory: remove older (pre 10.14) macos systems

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/tasks/main.yml
ref https://github.com/adoptium/infrastructure/issues/2517#issuecomment-1084815153
Ipv6 needs to be enabled in the docker engine on our dockerhost machines in order for certain ipv6 net tests, in jdk_net, to pass on containers on these dockerhost machine
=> UnixPb: Enable ipv6 on docker on dockerhost machines

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Xcode/tasks/main.yml
ref https://github.com/adoptium/infrastructure/issues/1910#issuecomment-1060625222
Often times the Apple ID variables, Apple_ID_User, Apple_ID_Password, FASTLANE_SESSION, are not defined during a playbook run. I am not sure where these variables are kept. AWX does not have access to them despite having access to the secrets repo.
In any case, the playbook should not halt if these variables are not present
=> UnixPB: Skip xcode role if apple id variables are not defined

.ansible-lint, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/handlers/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/tasks/main.yml
-  https://github.com/ansible/ansible-lint/pull/1908 add to v6.0.0
- GH action installing 6.0.2 ansible-lint since mid March which broke lint step
- yamllint for .ansible-lint file
- no-handler lint error
=> fix: disable new fqcn ansible-lint rule

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.f34, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.f35, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/README.md, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Xcode/tasks/main.yml
- use port 2232 and 2233 on host
- use ant 1.10.12
- fix ansible-lint error  [unnamed-task: All tasks should be named] (https://github.com/adoptium/infrastructure/runs/5884567208?check_suite_focus=true#step:5:133)
Ref: https://github.com/adoptium/infrastructure/issues/2183
=> unixPB: add two new dockerstatic container for fedora34/35

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.cent8
- when enabled check on dockerstatic dockerfile found issue: 
https://github.com/adoptium/infrastructure/runs/5970485601?check_suite_focus=true
`Step 2/23 : RUN dnf -y update && dnf install -y perl openssh-server unzip wget epel-release
---> Running in 4732eaff2945
CentOS Linux 8 - AppStream                      108  B/s |  38  B     00:00    
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
The command '/bin/sh -c dnf -y update && dnf install -y perl openssh-server unzip wget epel-release' returned a non-zero code: 1` 
- fixed with https://github.com/adoptium/infrastructure/runs/5970875795?check_suite_focus=true
- mirror update for centos8
Ref: https://github.com/adoptium/infrastructure/issues/2183
- [x ] commit message …
=> UnixPB: fix dockerstatic build on centos8

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml
ref https://github.com/adoptium/infrastructure/issues/2281#issuecomment-1059322275
Since changing from hotspot to temurin, bootjdks (on MacOS) are installed into `/Library/Java/JavaVirtualMachines/temurin-*.jdk/` rather than `/Library/Java/JavaVirtualMachines/adoptopenjdk-*.jdk/`. The build scripts still look in the former directory, https://github.com/adoptium/temurin-build/blob/c4842313fe56dacd4986e35d34d132db979bf8df/build-farm/platform-specific-configurations/mac.sh#L82 as do the playbooks. Making this link would solve this problem.
This would also ensure idempotency for the `adoptopenjdk_install` role for MacOS
=> UnixPb: Symlink adoptopenjdk install directory to temurin install directory on macos

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Fedora.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/build_packages_and_tools.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Fedora.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_10/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_7/tasks/main.yml, ansible/vagrant/Vagrantfile.Fedora35
=> Fixes #2507 - UnixPB : Fedora Compatible Playbooks

FAQ.md, Jenkinsfile, README.md, ansible/docker/Dockerfile.Alpine3, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Alpine.yml
- update Alpine play to install jdk16/17/18 from zulu which has support for aarch64
- add jenkins stage to build alpine image
- skip install test_tools packages
Ref: https://github.com/adoptium/infrastructure/issues/2497
=> docker: add support for Alpine aarch64 image #2497

.github/workflows/build.yml, .github/workflows/build_windows.yml
- remove branch check per action since it is done in "on"
- add buildx to enable[ cache feature](https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#inline-cache)
- move auth to login-action
- [x ] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ x] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
=> github: upgrade build-push-action to v2 to fix "linter" warning

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/bootjdk/tasks/openjdk.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.cent8, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.f33, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.f34, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.f35, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.u1604, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.u1804, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.u2004, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.u2104, ansible/playbooks/correct_vnc_install.yml, ansible/playbooks/ubuntu-jck.yml, ansible/playbooks/vagrant.yml
- [ x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ x] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
=> docker: update Dockerstatic to download jdk from api.adoptium.net v3

.github/workflows/build.yml, FAQ.md, Jenkinsfile
Now that we've added support for Alpine aarch64 docker images, it makes sense to move the x64 build to also be on Jenkins as it makes the manifest command much simpler to run.
=> docker: fix alpine manifest build for amd64

ansible/docker/Dockerfile.Alpine3
Temporary fudge while we don't have an `ea` build for jdk-19 in the temurin API so cannot download it during the build process.
Currently JDK19 is forced to bootstrap with 19 https://github.com/adoptium/temurin-build/blob/8d87dd642382b72337ee48e6b74c98cf1f234c89/build-farm/make-adopt-build-farm.sh#L145
We can remove this once we have ea builds regularly being published (And in fact we can hopefully switch away form zulu generally as per https://github.com/adoptium/infrastructure/issues/2564
=> docker: Force JDK19_BOOT_DIR=zulu18 for Alpine

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.ubi8, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/scripts/updatepackages.sh, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/tasks/main.yml
=> unixPB: add new dockerstatic container for Redhat UBI8 #2532

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml
For jdk 11, 17 and 18, since arm64 binaries are available, it would be best to use those instead of x64 ones
=> UnixPb: Add arm64 binaries on MacOS instead of x64 when available

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/jckservices_iptables/tasks/main.yml
Adding the IP for a new mac machine as described here: https://github.com/temurin-compliance/infrastructure#adding-new-machines
=> ansible: Add noh7B-macos12-arm64 ip

ansible/inventory.yml, ansible/plugins/inventory/adoptopenjdk_yaml.py
=> inventory: add our two hetzner infrastructure machines (nagios+jenkins)

.github/workflows/build_wsl.yml, FAQ.md, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2013/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2017/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2019/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Windows_Updates/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/shortNames/scripts/shortName.ps1, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/shortNames/tasks/main.yml
This will allow everyone to test the playbook using WSL (the Linux CL built into modern windows).  This also allows simpler testing of the Playbooks as we can then use WSL support in GH Actions. This allows Ansible to run 'natively'.
This PR also adds the `reboot` tag to tasks that require a windows restart to be run as well as a modification to the shortnames script to both add a registry key (required for win 2022) and also skip creating a shortname if the original directory doesn't exist.
=> pbTests add win playbook testing using WSL

ansible/playbooks/Supporting_Scripts/Nagios_Ansible_Config_tool/templates/check_ntp_timesync.cfg, ansible/playbooks/Supporting_Scripts/Nagios_Ansible_Config_tool/templates/check_timesync.cfg, ansible/playbooks/Supporting_Scripts/Nagios_Ansible_Config_tool/templates/zypper.cfg
- on centos/rhel default location is /usr/lib64/nagios/plugins , there is no /usr/lib/nagios/plugins/ unless we create symlink
- on unbuntu/debian, default is /usr/lib/nagios/plugins/
- we should use /usr/local/nagios (symlink) to access for different distro since the symlink has been created there for different ones.
this PR should not change anything for nagios on ubuntu/debian but fix centos/rhel
Related to https://github.com/adoptium/infrastructure/issues/2199
=> ansible: fix wrong path for nagios NTP check on Centos/RHEL

ansible/pbTestScripts/vagrantPlaybookCheck.sh
ref https://github.com/adoptium/infrastructure/issues/2581
=> VPC: Clean up vagrant boxes on exit

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Get_Vendor_Files/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/WMF_5.1/tasks/main.yml
Ref: #2422 , #2449
The same as #2449 , however this is specific to the Windows PB. 
This is currently blocked by #2178 , as we're unable to use VPC to test the changes.
=> winPB: Add 'changed_when: false' when using shell tasks to query

.github/ISSUE_TEMPLATE/ansible.md, .github/ISSUE_TEMPLATE/machineaccess.md, .github/ISSUE_TEMPLATE/teamaccess.md, .github/PULL_REQUEST_TEMPLATE.md
This will avoid github misinterpreting our checkboxes, since by
default github shows how many of these are complete, which is
confusing, so we ask PR submitters to remove lines that are invalid
=> github: Adjust templates to stop misinterpretation of checkboxes

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml
Fixes https://github.com/adoptium/infrastructure/issues/2611
ccache will be installed from source later on in the playbook execution in the ccache role on those OSs
Partial revert of https://github.com/adoptium/infrastructure/pull/2241
VPC Not applicable as it does not operate on RHEL
=> unixPB: Avoid attempting to install ccache on RHEL7

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml
- as dependencies they will be installed by "package"
=> unixPB: remove two package for docker installaion

ansible/pbTestScripts/testJDK.sh
=> VPC: Exclude sbom directory from TEST_JDK_HOME export for tests.

ansible/docker/Dockerfile.Alpine3
Alpine openjdk 8, 17+ currently won't compile with 3.16 and gcc 11.2 until fixed upstream: https://bugs.openjdk.org/browse/JDK-8288849
Signed-off-by: Andrew Leonard <anleonar@redhat.com>
=> ansible: Keep Alpine building with 3.15 until OpenJDK supports

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
- it should only be used for openj9
Fixes: https://github.com/adoptium/infrastructure/issues/1898
=> ansible: disable installing freemarker on unix, win and mac

ansible/inventory.yml
Only one of them, but in a push the test machine (which we were using for building JDK19+ for a while) can be used too as a backup system.
=> Add AIX 7.2 build machine to the inventory file

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/criu/tasks/main.yml
Add role to install CRIU on CentOS/RHEL 7 and Ubuntu.
Required by OpenJ9.
Related: https://github.com/eclipse-openj9/openj9/issues/14016
=> unixPb: Add role to install CRIU on Linux x86-64

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.f33, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.f34, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.f35
ref https://github.com/adoptium/infrastructure/issues/2631#issuecomment-1188992683
The jdk8 test java/nio/file/Files/probeContentType/Basic.java seems to pass on fedora only when this package is installed
Tested on test-docker-fedora36-x64-1
Before install
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5225/
After install
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5226/
=> unixPb: Install shared-mime-info on fedora docker static containers

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gmake/tasks/main.yml
We have not been verifying this source download. This fixes that omission.
The download has been verified with GPG using the key from the Ubuntu keyserver prior to generating the SHA checksum for inclusion into this file.
=> unixPB: verify sha256sum of gmake 4.1 source

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml
I do not believe these repositories are needed for anything. Will verify through VPC. Slight possibility they're needed on certain architectures, however we do not install openjdk-7-jdk on here (We do on Debian, hence not making the same changes there)
=> unixPB: remove unneeded repos from Ubuntu playbooks

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Debian.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Debian.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_7/tasks/main.yml
Not only do we use our self-built one, but GCC-7 is not available in the Ubuntu 22.04 repositories, so the playbook fails. We could bypass this on 22.04 and later, but since we do not use it for building it is simpler to remove it. We install the `gcc` package elsewhere so we will always have a system installed compiler even with this change.
=> unixPB: Remove gcc-7 package install as we use our self-built one

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/rhel.yml
ref https://github.com/adoptium/infrastructure/issues/2700
The former repo does not allow for docker to be installed onto our s390x rhel7 systems. Changing it to https://download.docker.com/linux/rhel/7/s390x/stable/ seems to work
https://awx2.adoptopenjdk.net/#/jobs/playbook/202?job_search=page_size:20;order_by:-finished;not__launch_type:sync
=> Docker: Fix docker repo for s390x rhel

.github/workflows/build_mac.yml, FAQ.md
Fix: https://github.com/adoptium/infrastructure/issues/2715
=> GH: upgrade runner from macos-10.15 to macos-11

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/SLES.yml
Cronie is needed for crontab tasks. 
Without bzip2, the [expat](https://github.com/adoptium/infrastructure/blob/7c29bb812d58c4df12cfa2dad1779f9f2c724fe8/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/SLES.yml#L240) tarball will not extract
=> UnixPb: Install Cronie and Bzip2 for SLES

.github/workflows/build_vagrant.yml
- according to https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
macos-12 has vagrant and virtualbox pre-installed, so no need brew install virtualbox again
- macos-11 does not and  add "brew install --cask vagrant" still problem to run it
- set the same config e.g ssh, time out etc in the action to match whats set in the vagrantPlaybookCheck.sh (as in VPC jobs)
-  this PR wont make GH action vagrant check on Solaris green, due to https://github.com/adoptium/infrastructure/issues/2694 need to be fixed as well. but using test with an existing [tnarik/solaris10-minimal](https://vagrantcloud.com/tnarik/solaris10-minimal) https://github.com/adoptium/infrastructure/runs/8232496747?check_suite_focus=true it is able to do "vagrant up" 
Fix: …
=> github: macos-12 for solaris

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/logs/tasks/main.yml
ref https://github.com/adoptium/infrastructure/issues/2745
This is currently very rudimentary. All it does it update a file on the remote host whenever the playbook is run to indicate the date and time of the run.
Limitations (to hopefully be resolved once pr is ready for review):
~Only runs when playbook is run as a whole. Not run if tags are specified~
~Only indicates date and time, specific tags/roles and a 'git hash' of the playbook should be included~
Feel free to provide feedback
=> UnixPb: Add (basic) logs role

.github/workflows/build.yml, ansible/docker/Dockerfile.Alpine3, ansible/docker/Dockerfile.CentOS6, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adopt_etc/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/logs/tasks/main.yml
ref https://github.com/adoptium/infrastructure/issues/2745
Adds the latest commit SHA to the logs stored on the remote machine in the jenkins directory. Thankfully, the default working directory of ansible seems to be the directory of the playbook, in this case the `main.yml` file. Which means `git rev-parse HEAD` will always be run in the correct directory.
Tested from my workstation and https://awx2.adoptopenjdk.net/#/jobs/playbook/485?job_search=page_size:20;order_by:-finished;not__launch_type:sync (includes debug tasks which I have removed)
=> UnixPB: Add latest commit SHA to ansible.log file

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml
Fixes https://github.com/adoptium/infrastructure/issues/2735
Introduced by https://github.com/adoptium/infrastructure/pull/2691 (arm32 specific)
The Temurin builds use our self-built compilers installed into /usr/local. As a courtesy to people who prefer to use the system installed ones and skip the installation of ours, we make those available too, along with other parts of the toolchains that may be required. This will default those versions to the normal `gcc` and `g++` on those distributions and not lock them to particular versions.
=> Install default gcc and not attempt to do individual versions

ansible/README.md, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/7-Zip/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java_install/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2013/tasks/main.yml
Update the VS2013 role to work from  local installation media.
This is only required until VS2013 is no longer used.
Fixes #2178
=> winPB: Fix broken Visual Studio 2013 role to use local installation media

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml
Packages do not exist on RHEL8 and later, therefore do not attempt to install them.
Fixes https://github.com/adoptium/infrastructure/issues/2725 https://github.com/adoptium/infrastructure/issues/2702
NOTE TO REVIEWERS: Linter issues unrelated to this PR
=> unixPB: Do not install 31-bit support files on RHEL/s390x

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/rhel.yml
ref https://github.com/adoptium/infrastructure/issues/2710
Added support for docker to be installed on rhel8 (ppc64, x64 and s390x)
Old ppc64le and x64 repo url no longer valid. Updated them to use a centos docker repo
The docker repo key is the same for rhel and centos
=> Docker: Add Ansible support for docker on Rhel8

ansible/docker/Dockerfile.Alpine3, ansible/docker/Dockerfile.CentOS6
ref https://github.com/adoptium/infrastructure/issues/2760
Revert `copy directory` changes that I made in https://github.com/adoptium/infrastructure/pull/2751/files#diff-cdadf2592f693c4816b592c519b913084ed2de4a238be6dbf42f75464798334bL7
The changes to which level of the infra repo gets copied are obsolete in that pr since I was able to get the SHA to be passed in as a parameter. More so, these changes are causing a build failure on our alpine images in the centos7_docker_image_updater job
https://ci.adoptopenjdk.net/job/centos7_docker_image_updater/268/execution/node/63/log/
https://ci.adoptopenjdk.net/job/centos7_docker_image_updater/268/execution/node/77/log/
```
Step 4/7 : COPY ../. /infrastructure
COPY failed: forbidden path outside the build context: ../. ()
```
=> docker: Copy from the correct directory in Centos6 and Alpine dockerfiles

ansible/docker/Dockerfile.Ubuntu2204
Adding docker file for Ubuntu 22.04. For anyone that wants to build their own JDK in a dockerfile, using the latest Ubuntu 22.04 is likely the best option for a supported distribution. This is a modified version of the Ubuntu 16.04 with simpler prereqs for Ansible that can be used if desired. Note that Adoptium does not currently use this as a build image for any platforms (Although it's possible we'd use it if we started to build in Docker for RISC-V in the future)
This has been tested on arm32 for the purposes of validating a solution to https://github.com/adoptium/infrastructure/issues/2760#issuecomment-1263801235
=> docker: Add dockerbuild file for Ubuntu 22.04

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml
Follow on to https://github.com/adoptium/infrastructure/pull/2736 which seems to have caused problems with Ubuntu16 on arm32 based on comments in https://github.com/adoptium/infrastructure/issues/2760#issuecomment-1263801235
The error which this should resolve is:
```
failed: [localhost] (item=gcc-7) => {"ansible_loop_var": "item", "changed": false, "item": "gcc-7", "msg": "No package matching 'gcc-7' is available"}
failed: [localhost] (item=g++-7) => {"ansible_loop_var": "item", "changed": false, "item": "g++-7", "msg": "No package matching 'g++-7' is available"}
```
=> unixPB: Remove gcc-7 install from Ubuntu 16

.ansible-lint
We have a number of instances where this policy of requiring jinja templates in `name:` clauses does not make sense e.g. when a path name is used (e.g. `/home/{{ Jenkins_User }}/somedir`) and I have not seen a compelling reason for this to be enforced, therefore I propose disabling it.
Ref: https://ansible-lint.readthedocs.io/rules/name/
Similarly when running the checks on this PR it was noticed that there is another error showing up in some of the rules. The second commit in skips that one too (I tried moving to warn_list: as per the snippet below but that didn't seem to work and it still showed as an error). Removal of this as an error is consistent with the comments made upstream in https://github.com/ansible/ansible-lint/pull/2512
```
warn_list:
- 'template-instead-of-copy' # …
```
=> ansible: Remove jinja name template errors

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.f35, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.sles12, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.sles15
~Draft~ pr for sles12 and sles15 dockerfiles to be hosted on dockerhost-marist-ubuntu2204-s390x-1
ref https://github.com/adoptium/infrastructure/issues/2689
=> Dockerstatic: Add sles12 and sles15 dockerfiles

Jenkinsfile, ansible/docker/Dockerfile.CentOS7, ansible/docker/Dockerfile.Ubuntu1604, ansible/docker/Dockerfile.Ubuntu2204
Alpine docker images are failing because they are not being passed the git_sha parameter. 
https://ci.adoptopenjdk.net/job/centos7_docker_image_updater/277/execution/node/58/log/
```
cd /ansible
/bin/sh: git_sha: parameter not set
The command '/bin/sh -c set -eux;  cd /ansible;  ansible-playbook -i hosts ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml -e "git_sha=$git_sha" --skip-tags="debug,hosts_file,hostname,adoptopenjdk,jenkins,nagios,superuser,docker,swap_file,crontab,nvidia_cuda_toolkit";  rm -rf /ansible; apk del ansible' returned a non-zero code: 2
```
Also added the git_sha to the centos7 and ubuntu16 dockerfiles
Using https://ci.adoptopenjdk.net/env-vars.html/ as a reference to get the git sha
=> Docker: Pass the git sha to the centos7 and ubuntu 16 dockerfiles

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/criu/tasks/main.yml
Upgrade version from v3.16 to 3.17.
Add cap_checkpoint_restore capabilities on Ubuntu 22.
=> UnixPB: Update CRIU role for Ubuntu

ansible/pbTestScripts/testJDKWin.sh
Amend testJDKWin.sh for correct paths to build JDKs, and path definition issues.
Fixes #2772 
Successful VPC Run Here : 
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1570/
=> pbTests: Fix Issue With Windows VPC Not Running Tests

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml
For an unknown reason, the playbook is not adding the jenkins user to the docker group on aarch64. The playbook does install docker on this architecture
=> UnixPb: Add jenkins user to docker group on aarch64

ansible/playbooks/nagios/README.md
Added a check for the machines with the build, windows & x64 labels  
updated the readme.md file in the ansible/playbooks/nagios/README.md with a new section detailing how to add an additional version of these checks.
fixes #2765 
cc @steelhead31 @smlambert @sxa
=> Adding a check for the machines with the build, windows & x64 labels 

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml
Install libffi6.dev.so.6 for Ubuntu 20/22 on s390x machines
Fixes #2830 
VPC Run : https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Ubuntu2004,label=vagrant/1583/console
=> UnixPB : Install LibFFI6 On Ubuntu 20/22 on s390x

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/group_vars/all/adoptopenjdk_variables.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/NSClient/tasks/main.yml
Fixes #2825 
Installs NSClient software for windows as part of the nagios monitoring improvements.
=> winPB: Install NSClient++ On Windows Hosts For Nagios Monitoring

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/jckservices_iptables/tasks/main.yml
Removes jck-marist-rhel7-s390x-1, jck-marist-ubuntu2004-s390x-1, jck-marist-ubuntu2004-s390x-2 nodes. EF issue #2214 https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2214
Signed-off-by: Paweł Stankiewicz <pawel.stankiewicz@eclipse-foundation.org>
=> Decommissioning of old Marist s390x systems

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml
Fixes https://github.com/adoptium/infrastructure/issues/2843
```
"msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /usr/lib/jvm/jdk-11.0.16.1+1\n/usr/lib/jvm/jdk-11.0.17+8",
"path": "/usr/lib/jvm/jdk-11",
"src": "/usr/lib/jvm/jdk-11.0.16.1+1\n/usr/lib/jvm/jdk-11.0.17+8"
```
Shoudl fix the regular failures on this platform in https://ci.adoptopenjdk.net/job/centos7_docker_image_updater/
=> unixPB: Stop installing two JDK8s on Alpine

ansible/inventory.yml
ref https://github.com/adoptium/infrastructure/issues/2792
I have not added the new dockerstatic containers that are hosted on both of the new x64 dockerhost machines as we do not normally add those to the inventory file
=> Inventory: Update inventory file with new equinix machines

ansible/inventory.yml
The ansible infrastructure inventory requires updates, following the rebuild/recommision of dockerhost-equinix-ubuntu2204-armv8-1 (139.178.86.243) and the removal of defunct risc9 (gdams) and spearhead machines
Fixes #2851
=> inventory: Remove 139.178.86.243 from build label hosts, add to dockerhosts dockerhost-equinix-ubuntu2204-armv8-1

ansible/inventory.yml
=> Inventory - Fix issue 2851

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/NVidia_Cuda_Toolkit/tasks/main.yml
Fixes  #2818 
Bump NVIDIA cuda to version 9.1
VPC Run Here : https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Win2012,label=vagrant/1589/
=> WinPB : Bump Nvidia Cuda To 9.1

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.deb11
The dockerfile needs curl and gnupg at the beginning of the dockerfile for the curl and gnupg commands later in the image build
=> Dockerstatic: Move gnupg and curl to top of deb11 dockerfile

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/MacOSX.yml
Required if we decide to merge https://github.com/adoptium/temurin-build/pull/3188. Switching to the GitHub FreeType adds a dependency on `automake` for the macOS build.
=> unixPB: install automake on macOS

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml
* compiling openssl v3 within container or system requires this package
* see https://github.com/eclipse-openj9/openj9/pull/14930
=> Add perl-IPC-Cmd to Redhat/CentOS installs for OpenSSL v3 compile

ansible/playbooks/nagios/roles/Nagios_Config/defaults/main.yml, ansible/playbooks/nagios/roles/Nagios_Config/scripts/Create_Nagios_Server_Configurations.py, ansible/playbooks/nagios/roles/Nagios_Config/tasks/Create_Nagios_Server_Configurations.yml
Fixes #2876 
Parameterise the valid service groups from the ansible inventory file, and fix service group matching so that when dockerhost is a valid host type, the docker-xxxx machines are not included in error.
=> Ansible: Nagios: Fix service group matching and parameterise.

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/jckservices_iptables/tasks/main.yml
Removes jck-equinix_esxi-solaris10u11-x64-1, jck-equinix_esxi-solaris10u11-x64-2 EF issue #2428 https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2428
Signed-off-by: Pawel Stankiewicz <pawel.stankiewicz@eclipse-foundation.org>
- [ x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
=> ansible: Decommissioning of old solaris/x64 systems

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/group_vars/all/adoptopenjdk_variables.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Alpine.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Fedora.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Solaris.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/ant/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/autoconf/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/cmake/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/curl/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gmake/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/maven/tasks/main.yml, ansible/playbooks/Supporting_Scripts/package_signature_verification.sh
ref https://github.com/adoptium/infrastructure/issues/2233
Left to do
Example of usage:
```
./package_signature_verification.sh -s path_to_sig_file (or -sl sigfile_url) -f path_to_binary (or -fl binary_url) -k public_key
```
I'm still undecided whether to import all of the gpg keys at the beginning of the playbook, or at each role which uses it
=> UnixPB: Script to provide GPG signature verification for downloaded binaries

ansible/inventory.yml
Ref: https://github.com/adoptium/infrastructure/issues/2911#issuecomment-1411860221 https://github.com/adoptium/infrastructure/issues/2465 https://github.com/adoptium/infrastructure/issues/1843 - these have been marked offline to verify that their removal will not cause problems and so can now be safely deleted.
=> inventory: Remove two old AWS machines

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
Based on the current set of supported java versions, this ensures that a suitable GA boot JDK is available on each system (18 and 19) so it doesn't have to be downloaded at build time.
Part of me also wants to remove JDK 8 and 11 as well but I'm not feeling that brave ... yet. Will be dependent on  https://github.com/adoptium/infrastructure/issues/2763 being complete and moving all systems to JDK17.
=> unixPB: Adjust boot JDKs to current required ones. Remove JDK11

Jenkinsfile
ref https://github.com/adoptium/infrastructure/issues/2753
If we're using this job to push the centos6 image to dockerhub, then am I correct to assume that we then do not have to push the image to dockerhub during the github workflow https://github.com/adoptium/infrastructure/blob/de2d533f614be45ea37d34082efc306f1e2f4e74/.github/workflows/build.yml#L20, and just use the pr workflow as a test?
=> Jenkins: Add centos6 build job to centos7_docker_image_updater jenkins job

.github/workflows/build_qemu.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
Migrated QEMU playbook check functionality. Relevant docs here https://github.com/uraimo/run-on-arch-action
The gh action does not support riscv, so that will still need to remain in QPC.
This yaml file is alot easier to maintain than the entire QPC jenkins job, and its alot easier to add new arch distro combos
=> Workflow: Migrate QEMU playbook check to github workflow

.ansible-lint, .github/workflows/build_vagrant.yml, .github/workflows/build_wsl.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/X11/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/ant/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/ant_contrib/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/bootjdk/tasks/openjdk.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/rbac/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/rbac/tasks/setsecattr.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/security/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/users/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/users/tasks/nagios.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/users/tasks/zeus.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/xlc_v13/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/xlc_v16/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/yum/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_ITW_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/dockerhost.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/git-hg-jenkins.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/linux_installer_setup.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Alpine.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Debian.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Xcode/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/trss.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/ubuntu-jckservices.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml, ansible/playbooks/nagios/roles/Nagios_Config/tasks/Get_Ansible_Inventory.yml
Correct a number of ansible linter errors related to structure / task names etc.
Also add 3 new exclusions to the linter excludes, as a large number of changes would need to be made and tested.
- 'no-free-form' # Exclude As Requires Significant Changes ( 196 changes required )
- 'fqcn[action]' # Exclude As Requires Significant Changes ( 249 changes required )
- 'args[module]' # Exclude Experimental Rule Validation ( Prevents 4 experimental warnings )
=> Ansible: Ansible Linter related fixes

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.ubi8
ref https://github.com/adoptium/infrastructure/issues/2882#issuecomment-1385769644
These packages are needed on ubi8 for jdk_management tests to pass, see https://github.com/adoptium/infrastructure/issues/2882#issuecomment-1384516670
=> Dockerstatic: Add packages for uptime, diff and hostname for UBI8

ansible/playbooks/nagios/roles/Nagios_Server/tasks/configure_nagios_core.yml
A default (blank) servicegroups.cfg file is required to be added to the base nagios configuration, along with the configuration changes to nagios.cfg to ensure that the nagios server can be started.
=> NagiosPB : Create service groups config file

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/SLES.yml
Update unix playbooks for SLES12 and SLES15 to create a symlink for libffi.so.6, to the relevant installed version.
Fixes Build [#1058](https://github.com/adoptium/temurin-build/issues/1058)
VPC Running at : https://ci.adoptium.net/job/VagrantPlaybookCheck/1617/
=> UnixPB: Add symlinks for libffi.so.6 on SLES12 & SLES15

Jenkinsfile
ref https://github.com/adoptium/infrastructure/issues/2753
We are seeing failures in the centos6 build of the centos7_docker_image_updater pipeline, https://ci.adoptium.net/job/centos7_docker_image_updater/. Seeing as I have no ETA on when I can get this fixed, I am temporarily removing it from the pipeline as it is holding up the Docker Manifest stage of that job
=> Temporarily remove the centos6 build from centos7_docker_image_updater

ansible/docker/Dockerfile.RHEL7, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml
Fixes https://github.com/adoptium/infrastructure/issues/2731
Note that this has been hard coded with UID1002 which is the `jenkins` user ID as it is deployed on our Marist/s390x hosts. Other systems may vary, and will result in the error from https://github.com/adoptium/infrastructure/issues/2834
Requires https://github.com/adoptium/ci-jenkins-pipelines/pull/611 to be usable. We should also consider if this can reasonably be added into the [docker image updater](https://ci.adoptium.net/job/centos7_docker_image_updater/) job or have another way to update these images when required.
=> docker: add RHEL7 dockerfile for s390x builds

ansible/inventory.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/README.md
Fixes #2938 
Add new windows 2022 machines to inventory, and update the windows playbook documentation on how to install the jenkins agent as a service.
Jenkins : https://ci.adoptium.net/computer/build-azure-win2022-x64-1/ & https://ci.adoptium.net/computer/build-azure-win2022-x64-2/
Nagios :  https://nagios.adoptopenjdk.net/nagios/cgi-bin/extinfo.cgi?type=1&host=build-azure-win2022-x64-1 & https://nagios.adoptopenjdk.net/nagios/cgi-bin/extinfo.cgi?type=1&host=build-azure-win2022-x64-2
=> inventory: Add win2022 machines and update windows docs for installing jenkins agent as a service.

ansible/inventory.yml
The server is no longer needed as we've switched win aarch64 builds to win2022
=> inventory: decommission win 2016 build server

CONTRIBUTING.md, README.md, docs/Backups.md, tools/run_backups
Fixes https://github.com/adoptium/infrastructure/issues/1295
For ease of reviewing feel free to start browsing the formatted pages at https://github.com/sxa/infrastructure/tree/backupdocs#backups
Note that the script being added here is the one that has been used live on the server for sometime other than me changing backticks to `$(...)` which is a known thing that upsets the linter so the functionality is basically sound ;-)
=> doc: Add information on adoptium server backups

ansible/inventory.yml
Fixes issue #1655 
Remove marist test host, as machine has been replaced, and this one should be decomissioned.
Host will be removed from nagios & jenkins, once this PR is merged.
=> inventory: Remove decommissioned marist test host.

ansible/playbooks/nagios/roles/Nagios_Server/tasks/install_nagios_core.yml
The nagios server core installation creates a nagios user, but doesn't create its home directory.
(https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
=> NagiosPB: Fix: Create missing nagios users home directory

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/MacOSX.yml
10.15 has been out of support for some time now, https://endoflife.date/macos
```
TASK [Common : Upgrade installed packages] *************************************
fatal: [test-macstadium-macos1015-x64-1]: FAILED! => {"changed": false, "msg": "Warning: You are using macOS 10.15.\nWe (and Apple) do not provide support for this old version.\nIt is expected behaviour that some formulae will fail to build in this old version.\nIt is expected behaviour that Homebrew will be buggy and slow.\nDo not create any issues about this on Homebrew's GitHub repositories.\nDo not create any issues even if you think this message is unrelated.\nAny opened issues will be immediately closed without response.\nDo not ask for help from Homebrew or its maintainers on social media.\nYou may ask for help in …
```
=> unixPb: Skip MacOS package upgrade on 10.15 and under

ansible/inventory.yml
test-osuosl-aix72-ppc64-3 was never built
test-osuosl-aix72-ppc64-4 is (also) known (and configured) as build-osuosl-aix72-ppc64-1
Fixes #3052 
- bastillion/nagios/jenkins will need to be updated/verified by someone else. I do not have access.
=> ansible: remove test-osuosl-aix72-ppc64-[3,4]

ansible/inventory.yml
test-marist-rhel7-s390x-1 and rhel8-s390x-1 were decommissioned a while back. Just forgot to remove them from the inventory file. They are not present in jenkins
=> inventory: Remove 2 decommissioned marist boxes

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/SLES.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/sles.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NVidia_Cuda_Toolkit/tasks/main.yml
Some fixes for errors I came across while testing the s390x parts of our playbook
https://download.opensuse.org/repositories/devel:/tools/SLE_15_SP3/ is expired, replaced with https://download.opensuse.org/repositories/devel:/tools/15.4/devel:tools.repo
The installation of Git 2.31.0 failed unless put in its own block
Remove install tasks for docker on sles 12, instead install it on sles15 s390x and x64
Add conditions for Nvidia toolkit role to prevent reinstalling it
=> unixPb: Install docker on SLES15 s390x not SLES12

ansible/inventory.yml
as build-osuosl-aix72-ppc64-2
Fixes: #3068
=> ansible: rebrand build-osuosl-aix71-ppc64-2 

ansible/inventory.yml
Add build-osuosl-ubuntu2204-aarch64-1 to inventory.
=> inventory: Add osuosl aarch64 machine

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/xlc_v13/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/xlc_v16/tasks/main.yml
The `xlc13.stat.isdir is false` and the `xlc16.stat.exists is false `conditions do not resolve correctly when both packages are present on the machine. Simplifying them this way makes them work, and I have removed the 'Everythings OK message' because I feel it is not necessary (if everything wasnt ok it would fail and that would be your indication)
```
"msg": "The conditional check 'xlc13.stat.isdir is undefined or xlc13.stat.isdir is false' failed. The error was: template error while templating string: no test named 'false'. String: {% if xlc13.stat.isdir is undefined or xlc13.stat.isdir is false %} True {% else %} False {% endif %}\n\n
The error appears to be in
'/tmp/awx_1248_x1wyqy0a/project/ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/xlc_v13/tasks/main.yml': line 21, column 7, …
```
=> aixPb: Simplify conditions for when to transfer compiler packages

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/disable_sendmail/tasks/main.yml
ref https://github.com/adoptium/infrastructure/issues/3086
On some machines the `Ensure sendmail is stopped` task fails and on some it passes
```
TASK [disable_sendmail : Ensure sendmail is stopped] ***************************
ok: [build-osuosl-aix71-ppc64-1] => {"changed": false, "name": "sendmail", "state": "stopped"}
fatal: [build-osuosl-aix72-ppc64-2]: FAILED! => {"changed": false, "msg": "0513-086 The sendmail Group is not on file.\n"}
ok: [test-osuosl-aix715-ppc64-2] => {"changed": false, "name": "sendmail", "state": "stopped"}
ok: [test-osuosl-aix715-ppc64-1] => {"changed": false, "name": "sendmail", "state": "stopped"}
fatal: [build-osuosl-aix72-ppc64-1]: FAILED! => {"changed": false, "msg": "0513-086 The sendmail Group is not on file.\n"}
ok: [test-osuosl-aix72-ppc64-1] => …
```
=> aixPb: Ignore failure of disable_sendmail task

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/rbac/tasks/main.yml
and make auth as needed before calling loop
=> aixPB: add check for each of the RBAC auth used in the config

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/maven/tasks/main.yml
Update URL for maven 3.6.3
Fixes #3097 
VPC check : https://ci.adoptium.net/job/VagrantPlaybookCheck/OS=CentOS8,label=vagrant/1672/console
=> unixPB: Update maven URL to apache archive

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2019/tasks/main.yml
Instead of checking to see if the adoptopenjdk tags are being used and then running adopt specific tasks, the playbook should run such tasks by default and skip them only if `--skip-tags adoptopenjdk` is used.
=> windowsPb: Add adoptopenjdk tags to MSVS_2019 role

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.sles15
Ref https://github.com/adoptium/infrastructure/issues/3026#issuecomment-1589277527
Solves library error on SLES15
```
19:51:21  =JAVA VERSION OUTPUT BEGIN=
19:51:21  Error: dl failure on line 894
19:51:21  Error: failed /long_path_goes_here/libjvm.so, because libffi.so.6: cannot open shared object file: No such file or directory
```
=> docker: link libffi library and install gawk in SLES15 dockerfile

.ansible-lint, ansible/playbooks/.ansible-lint, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml
Update Ansible Lint rules to use vars type validation on adoptopenjdk_vars.yml rather than playbook schema validation.
Fixes #3104
=> UnixPB : Linter Fixes

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/group_vars/all/adoptopenjdk_variables.yml
ref https://github.com/adoptium/infrastructure/tree/master/ansible#how-do-i-run-the-playbooks-on-a-remote-windows-host
Saves a user (me recently) from having to go that link and copy and paste the variables
=> windowsPb: add timeout variables to variables file

ansible/playbooks/nagios/roles/Nagios_Config/defaults/main.yml, ansible/playbooks/nagios/roles/Nagios_Config/files/Nagios_Server_Config.py, ansible/playbooks/nagios/roles/Nagios_Config/files/templates/jenkins-template.j2
Fixes Issue #3107 
Update the Nagios configuration playbook to use the dedicated template for the Jenkins server, so that the automation can produce a relevant config file.
Playbook has been run successfully through both VM & vagrant Nagios servers.
=> NagiosPB : Add Jenkins host template and configuration to Config Server playbook.

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2019/tasks/main.yml
Missed these changes in the https://github.com/adoptium/infrastructure/pull/3103. Skips these install tasks when it detects that the compiler is already installed
=> windowsPb: skip msvs2019 install tasks when necessary

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Solaris.yml
The playbook creates the symlink `/usr/lib/jvm/jdk-11` [after installing java](https://github.com/adoptium/infrastructure/blob/fc7d6fe556def56471531f94fa880af77b32a04d/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Solaris.yml#L445), but searches `/usr/lib/jvm/bell-jdk-11` to check if the jvm is already installed. Corrected this to `/usr/lib/jvm/jdk-11`
Removed duplicate code
=> unixPB: Solaris remove duplicate jvm check and correct jvm search path 

ansible/inventory.yml
https://github.com/adoptium/infrastructure/issues/2129 and https://github.com/adoptium/infrastructure/issues/1634 suggest these machines have been replaced with the siteox machines. They are not visible in jenkins so I assume they have been removed from there
=> inventory: remove solaris inspira machines from inventory

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/maven/tasks/main.yml
Update URL to download Maven 3.6.3 GPG signature file.
=> UnixPB: Update URL For Maven GPG Signature

ansible/inventory.yml
According to https://github.com/adoptium/infrastructure/issues/2879#issuecomment-1415818400 this machine is fit for removal. Its unreachable via awx. Unpingale and cannot rdp into.
Was/is there a plan to replace this machine?
=> inventory: Remove test-equinix-win2012r2-x64-1

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/7-Zip/tasks/main.yml
ref https://github.com/adoptium/infrastructure/issues/3123#issue-1791954714
build-ibmcloud-win2012r2-x64-2 is experiencing DNS problems which causes an error when downloading 7Zip
```
7-Zip : Download 7-Zip
FAILED! => {"changed": false, "dest": "C:\\temp\\7z.exe", "elapsed": 0.0670207, "msg": "Error when requesting 'Last-Modified'
date from 'https://www.7-zip.org/a/7z2201-x64.exe'. The remote name could not be resolved: 'www.7-zip.org'", "status_code": 
null, "url": "https://www.7-zip.org/a/7z2201-x64.exe"
```
While I fix that, it makes sense to add a task which checks if 7zip is already installed before downloading and installing it
=> windowsPb: Add check for 7zip installation

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Rust/tasks/main.yml
Ref https://github.com/adoptium/infrastructure/issues/3123#issue-1791954714
Rust gets installed into C:\rust\bin\rustc.exe while the task to check if it is already installed looks elsewhere
=> windowsPb: Fix the Rust install location

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/NSClient/tasks/main.yml
ref https://github.com/adoptium/infrastructure/issues/3132
Theres no client for arm64 windows. The role should be skipped until we find a suitable client
=> windowsPb: Skip NSClient install on arm64

ansible/docker/Dockerfile.Ubuntu2204
=> Ubuntu 22.04 build dockerfile missing `gnupg`

ansible/inventory.yml
Following the return of 2 Windows 2012 build machines to service, they have new public IP Addresses that require updating in the inventory.
=> inventory: Update IPs For Restored Azure Win 2012 Machines

ansible/docker/Dockerfile.Alpine3
JDK20 for Alpine/aarch64 won't build becausje the JDK19_BOOT_DIR definition points to a zulu18 which is not suitable as a boot JDK for 20. Once this is in the build process will download a nightly JDK19 for the JDK20 build, and then we'll be able to use that for JDK21.
=> unixPB: Stop forcing JDK19_BOOT_DIR to point at a JDK18

.github/workflows/build_wsl.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml, ansible/vagrant/Vagrantfile.Win2012, ansible/vagrant/Vagrantfile.Windows2022.Core
Fixes #3155 
As per this issue : https://github.com/ansible/ansible/issues/81240
The URL for this script 
https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1
Has changed to
https://raw.githubusercontent.com/ansible/ansible-documentation/devel/examples/scripts/ConfigureRemotingForAnsible.ps1
=> github: Update The URL for the ansible Powershell Script

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/NSClient/tasks/main.yml
Fixes #3132 
Install the Windows 32 bit NSClient on Windows aarch64 hosts. This has been tested on test-azure-win11-aarch64-1 & test-azure-win11-aarch64-2, and both are now monitored by nagios.
=> winPB: Install 32bit NSClient On ARM64 Windows Machines

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/scripts/updatepackages.sh, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/tasks/main.yml
ref https://github.com/adoptium/infrastructure/issues/2962
Ive added a job in AWX to run the updatepackage.sh script regularly (will initiate it when this gets merged). This is better than it being in a cron job since AWX will pull updates to the script. It will run tasks in the `dockerhost.yml` playbook tagged with `updateContainers` which only corresponds to the task I have added in this pr. The `never` tag ensures that the task will only run when specified (by use of the `updateContainers` tag) and not as part of the entire playbook. 
This is still a draft because though this script updates the containers, it does not install new packages if needed, so I need to think of a clean way to do that. 
My last resort is to add strings in the `updatepackages.sh` script which contain any new …
=> unixPb: run the updatepackage.sh script via dockerhost playbook

ansible/inventory.yml
Updates to record the specs of the macstadium machines pending a review of what we're using at this provider. 
Noting that the larger `test-macstadium-macos1014-x64-4` was listed as a `build-` prefixed machine in the macstadium UI but I've now renamed it, although it does not seem to have been contactable for a while.
=> inventory: Add specs for macstadium systems for reference

ansible/inventory.yml
```
root@dockerhost-skytap-ubuntu2004-ppc64le-1:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
```
Incorrectly named 2204 when its OS is 2004
=> inventory: Correct the OS for dockerhost skytap machine

FAQ.md
ref https://github.com/adoptium/infrastructure/issues/2962
Update to the dockerstatic docs now that https://github.com/adoptium/infrastructure/pull/3152 is merged
=> Doc: Update docker static patching policy

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Debian.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Debian.yml
Fixes #3173 
Update URLs for GPG and repository to adoptium.
=> UnixPB: Update Debian URLs

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/rngd/tasks/fedora.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/rngd/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/rngd/tasks/sles.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/rngd/tasks/ubuntu.yml
Cryptography tests are failing as not enough random information is being generated on older distributions, causing tests to timeout.
So installing and enabling rng-tools and its services fix the issues. 
- https://github.com/adoptium/aqa-tests/pull/4474
- https://github.com/eclipse-openj9/openj9/issues/16720
=> unixPB: Install rng-tools to fix low entropy

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/SLES.yml
Fixes #3191.
Package name updated to `libcurl-devel` from `curl-devel`.
=> unixPB: Fix sles 12 build tools package name

.github/workflows/build_vagrant.yml, ansible/vagrant/Vagrantfile.Solaris10
The github solaris playbook test is failing due to a number of issues, resolved in this PR...
Firstly the version of vagrant on the MacOS12 runner, requires the installation of the vagrant virtual box extensions.
Secondly due to upgrades in the default installation of Ansible, a later version of python is required, so the vagrantfile for Solaris 10 has been updated to install Python 2.7
In addition, the rsa cipher needed to be added to the ansible playbook line.
Fixes #3204
=> github: Fix Github action failing solaris 10 playbook check.

ansible/inventory.yml
Add Windows 2022 Server Test Machine, due to replace test-azure-win2012r2-x64-1
Fixes #3163 
Added to Jenkins: https://ci.adoptium.net/computer/test-azure-win2022-x64-1/
Added to Nagios: https://nagios.adoptopenjdk.net/nagios/cgi-bin/extinfo.cgi?type=1&host=test-azure-win2022-x64-1
Added To Wazuh: [Agent 014](https://20.26.114.19/app/wazuh#/agents?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1y,to:now))&_a=(columns:!(_source),filters:!(('$state':(isImplicit:!t,store:appState),meta:(alias:!n,disabled:!f,index:'wazuh-alerts-*',key:manager.name,negate:!f,params:(query:infra-wazuh-server),removable:!f,type:phrase),query:(match:(manager.name:(query:infra-wazuh-server,type:phrase)))),('$state':(isImplicit:!t,store:appState),meta:(alias:!n,disabled:!f,index:'wazuh-alerts-*',k …
=> inventory: Add Windows 2022 Server Test Machine

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Debian.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Fedora.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/capstone/tasks/main.yml
This is the machine setup part of [#hsdis](https://github.com/adoptium/adoptium/issues/213)
=> unixPB: Install capstone 4 from repositories or source

FAQ.md, ansible/pbTestScripts/testJDK.sh, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Debian.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Solaris.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Alpine.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Debian.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Fedora.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/SLES.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/openSUSE.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.alp311, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.alp312, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.alp313, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.alp314, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.cent8, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.deb11, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.f33, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.f34, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.f35, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.sles12, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.sles15, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.u1604, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.u1804, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.u2004, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.u2104, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.u2204, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.ubi8
Fixes #3059 
Install packages required for running ssl-tests for 3rd party clients ( gnutls / nss / openssl ), also include appropriate documentation update, and an additional test has been added to the VPC tests.
=> UnixPB: Include Pre-Req Packages For SSL Test

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.cent8
Fixes #3224
Remove problematic SSL test related packages from distributions that are encountering issues on ARM / PPC64LE on RHEL, CentOS & UBI 8.
=> UnixPB: Only install ssl test packages on x64 for Centos/RHEL

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/performance_tools/tasks/main.yml
Fixes: https://github.com/adoptium/infrastructure/issues/3181
Adds an optional role for installing gdb, perf, nmon and valgrind on Ubuntu, CentOS, Rhel & SLES machines.
=> unixPB: Add an optional role for performance tools

.github/ISSUE_TEMPLATE/machineaccess.md
Add reference to assist users to know that they should not close the issue when access is required as per [the described process](https://github.com/adoptium/infrastructure/blob/master/FAQ.md#temporary-access-to-a-machine).
=> github: Clarify machine access removal process

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2022/tasks/main.yml
The checksum for the downloaded version of windows VS2022 requires an update, due to a change to the remote installation bootstrapper file. This is currently causing the github actions to fail.
=> WindowsPB: Update checksum for downloaded vs2022

.github/workflows/build_qemu.yml, FAQ.md, Jenkinsfile, ansible/docker/Dockerfile.Ubuntu2004-riscv64, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml
It will be used for cross-compilation and testing.
=> [ansible] Add Ubuntu 20.04 linux-riscv64 image

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Thunderbird/tasks/main.yml
Fixes #3239 
Remove installation of firefox from the windows playbook due to security concerns, and restrict installation of Thunderbird to JCK machines. In addition bump the version of thunderbird to the current version ( 115.4 ), which currently has no known security issues.
=> WindowsPB: Prevent Installation Of Firefox & Bump Installation version of Thunderbird

FAQ.md
ref https://github.com/adoptium/infrastructure/issues/3220
=> Docs: Add information on regular deployment of playbooks via AWX

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2022/tasks/main.yml
Ref https://github.com/adoptium/infrastructure/issues/3246#issue-1985631066
The `vs2022_layout_ready` variable does not get registered when the `Transfer VS2022 Layout File` task is skipped (due to msvs2022 already being installed). Then when ansible tries to evaluate `when: (vs2022_layout_ready.stat.exists)` in the `Get SHA256 checksum of the file` task it hits an error:
```
TASK [MSVS_2022 : Get SHA256 checksum of the file]
fatal: [build-azure-win2012r2-x64-4]: FAILED! => {"msg": "The conditional check '(vs2022_layout_ready.stat.exists ) and (windows_version.stdout_lines[0] | regex_search('^(10\\.|11\\.|2016|2019|2022)'))' failed. The error was: error while evaluating conditional ((vs2022_layout_ready.stat.exists ) and (windows_version.stdout_lines[0] | …
```
=> windowsPb: Move msvs2022 install into own block

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/MacOSX.yml
Now that https://github.com/adoptium/temurin-build/issues/3509 is solved and https://github.com/adoptium/temurin-build/pull/3523 was merged we can remove the task which uninstalls libpng from our mac machines as the build will now know to not pick up libpng
=> unixPb: Remove task to uninstall libpng

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Xcode11/tasks/main.yml
ref https://github.com/adoptium/infrastructure/issues/2536
Xcode11.7 is required on m1 mac machines in order to cross compile x64 jdk8
Our usual method of installing xcode using `xcversion` is no longer supported https://github.com/xcpretty/xcode-install/blob/master/MIGRATION.md and is causing errors when I use it to install xcode11.7, see https://github.com/adoptium/infrastructure/issues/2536#issuecomment-1733623397
[xcodes](https://github.com/xcpretty/xcode-install/blob/master/MIGRATION.md) is another tool used to install different versions of xcode but I think it is dependent on Xcode13 which I believe requires macOS 11.3+ (our M1 machines are 11.0)
=> unixpb: Add Xcode11 installation tasks to Unix playbook

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2022/tasks/main.yml
Update checksum for VS2022 installer download
Fixes #3255
=> WindowsPB: Update checksum for vs2022 download

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Xcode11/tasks/main.yml
Fixes #3258 
As per this linter bug when: not xcode11_installed.stat.exists and apple_variables is defined
Certain tasks when cascaded several levels lose context, and cannot be linted successfully. Seperating out the problem tasks ( in this case the get_url task ) from the block, and then leaving all non problematic tasks in the block, allows the linter to behave correctly.
=> UnixPB: Fix Linter For Xcode 11 task

ansible/ansible.cfg, ansible/pbTestScripts/vagrantPlaybookCheck.sh, ansible/pbTestScripts/vmDestroy.sh, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2017/tasks/main.yml, ansible/vagrant/Vagrantfile.Win2022
Fixes #3193 
Implements a VPC option for Windows Server 2022, this requires a new Vagrant Box to match the standard VPC vagrant file naming ( Vagrantfile.win2022 ) and in particular an improvement to the MSVS_2017 installation from download role to mirror the installs of MSVS_2019 & MSVS_2019, in using Powershell to handle the installation rather than the command shell.
=> Vagrant: Add Windows Server 2022 option to VPC

ansible/vagrant/Vagrantfile.Win2012, ansible/vagrant/Vagrantfile.Win2022
The windows boxes available for the Vagrant Playbook check often fail to boot due to vagrants default timeout.
This PR increases the default.
=> Vagrant: Increase boot timeout for windows machines

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml
Fixes #3268 
Prevent installation of docker.io, as docker-ce has already been installed. Update docker.io installation to install the current version, rather than latest.
=> UnixPB: Fix Docker Installation On Debian. 

.github/workflows/build.yml
Fixes #3211 
Amend the value of the docker push tag in the action to a boolean rather than a reference. Similar to the alpine image push which does work.
=> github: Fix Centos6 build image push

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/dnf/tasks/main.yml
ref https://github.com/adoptium/infrastructure/issues/3142#issuecomment-1662156865
=> aixPb: Add steps to install dnf and deprecate yum for AIX 7.2 and higher

ansible/playbooks/AdoptOpenJDK_ITW_Playbook/roles/Common/scripts/install-xcode.sh
Fixes #3281 
HTTPS download is not available for the 2 files from Apple.
SHA256 checksum tests added, and scope of script restricted to MacOS10.
This script is not run automatically as part of the playbook.
=> ITWPlaybook: Improve Xcode Installation in ITW playbook.

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml
Fixes: https://github.com/adoptium/infrastructure/issues/3276
Add Common role support for CentOS 9 Stream
=> unixPB: Fix errors in Common role to support Centos 9 Stream

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml
Fixes https://github.com/adoptium/infrastructure/issues/3289
DevKit creation needs:
- "patch" as DevKit patches certain downloads
- "texinfo" as DevKit build of binutils needs this to build
=> unixPb: Update Centos7 image with patch & texinfo to enabled building of devkit

docs/Testing.md
ref https://github.com/adoptium/infrastructure/issues/2502#issuecomment-1766226058
=> docs: Document the testing done in the infra repo

Jenkinsfile
Same as https://github.com/adoptium/infrastructure/pull/2756/files but now that https://github.com/adoptium/infrastructure/issues/2753 is solved there should be no issue in having the centos6 build in the jenkins job
=> jenkins: Reintroduce centos6 to centos7_docker_image_updater jenkins job

.github/workflows/build.yml
Fixes #3211 
Update docker credentials to use PAT, but disable push on merge, due to replacement with docker multiarch jenkins job. Code left to enable easy re-enablement if required.
The docker push on merge has also been disabled, due to the relocation of the centos6 docker push to the jenkins job as per this PR: https://github.com/adoptium/infrastructure/pull/3296
=> Github: Update Docker Login Credentials To Use Token

.github/workflows/build.yml
Bump Github login action to v3 to support docker login with PAT.
=> GitHub: Bump Dockerhub login action

.github/workflows/build.yml, FAQ.md
Fixes #3298 
Disable the Github Action to push a Centos 6 docker image on merge to Github. This is already disabled for Alpine 3.
This functionality has been relocated to the Jenkins multiplatform docker build job.
However for future reference , the code has been left in place to make re-enablement quicker/simpler should it be required, and it will also test the docker hub credentials being used.
=> Github: Disable push on merge & update document.

FAQ.md
=> docs: Correction to Tims git handle

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/scripts/updatepackages.sh
ref https://github.com/adoptium/infrastructure/issues/2662#issuecomment-1864391143
Fontconfig allows certain jdk_beans and jdk_imageio tests to pass
=> unixPb: Add fontconfig to common packages to be installed/updated on static docker containers

ansible/docker/Dockerfile.Ubuntu2004-riscv64, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml
We don't want to rely on openjdk-17-jdk from Ubuntu 20.04 repositories, it crashes when running on VF2.
Relates to https://github.com/adoptium/temurin-build/issues/3591
=> Download cross-build jdk17u and jdk21u from CI

ansible/inventory.yml
Ref https://github.com/adoptium/infrastructure/issues/3238#issuecomment-1853516549
test-azure-win2012r2-x64-1 and -3 have been replaced with test-azure-win2022-x64-1 and -2
Will remove their jenkins entries once this gets merged
=> inventory: remove test-azure-win2012r2-x64-1 and -3

ansible/inventory.yml
Add the new windows test server ( issue #3238 ) and Wazuh server ( #3047 ) to the ansible inventory.
=> inventory: Add windows test server & wazuh SIEM server

.github/workflows/build_qemu.yml
ref https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
=> github: Replace action checkout version with SHA in build_qemu

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/yum/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_ITW_Playbook/roles/Common/tasks/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Debian.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/SLES.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/OpenSSL/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/freemarker/tasks/main.yml
Fix issues identified in ToB #4
Fixes #3324
=> UnixPB: Fix insecure downloads discovered from TrailOfBits Audit

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.ubi8, docs/Setup-QEMU-Images.md
Fixes #3342 
Issues Identified in TOB-9 security audit.
Debian 11 installation, and dockerstatic file changes tested ok.
=> Security: Update QEMU Instructions & Secure UBI8 downloads in dockerfile

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/SLES.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/SLES.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/rhel.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NVidia_Cuda_Toolkit/tasks/main.yml
Fixes #3341 & #3147 
Ref: Security Audit Issue TOB-5 issues identified with insecure downloads in SLES & RHEL
=> UnixPB: Fix Insecure Downloads In RHEL/SLES playbooks.

ansible/inventory.yml
=> inventory: remove deleted mac minis from inventory

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/dockerhost.yml
=> unixPB: Install jdk21 instead of 11 from dockerhost.yml

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/sles.yml
Extends docker support to SLES 12.
Fixes: https://github.com/adoptium/infrastructure/issues/3326
All the relevant packages mentioned in the PB are available as part of `Containers Module 12` repo. eg: https://scc.suse.com/packages/25502818
note: docker not supported in sles 12 aarch64
=> unixPB: Add Docker support for SLES 12

.github/workflows/check_dockerstatic.yml
Fixes #3386 
Remove out of support Ubuntu version from GHA
=> github: Remove Ubuntu 21.04

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.sles15
The `hostname` command is needed a jdk_net test:
https://ci.adoptium.net/job/Grinder/8802/testReport/sun_net_www_protocol_https_HttpsURLConnection_PostThruProxyWithAuth/java/PostThruProxyWithAuth/
```
Server started at: [SSL: ServerSocket[addr=60d5d0846858/172.17.0.18,localport=40167]]
Proxy server created: ServerSocket[addr=60d5d0846858/172.17.0.18,localport=38103]
Proxy server listening at: ServerSocket[addr=60d5d0846858/172.17.0.18,localport=38103]
Command line: [hostname]
executeProcess() failed: java.io.IOException: Cannot run program "hostname": error=2, No such file or directory
Client side failed: Get hostname failed.
```
=> unixPb: Install `hostname` in sles 15 dockerfile

ansible/inventory.yml
=> inventory: remove more macstadium VMs

ansible/inventory.yml
ref https://github.com/adoptium/infrastructure/issues/2991
=> inventory: Add dockerhost-osuosl-ubuntu2204-aarch64-1 to inventory.yml

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/dockernode.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.alp319, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.deb12, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.f39, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.u2310, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/deploy_container/tasks/deploy.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/deploy_container/tasks/main.yml
ref https://github.com/adoptium/infrastructure/issues/3370
New playbook added `dockernode.yml `which will deploy any number of specified containers onto a chosen dockerhost machine. Example usage: (will add to docs)
```
ansible-playbook AdoptOpenJDK_Unix_Playbook/dockernode.yml -t deploy -e "docker_images=u2204,alp314,deb11"
```
The `deploy` tag must be specified if the user wants to deploy a container. The `docker_images` variable will contain a list of chosen OSs for which we have dockerfiles (error is handled when dockerfile does not exist).
I am testing this at the moment in awx. Once successful we can remove the container build and deploy functionality in https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/tasks/main.y …
=> docker: New dockernode.yml playbook to automate deployment of docker static containers

ansible/docker/Dockerfile.Ubuntu2204
This line should only ever have been in the ubuntu 16.04 one as it's the image we use for arm32. Anyone building a later image should have it able to work on aarch64.
=> Unbreak aarch64 dockerbuild under Ubuntu 22.04

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.sles12, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.sles15
Use JDK17 for the java agent. Use the x64 binary in the dockerfile. The dockernode playbook will change the architecture if needed
=> docker: Use JDK17 for SLES dockerfiles

.github/workflows/build_mac.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/MacOSX.yml
ref https://github.com/adoptium/infrastructure/issues/3203
=> github: Build on MacOS13 image in github workflow

collections/requirements.yml
Some of our roles (`curl` and `GIT_Source`) are trying to use things from ansible galaxy - `homebrew` and `zypper` specifically - which are not available by default, so they fail from AWX when you try to sync the project.
This configuration file, based on the information in https://docs.ansible.com/ansible-tower/3.8.4/html/userguide/projects.html#ansible-galaxy-support, allows us to use the common modules from Ansible Galaxy. Note that this requires `Enable Collection(s) Download` to be set on in the Settings -> Jobs Settings section of the UI (Only available to 
`admin`)
Related to https://github.com/adoptium/infrastructure/issues/3339#issuecomment-1959711161
Testing at https://awx.adoptium.net/#/jobs/playbook/122/output - since it's got past the initial failure at the start (see below) …
=> awx: add requirements.yml for galaxy roles

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NTP_TIME/tasks/main.yml
Fixes #3411 
VPC Completed OK : https://ci.adoptium.net/job/VagrantPlaybookCheck/1833/
CentOS 7 playbook restarts the service now.
=> UnixPB: Update NTPD task to restart ntpd service on CentOS correctly

.github/workflows/labeler.yml
Now that GH token defaults is read only we need to add explicit definitions of permissions required.
=> github: Fix labeler GitHub Action

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Clean_Up/tasks/main.yml
This syntax is invalid and does not work with the new AWX server
Fixes https://github.com/adoptium/infrastructure/issues/3425
While there may be a better solution here, this will allow the deployments to continue to succeed ... I've tested this in a separate AWX template
=> unixPB: Clean_Up role: remove warn: no

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml
We don't want to rely on openjdk-11-jdk from Ubuntu 20.04 repositories, it's based on Zero VM and just too slow for use as boot/build JDK.
=> [ansible] Download cross-build jdk11u from CI

ansible/docker/Dockerfile.Ubuntu2004-riscv64
=> [ansible] Update JDK11_BOOT_DIR to use /usr/lib/jvm/jdk-11

.github/workflows/semgrep_diff.yml, .semgrepignore, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/CentOS.yml
Add a Github Action to run a Semgrep scan using the trail of bits ruleset ( identical to those used in the security audit)  against the files changes as part of a PR.
Details About Semgrep: https://github.com/semgrep/semgrep/blob/develop/README.md
Details About ToB Scanning Rules : https://github.com/trailofbits/semgrep-rules/blob/main/README.md
=> Github: Add Semgrep Check On Pull Request

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2022/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/WiX/tasks/main.yml
Fixes #3439 
The Wix toolset installer has been moved to a different URL, this updates the windows playbook appropriately.
VPC Run: https://ci.adoptium.net/job/VagrantPlaybookCheck/OS=Win2022,label=vagrant/1834/console
- [] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
=> winPB: Update Wix Installer Download URL & Checksum

.github/workflows/semgrep_diff.yml
The new semgrep action was incorrectly only analysing the last commit on a branch.
This PR amends semgrep to run in CI/diff aware mode, and thus make the checks run across all commits for a PR.
=> github: Fix Semgrep GitHub Action To Be Diff Aware

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NTP_TIME/tasks/main.yml
Fixes #3454 
VPC Completed OK: https://ci.adoptium.net/job/VagrantPlaybookCheck/1842/
=> UnixPB: Include check for ntpd service.

ansible/inventory.yml
Ref: https://github.com/adoptium/infrastructure/issues/3339
It's possible we'll switch over to an aarch64 host for this since that should now work, but for now this is the live server and where the DNS entry points to.
=> inventory: add Azure x64 awx.adoptium.net

.github/workflows/build_vagrant.yml
Fixes #3459 
Migrates the failing Solaris 10 build action from Macos 12 to Ubuntu Latest & removes the insecure flag from the ssh connection to the vagrant box..
`-o StrictHostKeyChecking=no`
=> github: Migrate Solaris Check To Ubuntu

README.md
=> doc: add note on backing up jenkins war file on upgrades

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
Fix to PR from earlier today - there is no Temurin 20 on Linux/arm32 so this download fails.
Quick approvals appreciated on this one (hence to review request spam for this one!) as it's blocking build image regeneration just now.
=> unixPB: do not install arm32 Temurin 20 (It does not exist)

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Debian.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Fedora.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/SLES.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml
Resolves https://github.com/adoptium/infrastructure/issues/3453
=> unixPB,winPB: install jq on Linux+Windows for SBoM parsing

.github/workflows/build_mac.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Xcode11/tasks/main.yml
This mean that the playbooks get tested on an M1 macOS host but this should also fix the failing GH action
=> bump latest mac run to macos-14

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.sles12
Fixes #3480 
Install hostname on sles12 dockerstatic containers.
=> Dockerstatic: Ensure Hostname Installed On Sles12

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/disable_gui/tasks/main.yml
Fixes #3478 
The task to disable the GUI, also kills the NTPD service on CentOS7. This has been observed in the weekly playbook runs to refresh the Unix servers.
This has been debugged and investigated to relate to this command 
`systemctl isolate multi-user.target`
VPC Completed OK: https://ci.adoptium.net/job/VagrantPlaybookCheck/1860/
=> UnixPB: Restart NTPD after disabling of GUI

ansible/inventory.yml
New dockerhost machine on azure as per https://github.com/adoptium/infrastructure/issues/3470
=> inventory: add dockerhost-azure-ubuntu2204-x64-2 to inventory file

ansible/inventory.yml
As per the equinix migration, these 2 dockerhost machines are offline and will be decommissioned soon. They have been replaced with azure machines
=> inventory: Remove equinix x64 dockerhost machines from inventory file

FAQ.md, ansible/docker/Dockerfile.RHEL7, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
Part of https://github.com/adoptium/temurin-build/issues/3700
This updates the s390x Dockerfile to remove the hack that was required while we were using docker-ce as the docker provider. The default `docker` package on RHEL7 means that the RHEL subscription from the host machine is automatically made available to containers running on the host, so that is simplified. NOTE: Only `build-marist-rhel79-s390x-2` has these changes during this prototype phase - `-1` still has `docker-ce` so will be incompatible with this change and the dockerfile will no longer run.
The playbook changes prevent attempts to install adoptium JDK8 or JDK20 as they do not exist on s390x.
The primary reason for these changes is to attempt to incorporate the devkits into the build. Since the RHEL7 ones cannot be …
=> Changes to support RHEL7/s390x image creation and devkit inclusion

collections/requirements.yml
AWX is unable to resolve some of the windows modules, installing the `community.windows` modules should solve this
```
ERROR! couldn't resolve module/action 'win_lineinfile'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/runner/project/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/logs/tasks/main.yml': line 37, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be
- name: Update Log File
^ here
```
=> AWX: Add windows collection packages to AWX collections.yml

ansible/inventory.yml, ansible/playbooks/nagios/roles/Nagios_Config/files/Nagios_Server_Config.py, ansible/plugins/inventory/adoptopenjdk_yaml.py
We haven't looked at FreeBSD as a supported platform for years, and the machine does not appear to be contactable, therefore removing.
=> inventory: remove spearhead

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/deploy_container/tasks/deploy.yml
fixes https://github.com/adoptium/infrastructure/issues/3505
=> docker: Assign port number to static docker container during automated deployment

ansible/inventory.yml
Remove the now decomissioned windows2012 machines, which will ber replaced as per: https://github.com/adoptium/infrastructure/issues/3238
=> Inventory: Remove IBMCloud Win2012 Machines

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/README.md
ref https://github.com/adoptium/infrastructure/issues/3415
Like the inventory.yml file, I recommend updating the DockerInventory.json via manual prs using [the script](https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/scripts/updateDockerStaticInventory.py) (until I find a way to automate the automation 😄  )
=> docs: Update static docker docs to include inventory update script usage

ansible/inventory.yml
=> Inventory: Replace Marist s390x build host.

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/WiX/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/shortNames/tasks/main.yml
Noting that we'll need to manually cleanup the old wix v3.14 installation on all machines
=> winPB: upgrade wix toolset to v5.0.0

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/jckservices_iptables/tasks/main.yml
Update JCKServices with IP of new TCK Solaris host.
=> UnixPB: Add new TCK solaris host

ansible/inventory.yml
Following the reboot of the non-responsive windows 2016 test azure machine, its IP address was changed, as it is not assigned a static public IP address.
The machine is now back in service, but it has a new IP address.
=> inventory: Update win2016 machine ip address

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/scripts/updateDockerStaticInventory.py
The script should use https not http. Tested and it works.
=> docker: Update inventory updater script to use https

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml
Few tasks(Jenkins/Nagios user to Docker group, Enable & Disable Docker service) in Docker role are limited to only a few OS versions. This PR extends it's support to the latest OS versions.
=> UnixPB: Extend support of few docker related tasks to lastest OS versions

ansible/DockerInventory.json
Just a typo fix. The name has been fixed in jenkins too
=> inventory: Fix typo with static docker machine

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2022/tasks/main.yml
There is a need to correct the checksum value for vs_Community.exe file.
failed job: https://github.com/adoptium/infrastructure/actions/runs/9393130716/job/25868653756?pr=3582
```
C:\Users\Administrator\Downloads>certutil -hashfile vs_Community.exe SHA256
SHA256 hash of file vs_Community.exe:
8653debb099fe571c681c7f06334e703ea801168590787a727faef61e0cffc42
CertUtil: -hashfile command completed successfully.
```
important links: https://github.com/adoptium/infrastructure/pull/3582
=> WinPb: Correct the checksum for vs_Community.exe

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/NVidia_Cuda_Toolkit/tasks/main.yml
The silent installation for NVIDIA toolkit is not successful. the playbook run gets executed successfully but the NVIDIA GPU Computing Toolkit folder is not getting created and therefore the CUDA_HOME variable is not getting set causing build compiles to throw error saying CUDA_HOME not found.
The NVidia official documentation mentions nvcc_9.1 as the compiler to be used. After the change the NVIDIA GPU Computing Toolkit folder is getting created successfully.
https://docs.nvidia.com/cuda/archive/9.1/cuda-installation-guide-microsoft-windows/index.html
` C:\temp\cuda_9.1.85_win10_network.exe -s nvcc_9.1 nvml_dev_9.1`
I have only done testing on windows 10,11, 2016,2019 and 2022. I am not sure how it is for Windows 7,8 and Server 2008,2012
Reference ticket: …
=> WinPb: Change compiler parameter for NVidia cuda toolkit silent installation

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/NVidia_Cuda_Toolkit/tasks/main.yml
Update the cuda path (C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0) to v9.1 in the check to see  if NVidia CUDA toolkit is already installed
Need to update the CUDA_VERSION=9.0 in build-farm/platform-specific-configurations/windows.sh in temurin-build repo after change is merged.
=> WinPb: Update cuda path to v9.1

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/openSUSE.yml
Ref: TOB5
The fixes in this PR address a few security vulnerabilities in the OpenSuse common tasks. This playbook does not run, due to issues with the repositories being no longer available, and requiring rework: planned in #3365
=> UnixPB: Update OpenSuse Common Tasks For Security

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.ubi9
ref https://github.com/adoptium/infrastructure/issues/3586
=> docker: Add ubi9 docker static dockerfile

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.ubi8
ref https://github.com/adoptium/infrastructure/issues/3586 The UBI8 static docker dockerfile has been updated to use the vault centos stream repos
=> Ubi8.dockerstatic.dockerfile

.github/workflows/build_mac.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/MacOSX.yml
Ensure JQ is installed on Mac Hosts for Reproducible build tests.
See: #3593
=> UnixPB: Install JQ for mac repro tests.

.github/workflows/build_vagrant.yml
=> GHA: Update Solaris 10 Vagrant Check To Use Compatible Versions Of Ansible/Python

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/dockernode.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/README.md, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/deploy_container/tasks/deploy.yml
Ref https://github.com/adoptium/infrastructure/issues/3579
Adds ability to build arm32 containers using docker buildx. Updates docs accordingly
=> docker: Add docker buildx functionality to dockernode playbook for arm32 containers

ansible/inventory.yml
2 new machines added as per https://github.com/adoptium/infrastructure/issues/3501
=> inventory: Add ubuntu 2404 machines to inventory

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/jckservices_iptables/tasks/main.yml
=> unixPB: Add new Scaleway TC machine to iptables config

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/yum/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/ccache/tasks/main.yml
Using `warn: False`/`warn=False` is deprecated, which is causing linter errors
`FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.legacy.command) module: warn. Supported parameters include: _raw_params, _uses_shell, argv, chdir, creates, executable, removes, stdin, stdin_add_newline, strip_empty_ends."}`
```
inline-env-var: Command module does not accept setting environment variables inline.
ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/yum/tasks/main.yml:70 Task/Handler: Unpack yum bundle
inline-env-var: Command module does not accept setting environment variables inline.
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/ccache/tasks/main.yml:17 Task/Handler: Download ccache.tar.gz
```
For the aix yum task, the yum role is deprecated. We install dnf on 7.2+ …
=> github: Fix latest linter errors

.github/workflows/packer.yml
Adds support for auto regenerating the Orka macOS images on PR merge. For now while we don't have an accurate way of installing xcode this will only update the top layer
=> packer: add workflow to automatically update orka images

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2022/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/WiX/tasks/main.yml
Update the Wix5 installation task, as the .NET SDK is not installed by default, and the wix installation requires it.
This also addresses a bug, where the playbook incorrectly uses sudo as a become method, which should be runas in Windows.
Fixes #3617
=> WinPB: Update Wix Installation To Install SDK

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/deploy_container/tasks/deploy.yml
The `--platform` option is required in the `docker run` command (along side its use in the `docker build` command) to prevent such warnings 
```
WARNING: The requested image's platform (linux/s390x) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```
Fixes https://github.com/adoptium/infrastructure/issues/3633
=> docker: Add --platform option to docker run command

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/jckservices_iptables/tasks/main.yml
Updates for new 24.04 systems for temurin-compliance. Part of  https://github.com/adoptium/infrastructure/issues/3598 - machines added at https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4760
=> unixPB: update jckservices iptables config for new riscv64 machines

ansible/docker/Dockerfile.CentOS7, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/CentOS.yml, ansible/vagrant/Vagrantfile.CentOS7
Fixes #3642 
Update various calls to mirrorlist.centos.org with vault.centos.org, now that mirrorlist has been deprecated following the EOL of Centos 7.
VPC in progress:
https://ci.adoptium.net/job/VagrantPlaybookCheck/1897/OS=CentOS8,label=vagrant/console
https://ci.adoptium.net/job/VagrantPlaybookCheck/1897/OS=CentOS7,label=vagrant/console
=> Docker: Fix Use Of mirrorlist.centos.org in dockerfiles and Unix playbooks.

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_10/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_11/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_7/tasks/main.yml
Fixes https://github.com/adoptium/infrastructure/issues/3634 and also adjusts the adoptopenjdk_install role to install JDK17 and 21 from the normal processes now that those levels are GA on riscv64
FYI @luhenry since you added most of the adoptopenjdk_install workarounds in the past but they shouldn't be required now :-)
Memo to self: Don't squash these commits.
=> Fix gcc and adoptopenjdk_install roles for riscv64

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml
This allows the use if `yumdownloader` to pull down the devkit prereqs as a non-root user (`jenkins` in our case)
Part of https://github.com/adoptium/temurin-build/issues/3749
=> unixPB: add yum-utils to RHEL/s390x for devkit creation

ansible/docker/Dockerfile.CentOS7
Fixes #3646 
Update various calls to mirrorlist.centos.org with vault.centos.org, now that mirrorlist has been deprecated following the EOL of Centos 7.
=> Docker: Fix Use Of mirrorlist.centos.org in dockerfiles for arm64 & ppc64le

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.cent7
Forgot to add this change in https://github.com/adoptium/infrastructure/pull/3402
Curl-devel is required before compiling git 2.15.0 from source to resolve `fatal: Unable to find remote helper for https`
=> docker: Install curl-devel onto centos7 static docker containers

ansible/inventory.yml
In draft while machine setup is completed. We will ultimately replace all of the 23.10 systems with 24.04 ones.
Part of https://github.com/temurin-compliance/temurin-compliance/issues/522
=> inventory: add new rise/scaleway ubuntu 24.04 systems

FAQ.md
Based on things seen in:
- https://github.com/adoptium/temurin-build/issues/3685#issuecomment-2075133310 
- https://github.com/adoptium/infrastructure/issues/3501#issuecomment-2105675393
- https://github.com/adoptium/aqa-tests/issues/5300#issuecomment-2104830025
=> doc: update FAQ to mention aqa-tests branches

.github/workflows/packer.yml, ansible/packer/orka-base.pkr.hcl, ansible/packer/orka.pkr.hcl
We can easily (and quickly) rebuild the base image for intel which means that it will always contain security updates etc. I've enabled this for intel but cannot make the same change for arm64 yet as it the Xcode download is too flaky.
=> packer: auto rebuild base image for intel

ansible/vagrant/Vagrantfile.Debian10
Fixes #3655 
Update the Debian 10 repositories to use the archive repositories, and configure dpkg to not require interactive mode during vagrant provisioning.
VPC OK: https://ci.adoptium.net/job/VagrantPlaybookCheck/OS=Debian10,label=vagrant/1903/
=> Vagrant: Fix Debian 10 Vagrantfile For Deb repositories.

ansible/vagrant/Vagrantfile.Ubuntu2004
Switch box to use bento box, which has larger /boot partition. Also include ppa repository to ensure more recent ansible is installed.
VPC OK: https://ci.adoptium.net/job/VagrantPlaybookCheck/OS=Ubuntu2004,label=vagrant/1905/
=> Vagrant: Fix VPC For Ubuntu 20.04

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Fedora.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.ubi8, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.ubi9
ref https://github.com/adoptium/infrastructure/issues/3614#issuecomment-2211131526 shared-mime-info is needed for java/nio/file/Files/probeContentType/Basic.java to pass
=> ansible: Install shared-mime-info on Centos UBI RHEL and Fedora

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.alp320
ref https://github.com/adoptium/infrastructure/issues/3605
=> docker: Add Alpine 320 Static Dockerfile

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/deploy_container/tasks/deploy.yml
Fixes this error `["ERROR: invalid tag \"aqa_u2404.ARM32\": repository name must be lowercase"]`
=> docker: Docker image tag must be lowercase when building dockerstatic image

ansible/inventory.yml
ref https://github.com/adoptium/infrastructure/issues/3692
OS upgraded to Ubuntu2404. Name changed in jenkins. hw.dockerhost labels updated
=> inventory: dockerhost-equinix-ubuntu2004-armv8-1 upgraded to ubuntu 2404

ansible/inventory.yml
test-marist-ubuntu2004-s390x-1 upgraded to test-marist-ubuntu2404-s390x-1 as of https://github.com/adoptium/infrastructure/issues/3501#issuecomment-2260357969
=> inventory: test-marist-ubuntu2404-s390x-1 added to inventory

FAQ.md, ansible/docker/Dockerfile.win2022, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Common/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/GPG_signature_verification/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2022/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/WMF_5.1/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/logs/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/shortNames/tasks/main.yml
**This PR is in draft to give as many people as possible time to review and voice options and not having this one quickly merged. Approvals are welcome in the meantime**
Notes:
- Adds Dockerfile.win2022 which can be used to create a build image comparable to the Linux ones. This will only install VS2022, not the earlier other compilers (this will be fine for all versions once https://github.com/adoptium/temurin-build/pull/3907 is merged)
- Various modifications to support the above including:
- Adding more 'win_reboot' tags to tasks to avoid attempting to reboot while running ansible inside the container
- Use of gpg2 instead of gpg since that is what the new cygwin seems to have
- Since the dockerfile does a base cygwin install, the ansible cygwin role now checks for jq.exe (the most …
=> winPB: Switch to VS2022 build tools and add Windows build dockerfile

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/bash_login/tasks/main.yml
To escape the rebase hell that is https://github.com/adoptium/infrastructure/pull/2288/, ive simply created a new pr :)
=> aixPb: Put /usr/bin in front of PATH

ansible/inventory.yml
ref https://github.com/adoptium/infrastructure/issues/3585
=> inventory: s390x and ppc64le dockerhosts have been upgraded to ubuntu 2404

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Incredibuild/tasks/main.yml
Fixes:  https://github.com/adoptium/aqa-tests/issues/5474
As seen in the above issue, the jwebserver tests fail due to a conflict with a process on port 8000. After investigation, this turns out to be a clash with the incredibuild dashboard service.
This change, reconfigures the Incredibuild dashboard service to use a different port. ( The incredibuild service uses port 30000, so 31000 seemed appropriate for the dashboard. Also having carried out investigation, I cannot find any other services using this port on Windows.
VPC Completed OK : https://ci.adoptium.net/job/VagrantPlaybookCheck/OS=Win2022,label=vagrant/1959/console
=> WindowsPB: Add Incredibuild Dashboard Configuration Task

.github/workflows/build_mac.yml
Fixes #3739 
Upstream bug, that required the workaround has now been resolved. So removing the workaround.
See: https://github.com/actions/runner-images/issues/9777 for additional required dirmgr configuration
&
See https://github.com/actions/runner-images/issues/8649 for the reverse lookup fix (upstream bug)
=> GHA: MacOS Revert Ubuntu keyserver workaround

ansible/DockerInventory.json, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/scripts/updateDockerStaticInventory.py
Fixes https://github.com/adoptium/infrastructure/issues/3735
The script now groups together static containers by looking for the `hw.dockerhost.$dockerhost` label in their jenkins config, instead of by ip
=> docker: Fix dockerinventory script to group containers by label not ip

.github/workflows/check_dockerstatic.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.centstream9
ref https://github.com/adoptium/infrastructure/issues/2478
Centos stream 9 has support for 2 more years, https://endoflife.date/centos-stream
=> docker: Add Centos Stream 9 dockerfile to static dockerfiles

.github/workflows/build_vagrant.yml
Fixes #3760 
Update the solaris github action to use a valid combination of Ubuntu, Virtualbox & Vagrant, until a version of Vagrant compatible with Virtualbox 7.1 is available.
This PR allows the Solaris check Github action to run normally.
=> GHA: Update Solaris Check Github Action With Valid Tools

ansible/inventory.yml
Part of #3238 
Remove decomissioned Windows 2012 azure machines.
=> Inventory: Remove Win2012 machines

.github/workflows/check_dockerstatic.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/group_vars/all/main.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/ant/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/group_vars/all/adoptopenjdk_variables.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Ant-Contrib/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.al2023, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.alp320, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.deb12, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.f41, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.sles12, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.sles15, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.u2404, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.ubi9, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/ant/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/group_vars/all/adoptopenjdk_variables.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/ANT/tasks/main.yml
ref https://github.com/adoptium/infrastructure/issues/3074
To do:
=> unixPb: Update Ant version to latest 1.10.15

ansible/inventory.yml
This machine is in jenkins https://ci.adoptium.net/computer/test-azure-win2022-x64-3/, but I couldnt find it in the inventory.yml file
=> inventory: Add test-azure-win2022-x64-3 to inventory.yml

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2022_REDIST/tasks/main.yml
Fixes #3772 
Required as part of https://github.com/adoptium/temurin-build/pull/3981/files 
VPC Successful : https://ci.adoptium.net/job/VagrantPlaybookCheck/OS=Win2022,label=vagrant/1982/console
=> WinPB: Add Installation of VS2022 Redists

.github/workflows/build_wsl.yml
Fixes #3157
Added checksum validation for WinRE Ansible file
=> GHA: Added checksum validation

ansible/pbTestScripts/vagrantPlaybookCheck.sh
Fix the Vagrant Playbook Check process for CentOS6
Fixes #3778 
VPC In Progress:  https://ci.adoptium.net/job/VagrantPlaybookCheck/OS=CentOS6,label=vagrant/1990/console
Test Run Here:
:heavy_check_mark: Test Run : https://ci.adoptium.net/job/SFR-VPC-AZURE-POC/OS=CentOS6,label=vagrant/111/console
=> VPC: Fix CentOS6 Playbook Check

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/jckservices_iptables/tasks/main.yml
as per https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5074
I've already run this playbook to allow the new host to reach the jckservices host.
=> update IP for jck-azure-ubuntu2204-x64-1

ONBOARDING.md, README.md, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Get_Vendor_Files/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Get_Vendor_Files/tasks/main.yml
It's now been moved to the Adoptium Org
=> update references to adoptopenjdk/secrets

ansible/inventory.yml
These disappeared as part of https://github.com/adoptium/infrastructure/issues/3292 earlier this year but didn't get removed from the inventory.
=> inventory: remove equinix awx systems

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Alpine.yml
Installing GA JDK17 aarch64 alpine linux as a bootjdk (using the adoptopenjdk_install role) is causing an error since the GA doesnt exist. We install a [nightly version](https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Alpine.yml) in the common role.
Theres an issue [here](https://github.com/adoptium/infrastructure/issues/3804) to discuss merging the bootjdk installs in the common role and the adoptopenjdk_install role, but until then this pr will stop errors such as https://ci.adoptium.net/job/centos7_docker_image_updater/574/execution/node/77/log/ in the build image updater job
```
> [5/5] RUN set -eux;  cd /ansible;  ansible-playbook -i hosts ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml -e …
```
=> unixPB: Dont install GA JDK17 bootjdk on alpine aarch64

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
Mistakenly put the wrong condition in https://github.com/adoptium/infrastructure/pull/3805 causing the JDK17 install to skip x64 alpine
https://ci.adoptium.net/job/centos7_docker_image_updater/576/execution/node/116/log/
```
#9 807.4 TASK [adoptopenjdk_install : Install latest Adopt JDK17 if one not already installed (Linux/Alpine-Linux)] ***
#9 807.4 skipping: [localhost]
#9 807.4 
```
This should skip the JDK17 install only on aarch64 alpine. Its equivalent to `(ansible_distribution != "Alpine" or ansible_architecture != "aarch64")` which is also used in the playbook to prevent JDK11 and JDK8 from installing on alpine aarch64.
The Alpine3 aarch64 build image will still have its JDK17 bootjdk as mentioned here https://github.com/adoptium/infrastructure/pull/3805#issuecomment-2463452475 …
=> unixPb: Correct the condition on JDK17 alpine aarch64 install

ansible/inventory.yml
=> inventory: Remove dockerhost-azure-ubuntu2404-x64-1

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/SLES.yml
Need to change the distribution release version from 15.5 to 15.6 in the common role to add the devel-tools repo.
Can we make a change to make this dynamic?
Instead of using the hardcoded version , cant we make it dynamic?
For example instead  of `15.5` cant we make it `{{ ansible_distribution_major_version }}.{{ ansible_distribution_release }}`
=> change distribution_release to 15.6

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/aixfs/tasks/main.yml
Fixes #3129 
Some tests are requiring extra space in /tmp to prevent it filling to 100% before the test clears down.
+1Gb should be sufficient.
=> AIXPB: Increase Size Of TMP FS to 5GB

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/additional_plugins/check_docker_overlay2_size.sh, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/main.yml
Ref: #3797 
Add a new script to be used by nagios for monitoring the size of the /var/lib/docker/overlay2 folder, and ensure it is installed alongside the other nagios plugins.
VPC OK : https://ci.adoptium.net/job/VagrantPlaybookCheck/2008/
=> UnixPB: Add Docker Overlay Check Plugin Script For Nagios

ansible/pbTestScripts/buildJDK.sh, ansible/pbTestScripts/buildJDKWin.sh
Self-explanatory. The current build checks do run run through the SBoM generation process, so we are not validating that those parts of the process work after any changes. This will also help to verify https://github.com/adoptium/infrastructure/issues/3806 when it is implemented.
=> pbTests: Include SBOM creation in the build tests

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2022_REDIST/tasks/main.yml
As part of moving to the latest VS2022 Redist UCRT DLLs: https://github.com/adoptium/temurin-build/issues/4086
Update Windows image to download: vs2022_redist_14.40.33807_10.0.26100.1742.zip
- https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/2037/
=> Upgrade VS2022 Redist devkit to version vs2022_redist_14.40.33807_10.0.26100.1742

ansible/inventory.yml
ref https://github.com/adoptium/infrastructure/issues/3719
All of the test-rise boxes were given a reinstall to ensure a kernel upgrade to `5.10.113-scw1`. More specifically, test-rise-ubuntu2404-riscv64-1's ip changed because I deleted the old box and made a new one. The ubuntu 2310 boxes were reinstalled to ubuntu2404. Their entries in jenkins have been updated
=> inventory: Update test-rise riscv names and IPs after upgrades

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/jckservices_iptables/tasks/main.yml
Seems this machine was missing. It's been added to the machine already now so this PR just needs to go in to store the configuration
=> unixPB: add skytap-5 to jckservices firewall

.github/workflows/build_wsl.yml
Fixes #3873 
Add wsl version param to wsl setup, to ensure wsl v1 compatible with both windows 2019 & windows 2022.
This should also allow #3854 to be merged.
=> Fix Failing Windows 2022 Github Action

.github/workflows/linter.yml, ansible/pbTestScripts/buildJDK.sh, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/GIT_Source/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NVidia_Cuda_Toolkit/tasks/main.yml
Fixes #3839 
Downloads for Git Source and Nvidia Cuda toolkit are failing on CentOS6 due to the certificate errors, and the lack of support of SNI enabled validation, due to the age of the O/S.
This PR adds an alternative, but still secure download mechanism for CentOS6 only, to allow the playbook to be backwards compatible.
VPC In Progress : https://ci.adoptium.net/job/VagrantPlaybookCheck/2061/
=> UnixPB: Fix Problematic Centos6 Downloads

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/deploy_container/tasks/deploy.yml
Not sure if this option changed recently, or with a docker upgrade, but linux/v7/arm no longer works and linux/arm/v7 works 👍🏻
=> docker: Update mulitarch linux arm platform option

ansible/inventory.yml
As per https://github.com/adoptium/infrastructure/issues/3588 the test-osuosl ppc64le machines have been upgraded to ubuntu24.04. Jenkins configs have been updated
=> inventory: test-osuosl ppc64le machine upgrades to Ubuntu 24.04

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml
Follow-on to https://github.com/adoptium/infrastructure/pull/3293 for other platforms.
Blocker for https://ci.adoptium.net/job/build-scripts/job/utils/job/devkit/job/devkit-gcc-linux-riscv64/ to be able to work within the docker build container (without the container it produces a compiler which will not work on Ubuntu 20.04)
=> unixPB: Update Ubuntu build images (arm32/riscv64) with patch and texinfo for devkit creation

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml
I was a bit too quick with my [last PR](https://github.com/adoptium/infrastructure/pull/3896) and missed a couple of critical packages that are not already there. It's still not working 100% with these changes but it's close -the failure I'm seeing looks like it's related to the devkit code and not the machine setup (There is some hard coding of Centos in our scripts - unfortunately it doesn't show up until the job has been running for 14 hours)
=> unixPB: add rpm2cpio/rpm to for creating devkits on Ubuntu

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/WiX/tasks/main.yml
Updated used wix version to 5.0.2
=> ansible: Updated used wix version to 5.0.2

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml
rel: https://github.com/adoptium/infrastructure/issues/3851
The task installs weston related packages in RedHat/CentOS 10
=> UnixPB: Add Weston support to RHEL/CentOS 10

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
Fixes https://github.com/adoptium/infrastructure/issues/3904
cmake role is there for OpenJ9 and OpenJ9 does not support Alpine, so this is superfluous.
=> unixPB: exclude cmake on solaris and alpine (Not OpenJ9 there)

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/jckservices_iptables/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/ubuntu-jckservices.yml
These VMs were migrated to a new DC which means they have new IP addresses.
=> unixPB: update IP addresses for SkyTap AIX VMs

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/ant_contrib/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/dnf/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/xlc_v13/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/xlc_v16/tasks/main.yml
Updates:
- Move compiler installs after dnf role. If unzip and tar are not installed, ansible cant unarchive the compiler files
- Ant contrib should use the up to date ant_version
- Update the python interpreter used by the dnf module
- Remove `failed_when: false` on the transfer tasks in the compiler roles. If the transfer fails for whatever reason I want the playbook execution to stop
=> aixPb: A few updates to the AIX playbook

ansible/inventory.yml
ref https://github.com/adoptium/infrastructure/issues/3588
Upgraded the OS from 20.04 to 22.04. Its Jenkins config, and hw.dockerhost.dockerhost-skytap-ubuntu2004-ppc64le-1 label on its hosted containers have been updated
=> inventory: Update dockerhost-skytap-ubuntu2004-ppc64le-1 name after OS upgrade

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/jckservices_iptables/tasks/main.yml
Added the new tck machine to the jckservies_iptables role
=> unixPb: Update jckservices role with new jck machine ips

README.md
It's a good idea and saved us a lot of time during the [latest upgrade cycle](https://github.com/adoptium/infrastructure/issues/3925).
=> doc: add backup of plugins into jenkins upgrade doc

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Fedora.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml
Fixes https://github.com/adoptium/infrastructure/issues/3869
Related: https://github.com/adoptium/infrastructure/pull/3802 (The RHEL8-RHEL8Plus change in that PR may mean this needs an update to go it to avoid a conflict).
Note that as per the notes in 3869 CentOS6 will generally already have procps installed so, for simplicity,  I have not explicitly listed it here.
=> unixPB: add diffutils and procps-ng to RH/Cent/Fedora

ansible/pbTestScripts/testJDK.sh, ansible/pbTestScripts/testJDKWin.sh, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml
Fixes #3952 
Fix a bug where the addition of a new folder into the JDK build folder structure is causing the VPC post build tests to fail, as the derivation of the JDK folder was finding 2 entries.
:heavy_check_mark: U24.04 - https://ci.adoptium.net/job/VagrantPlaybookCheck/2095/
:heavy_check_mark: U22.04 - https://ci.adoptium.net/job/VagrantPlaybookCheck/OS=Ubuntu2204,label=vagrant/2098/
:heavy_check_mark: U20.04 - https://ci.adoptium.net/job/VagrantPlaybookCheck/OS=Ubuntu2004,label=vagrant/2096/
:heavy_check_mark: Centos 8: https://ci.adoptium.net/job/VagrantPlaybookCheck/OS=CentOS8,label=vagrant/2096/
:heavy_check_mark: Centos 7: https://ci.adoptium.net/job/VagrantPlaybookCheck/OS=CentOS7,label=vagrant/2098/
:heavy_check_mark: Solaris 10: …
=> Vagrant: Remove jmods folder from Test JDK derivation in VPC tests

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/nasm/tasks/main.yml
Spotted while testing the playbooks on RHEL9.
The changes in https://github.com/adoptium/infrastructure/pull/3732/files abstracted out the `nasm_version` variable as well as updating it to a later version, however some of the conditionals were left with the original hard coded number. This means that different operations within the role were checking for different things. Specifically the download was triggered if it was anything other than the target version, but the extract of the downloaded tarball checked for the older one, so always fails.
I've no idea how this hasn't been spotted as a problem before, but this PR should fixing it ;-)
=> unixPB: fix conditionals for nasm role

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/nasm/tasks/main.yml
Amend Unix Playbooks to run on RHEL10
Part of #3868 
:heavy_check_mark: JDK21 build successfully on RHEL10.
VPC In Progress : https://ci.adoptium.net/job/VagrantPlaybookCheck/2122/
13:31:07 [VagrantPlaybookCheck » Ubuntu1804,vagrant](https://ci.adoptium.net/job/VagrantPlaybookCheck/OS=Ubuntu1804,label=vagrant/) completed with result SUCCESS
13:31:07 [VagrantPlaybookCheck » CentOS8,vagrant](https://ci.adoptium.net/job/VagrantPlaybookCheck/OS=CentOS8,label=vagrant/) completed with result SUCCESS
13:31:07 [VagrantPlaybookCheck » Ubuntu2204,vagrant](https://ci.adoptium.net/job/VagrantPlaybookCheck/OS=Ubuntu2204,label=vagrant/) completed with result SUCCESS
13:31:07 [VagrantPlaybookCheck » Ubuntu2404,vagrant](https://ci.adoptium.net/job/VagrantPlaybookCheck/OS=Ubuntu2404,label=vagrant/) …
=> UNIXPB: Update Playbooks For RHEL10 Support

ansible/inventory.yml
=> inventory: Add 2 new OSUOSL aarch64 dockerhost machines

ansible/packer/orka.pkr.hcl
=> unixPB: orka - always ensure that xcode path is reset to /

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/cmake/tasks/main.yml
Incorrect variable used for cmake's GPG signature check in [the previous PR](https://github.com/adoptium/infrastructure/pull/4019/files) (Not sure why I didn't hit this in my local testing though)
=> unixPB: Fixup cmakeVersion check for GPG signature

.github/workflows/build_wsl.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2013_REDIST/tasks/main.yml
Fixes #4052 
VPC In progress : https://ci.adoptium.net/job/VagrantPlaybookCheck/2154/
=> WindowsPB: Add Pre-requisite VC runtime packages required for tests.

ansible/inventory.yml
Update the IP address for test-azure-windows-x64-2
Remove defunct windows 2016 & 2019 hosts ( machines no longer in azure )
=> Inventory: Update Windows IP Address

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/nasm/tasks/main.yml
Updates to allow CentOS Stream 10 to be provisioned using the playbooks.
Note: Does not currently include the EPEL install (`dnf install -y epel-release` seems to work in CS10 containers, but on a real machine it seems to need it installed by `dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm`
Final step in https://github.com/adoptium/infrastructure/issues/3868 assuming the testing completes as expected
=> unixPB: Updates for Centos Stream 10

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml
Required by OpenJ9 when compiling OpenSSL version 3.5.3+
Related eclipse-openj9/openj9#22631
=> unixPB: Add perl-Time-Piece to common RedHat/CentOS

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/MacOSX.yml
ref https://github.com/adoptium/aqa-tests/issues/6596#issuecomment-3311995980
=> unixPb: Set corefile size on MacOS to unlimited
