adoptium/infrastructure

ansible/playbooks/rhel.yml, ansible/playbooks/ubuntu.yml, ansible/playbooks/windows.yml
Signed-off-by: Adam Brousseau <adam.brousseau@ca.ibm.com>
=> Cleanup Cuda binary from tmp after install

ansible/playbooks/centos_7.yml, ansible/playbooks/rhel.yml, ansible/playbooks/sles_12.yml, ansible/playbooks/ubuntu.yml, ansible/playbooks/windows.yml
Signed-off-by: Adam Brousseau <adam.brousseau@ca.ibm.com>
=> Cleanup cmake from tmp after install

ansible/playbooks/centos_7.yml, ansible/playbooks/rhel.yml, ansible/playbooks/sles.yml
Fixes #33
Signed-off-by: Adam Brousseau <adam.brousseau@ca.ibm.com>
=> Fix missing underscore in with_items

ansible/playbooks/ubuntu.yml
=> arm vs aarch64 list of supported OS/Arch was misleading

.gitignore, Vagrantfile, ansible/README.md
Initial commit some documentation for newbies to ansible and added a Vagrant file to run ansible playbooks in an isolate environment
=> A bit of documentation for ansible playbooks

ansible/playbooks/rhel.yml
* remove from tags:ant actions
=> Install ant-contrib package via yum for rhel7 ppcle

ansible/playbooks/ubuntu.yml
Reverts AdoptOpenJDK/openjdk-infrastructure#52
=> Revert "Add openjdk9 to ubuntu.yml"

ansible/playbooks/ubuntu.yml
Added support for Raspbian 8 on armv7l  on Raspberry Pi 2
=> Added support for Raspbian 8 on armv7l

ansible/playbooks/rhel.yml
=> Add numa package installation for openj9 requirement

ansible/playbooks/rhel.yml
This is a follow up on #30 which was closed without resolution.
=> Add XML::Parser to rhel ansible scripts

ansible/playbooks/ubuntu.yml
=> Add XML::Parser and package dependencies for ubuntu

ansible/playbooks/ubuntu.yml
was: tags:xml_parser
now: tags: xml_parser
=> Space error on line 227

ansible/playbooks/windows.yml
- install java 7 jdk instead of jre
- add java 8 bin directory to path
- add check for freemarker and freetype
- install freetype, freemarker into c:/openjdk directory
- grant jenkins user permissions on freetype
=> Install windows resources

ansible/playbooks/adoptopenjdk_variables.yml, ansible/playbooks/conf/krb5.conf, ansible/playbooks/ubuntu-jck.yml
Installs Tomcat HTTP server, FTP server with a suitable user, and a krb5 Kerberos server with a random password on the assumption we won't need it in the future... The two users are given "known" passwords which I don't think should be an issue ...
=> Add playbook for setting up Ubuntu to run the JCK suite

ansible/playbooks/windows.yml
added ignore_errors: yes to Cleanup cmake
=> cmake - ignore_errors: yes

ansible/playbooks/ubuntu.yml
* add gcc-4.8, g++-4.8
* add curl, numa, freetype
=> Add openj9 package requirements for ubuntu based systems

ansible/playbooks/rhel.yml
=> Enable the install of git 2.15 on all platforms

ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Jenkins_User/tasks/main.yml
Disabled adding jenkins user to audio group for armv7l
=> Disabled adding jenkins user to audio group armv7l

ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Common/tasks/Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Common/vars/Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Swap_File/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Vendor/tasks/main.yml
- Add additional repositories for BeagleBone
- Created new section for the installation of GCC and G++ 4.8
- Update Swap_File task to allow the swapfile to be on another mount point for BeagleBone
- Harden Vendor task, so that it will no longer fail when the Vendor file/folder doesn't exist
=> Updates to support BeagleBone

ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Common/vars/Ubuntu.yml
=> Add https support for git on linux arm

ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Common/vars/Ubuntu.yml
Reverts AdoptOpenJDK/openjdk-infrastructure#108
=> Revert "Add https support for git on linux arm"

ansible/playbooks/ubuntu-jckservices.yml
After merging, this will need to be run again on jckservices
=> add ppcle machines

ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Common/vars/Ubuntu.yml
=> Add fontconfig for Java10+ builds

ansible/playbooks/windows.yml
Install:
- cygwin/cpio
- VS 2010 Pro
=> Updates for OpenJDK8

ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Common/vars/RedHat.yml
=> Add fontconfig-devel on rhel for Java10+ builds

ansible/playbooks/ubuntu-jckservices.yml
Have already run this on the server so the rules are updated, just need these updates saved in git :-)
=> Add JCK s390x and windows machines to jckservice firewall config

ansible/playbooks/windows.yml
=> Add packages checks prior to installation

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/group_vars/all/adoptopenjdk_variables.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/ANT/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Common/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Debug/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Firefox/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Freemarker/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Freetype/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/GIT/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java7/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java8/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Jenkins_User/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVC_2010/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2013/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/NTP_TIME/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/NVidia_Cuda_Toolkit/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Strawberry_Perl/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Windows_Updates/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cmake/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/vars/main.yml
- This is the rewrite of the Windows.yml playbook into the new format
=> Rewrite of Windows Playbook into new format

ansible/playbooks/ubuntu-jckservices.yml
Closes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/141
=> fix persistent IP tables

ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Nagios_Plugins/tasks/nagios_RedHat.yml, ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Nagios_Plugins/tasks/nagios_Ubuntu.yml
rewrote nagios_RedHat.yml and nagios_Ubuntu.yml
- use common method to add user
- compile using make -j 
- When conditions 
- added License Information
- cleaned up formatting
=> Improvements to nagios_RedHat.yml and nagios_Ubuntu.yml

infrastructure.md
Wrong IPs and OS levels in infrastructure.md - correcting
=> Fix OSUOSL PPCLE machine entries in infrastructure.md

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java7/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java8/tasks/main.yml
This is required for OpenJ9 windows builds.
FYI @vsebe
=> add symlinks for java 7 and java 8

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java9/tasks/main.yml
closes: #158
add java 9 to windows playbook
=> add Java 9 to windows playbook

ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Nagios_Plugins/tasks/nagios_RedHat.yml, ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Nagios_Plugins/tasks/nagios_SLES.yml
- Created play for Nagios Plugins on SLES
- Updated download URL for check_yum in RHEL role
FYI: @geraintwjones
=> Created play for Nagios Plugins on SLES

infrastructure.md
Add `test-osuosl-ppc64le-ubuntu-16-04-1` and `test-osuosl-ppc64le-ubuntu-16-04-2` in list of machines 
Signed-off-by: Mesbah <Mesbah_Alam@ca.ibm.com>
=> Add entry for 2 new machines 

ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Nagios_Plugins/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Nagios_Plugins/tasks/nagios_CentOS.yml, ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Nagios_Plugins/tasks/nagios_RedHat.yml, ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Nagios_Plugins/tasks/nagios_SLES.yml, ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Nagios_Plugins/tasks/nagios_Ubuntu.yml
closes: #176
This PR mainly moves the common nagios tasks into the `main.yml` file
but also cleans up some of the `When` checks that are no longer
necessary with the new layout.
=> Refactor Common Nagios Tasks + cleanup

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/group_vars/all/adoptopenjdk_variables.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/FreeBSD.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Superuser/tasks/main.yml
on freebsd `/etc/sudoers` is actually `/usr/local/etc/sudoers`
=> freebsd fixup 2

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Master_Config/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_FreeBSD.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_SLES.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Tunnel/tasks/main.yml, ansible/playbooks/Supporting_Scripts/Nagios_Ansible_Config_tool/Nagios_Ansible_Config_tool.sh, ansible/playbooks/Supporting_Scripts/Nagios_Ansible_Config_tool/Nagios_RemoteTunnel.sh
ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/204
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/202
- Updated plays to point to Unix not Linux
- Created Nagios Tunnel role
- Created Nagios Remote Tunnel script
- Added ansible_port number var
- Rewrote Nagios_Ansible_Config_tool.sh
=> Nagios Tunnel

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Tunnel/tasks/main.yml
=> Fixed cron job

ansible/playbooks/aix.yml
=> Update AIX environment for java8(_64) and set as default for all users

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Tunnel/tasks/main.yml
Added additional when condition ``` - tunnel_script_result.stat.exists == False ```
Test if already exists, if so skip
=> Added additional when condition

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Master_Config/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Tunnel/tasks/main.yml
syntax issue caused by having brackets are round ansible_port
=> removed {{ }}  around ansible_port - syntax issue

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml
=> Added xorg-x11-server-Xvfb to CentOS test tool package

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Debug/tasks/main.yml
Added ```- "Domain: {{ Domain | default('***Undefined***') }} "``` to debug output
=> Added Domain to debug output

ansible/playbooks/aix.yml
=> Add cmake for openj9/omr compilation

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_SLES.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_Ubuntu.yml
**Now supporting:**
SLES 12 x
SLES 11 x
SLES 11 p
SLES 12 s390x
rhel6  p
rhel6 x
rhel7 x
rhel7 le
rhel7 p
rhel7 s390x
Raspbian 8 armv7l
Ubuntu 14 x
Ubuntu 14 le
Ubuntu 16 X
Ubuntu 16 s390x
Ubuntu 16 LE
=> Added Nagios Plugin support for more OS'

ansible/playbooks/aix.yml
I'm pretty sure that this was incorrect before? Ping @jdekonin to confirm
=> Update aix.yml to point to aix nagios 

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_FreeBSD.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_SLES.yml
This will address issue #253 
Moved the 'Install plugins' from main.yml (Nagios_Plugins) into nagios_{{ ansible_distribution }}.yml
=> Nagios Plugin issue RHEL 7 x #253

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/FreeBSD.yml
I tested this on a FreeBSD image in Vagrant - see https://forums.freebsd.org/threads/official-vagrant-freebsd-images.52717/
=> Added xorg-vfbserver to FreeBSD

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_RedHat.yml
tested on centos6,7 all arches and rhel7 s390x, ppc64le, x64
=> change nagios to install nagios-plugins-all

ansible/playbooks/ubuntu-jck.yml
Details in issue #280 
closes: #280
=> updated `- hosts` to limit play to jck ubuntu

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Security/tasks/main.yml
from:  - jenkins 
to: - "{{ Jenkins_Username }}"
Details in #251
=> changed - jenkins to a var

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Ant-Contrib/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Clean_Up/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Swap_File/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_48/tasks/main.yml
- Fixes to support RHEL 6
- Additional steps for Ant-Contrib on SLES
- Updated cleanup
=> Fixes to support RHEL 6

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Clean_Up/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NVidia_Cuda_Toolkit/tasks/main.yml
Failures seen if DKMS and/or kernel-debug-devel was not installed prior to installing cuda
added cleanup
=>  Updated rhel7 ppc64le section 

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Clean_Up/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/freemarker/tasks/main.yml
=> Add freemarker role for unix playbooks

ansible/playbooks/aix.yml
* set appropriate /etc/security/limits
* set user & group settings
=> Include additional user specific setup for aix playbook

ansible/playbooks/aix.yml
=> Add autoconf to aix playbook

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml
=> Add xz compression to CentOS build tools

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/CentOS.yml
=> Add c++ symlink for CentOS 6

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/ANT/tasks/main.yml
=> Update ant to the latest version for Windows

ONBOARDING.md, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml
Original issue:
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/369
=> Add "binfmt-support" and "qemu-user-static" packages

README.md
=> Add jdekonin to @infrastructure team members

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Jenkins_User/tasks/main.yml
=> Unset expiry for Jenkins user and root

ansible/README.md
Updates based on @johanvos experiences
=> Update ansible docs with required version and s/Linux/Unix

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/autoconf/tasks/main.yml
=> Update autoconf to v2.69 on CentOS 6 and RHEL 6

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml
=> Add Ubuntu repo for GCC 7.3

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_7/tasks/main.yml
Installs from the scl repo for x86-64
Installs from a tarball we're self-hosting (that I build myself from source) p/zLinux
=> Add gcc 7.3.0 to CentOS build machines

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/autoconf/tasks/main.yml
=> Fix conditional for autoconf version check 

ansible/playbooks/AdoptOpenJDK_Services_Playbooks/ubuntu-jckservices.yml
@karianna This is the same change as https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/393 but without the mess of commits ...
=> ansible: Add SoftLayer Windows machine to jckservices iptables

README.md
Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/420
=> Add Sej as infrastructure member in README.md

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NVidia_Cuda_Toolkit/tasks/main.yml
=> Add CUDA installation to CentOS 6 and RHEL 6

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk10/tasks/main.yml
Fixes https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/437
=> ansible: Download adoptopenjdk10 for bootstrapping 11

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gmake/tasks/main.yml
=> ansible: source compile gmake on CentOS/RHEL on ppc64le

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml
This was tested on RHEL7.5 x86 and seems to work just fine. Should fix #471 
Signed-off-by: Connor Willhelm <connor.willhelm@ibm.com>
=> Adding Support for EPEL on RHEL7

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/RedHat.yml
=> Ignore errors when epel-release-latest package is already installed

ansible/playbooks/correct_vnc_install.yml
Fix https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/432 and https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/424
=> Ansible: new playbook to correct version of vncserver on P and Z

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Ant-Contrib/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/FreeBSD.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/OracleLinux.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/SLES.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/ant/tasks/main.yml
- install ant in /usr/local
- fix ant lib in ant-contrib role
Issue #387 
=> Install Apache Ant binary distribution

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/curl/tasks/main.yml
=> Install curl 7.61

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/SLES.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/SLES.yml
=> Add opensuse repo for git installation through package manager

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml
Fixes issue https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/400
=> Update ubuntu.yml to install pigz

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml
- package available on 
-- x86 - ub14,16,18
-- ppcle - ub14,16
-- 390 - ub16
=> Add numactl for ubuntu installs

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Version/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Version/tasks/main.yml
This PR solves #341. Please review it :)
=> Verify if ansible version is 2.4 or above

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gmake/tasks/main.yml
Fixes https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/357 (or at least fixes the current problem!)
=> ansible: Install gmake 4.1 on zLinux

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
=> ccache should be installed after all compilers are installed

CONTRIBUTING.md
* improvement to commit comments provides better tracking of c
content inclusion/exclusion as well as providing documentation
for the reason behind the change.
=> Update contributing guidelines for pull request comments

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Strawberry_Perl/tasks/main.yml
=> Add Strawberry perl to PATH environment variable

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Ant-Contrib/tasks/main.yml
This particular file is rather a mess, but I'm saving fixing it for a subsequent overhaul and making the minimal change required to make the playbook work at the moment ...
=> ansible: Use correct operation to install junit on SLES

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Freetype/tasks/main.yml
Changed checks for when to build freetype as they were
skipping tasks constantly. Also Changed syntax of win_shell
command for building freetype so it will work properly.
=> Updated Freetype role

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
=> ansible: Install MSVS_2010 first as needed to compile freetype etc.

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk10/tasks/main.yml
Currently using an automatically downloaded version into the workspace which is just silly.
=> ansible: Add JDK10 boot JVM to aarch64 machines

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/FreeBSD.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/OracleLinux.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/SLES.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml
=> Add JDK12 prereqs libXi libXrandr to linux playbooks

README.md
=> Update README.md with correct link to CONTRIBUTING.md

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml
- libxrandr-dev
- libxi-dev
Related #640
=> Fix casing on jdk12 packages

ansible/playbooks/aix.yml, ansible/playbooks/nagios/nagios_aix.yml, ansible/playbooks/scripts/AIX_ramdisk.ksh
Fixes for issues:
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/182
and
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/562
=> Ansible: Updates to AIX scripts

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/GIT_Source/tasks/main.yml
Fixes #676 ... part of #673 
Need to verify that the ansible logic is correct before merging
=> ansible: Use installed libcurl on CentOS/RHEL6 to compile git

ansible/playbooks/adoptopenjdk_variables.yml, ansible/playbooks/aix.yml
Separated from Linux part (#624).
ref #618
=> Update AIX playbooks with locales to support MBCS testing

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/SLES.yml
Create Asian locales on Linux distributions which didn't create them.
Install locale filesets to AIX. "/Vendor_Files/aix" should contain the locale filesets of AIX OS.
#618
=> Update Linux playbooks with locales to support MBCS testing

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml
Reverts AdoptOpenJDK/openjdk-infrastructure#702
Addresses #714
=> Revert "Ansible: Add s390x and ppcle64 to RHEL, CENT, and SLES docker tasks"

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_7/tasks/main.yml
Part of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/686
=> Replace gcc7.3 with 7.4 on s390x

ansible/playbooks/aix.yml
=> Fix up missing tags in aix playbook

ansible/playbooks/aix.yml
=> Cleanup whitespace as per travis failure introduced in #734

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gmake/tasks/main.yml
Updated conditional clause to include x86_64 RHEL, CentOS, SLES12 and
Ubuntu14 distributions.
=> Install make 4.1 on Linux x86

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java12/tasks/main.yml
* Add Java12 to main.yml
* Add new role Java12
Pull request #742 must be merged first before this commit will work correctly. The new syntax in this role depend on changes from that pull request
fyi @jdekonin
=> Ansible: Add Windows role Java12

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml
=> Do not install numactl on Linux/Ubuntu/arm32

ansible/inventory.yml
=> Add test-azure-win2012r2-x64-2 and 3 to inventory

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/group_vars/all/adoptopenjdk_variables.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk12/tasks/main.yml
* Added JDK 12 install to Unix playbook
* Add bootjdk variable to adoptopenjdk_variables.yml
* Add ablility for main.yml to read default variables
fyi @jdekonin
Signed-off-by: HusainYusufali husainyusufali7@gmail.com
=> Ansible: Add JDK 12 Role to Unix Playbook

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/OpenSSL/tasks/main.yml
* Fix OpenSSL checks (downloaded, 32 and 64 bit installed, and symlinks created)
* Change method of unarchiving openssl-1.1.1.tar.gz
* Change method of installing and compiling OpenSSL
* Create OpenSSL symlinks
Fixes #749 
Signed-off-by: HusainYusufali husainyusufali7@gmail.com
=> Ansible: Fix OpenSSL installation on Windows

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/OpenSSL/tasks/main.yml
Add to PATH via profile for remote desktop connections and via ssh client environment for Jenkins agent.
Link libraries and clean up old versions.
=> Update OpenSSL to v1.1.1b

ansible/playbooks/aix.yml
=> Fix type used in cpan install path

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
=> Remove CUDA toolkit as OpenJ9 does not yet support it

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/cmake/tasks/main.yml
=> Add cmake role for s390x

ansible/inventory.yml
=> Move Linux/s390x build machine to test farm

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
This reverts commit 794633006b32232c4ebb379bb3b135087c06c65b.
=> Reinstate cuda SDK installation as per TSC#88

.travis.yml, ansible/inventory.yml, ansible/plugins/inventory/adoptopenjdk_yaml.py
=> remove cloudcone machines

ansible/inventory.yml
=> Add godaddy test machines to inventory file

ansible/README.md, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/IcedTea-Web/tasks/main.yml
Implemented and tested it :)
Fixes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/829
=> Add IcedTea-Web onto Windows Playbook

ansible/README.md
Added some write-up on how to run two VMs on different OSs on the same machine, as I had trouble with this before.
=> Ansible-doc-rework

ansible/inventory.yml
closes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/847
=> add win2008r2-x64-2

ansible/inventory.yml
closes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/850
=> remove joyent build machine and add replacement

ansible/inventory.yml
closes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/720
=> add godaddy test machines

ansible/playbooks/aix.yml
Fix a few things that were causing syntax highlighting issues in my default editor ;-)
=> Adjust some of the output messages in AIX playbooks

ansible/Vagrantfile.CentOS7
Written based off the CentOS6 Vagrant file.
=> Added CentOS7 Vagrantfile

ansible/MANUAL_STEPS.md, ansible/inventory.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/MacOSX.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/MacOSX.yml
closes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/849
=> add additional 10.12 build machine

ansible/inventory.yml
=> Add two new AIX machines to inventory.yml

ansible/inventory.yml, ansible/plugins/inventory/adoptopenjdk_yaml.py
closes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/868
closes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/680
=> add ppc64le and aarch64 test machines

ansible/inventory.yml
the machines have now been decommissioned
=> remove deleted JCK machines

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/MacOSX.yml
=> install nasm on build macOS

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/MacOSX.yml
required for macOS codesigning
=> add p7zip to test tools

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/MacOSX.yml
the linter was failing on all PR's because of this comment
=> fix linter issue

ansible/plugins/inventory/adoptopenjdk_yaml.py
closes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/886
=> fix inventory deprecation error

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/MacOSX.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Debug/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/ant/tasks/main.yml
this avoids us hard-coding the username on macOS
=> improve username logic for running non-sudo tasks on mac

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NVidia_Cuda_Toolkit/tasks/main.yml
Fixes https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/851
=> Enable ppc64le CUDA install on CentOS7 as well as RHEL7

ansible/pbTestScripts/buildDocker.sh
Requested due to the script escaping the Jenkins workspace.
=> Changed variables "HOME" to "WORKSPACE" in Docker test script

ansible/pbTestScripts/README.md
Updates the README to make it more obvious on how to use the script, since adding in the ability to test the playbooks from a specific branch.
=> Updated pbTestScripts/README.md to reflect script changes

ansible/pbTestScripts/buildDocker.sh
FYI @willsparker - have done this
=> Fixup last commit - adjust git clone target dir

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/SLES.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml
Needed for `--enable-dtrace` to work, as described in https://github.com/AdoptOpenJDK/openjdk-build/issues/1242
=> Add systemtap-sdt to all Linux distros

ansible/Vagrantfile.Win2012
PR to fix an issue in the last PR (#934)
=> Altered Windows Vagrantfile to have correct syntax

ansible/pbTestScripts/testScript.sh
=> pbTest: Fix missing ) in testScript.sh

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NVidia_Cuda_Toolkit/tasks/main.yml
=> Add nvidia support for ubuntu16 ppcle

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/OpenSSL/tasks/main.yml
AdoptOpenJDK/openjdk-security#3
Signed-off-by: Rajdeep Singh <rajdeep.s@hotmail.com>
=> Updating to use OpenSSL 1.1.1d

ansible/inventory.yml
=> Move marist/s390x-2 from JCK group to main test group

ansible/inventory.yml
Part of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/753
=> inventory.yml: Update Linaro machine details

ansible/README.md
Important change as the variable wouldn't fix the macOS issue if "yes" isn't capitalised.
=> PB: small README.md change

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Protobuf/tasks/main.yml
* changed configure options for Protobuf to make Protobuf more optimized
* replacing #883
=> Changed Protobuf configure options

ansible/inventory.yml
Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/910
=> inventory: Add vagrant bare metal test machine

ansible/pbTestScripts/testScript.sh
This will stop the script if the playbooks don't succeed - as theres no point trying to build if the playbooks fail.
Due to this, the Windows section will clear up the files from the old run, just before doing a new one.
=> pbTests: Stops script if playbook fails; Cleans up after Windows VM

ansible/pbTestScripts/testScript.sh
PR to change `testScript` to do several things:
- Ensure that the inventory file can be picked up by the `ansible all` command when running a build on the Unix playbook, by being in the correct directory.
- Change the `searchLogFiles` function to `exit 1` when `unreachable=1` is detected.
- Refactor so `branchName` is set to `master` earlier on, so multiple `if` statements can be stripped out.
=> pbTest: Ensure in correct dir to start build; Add to grep to log file search; Refactor

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/SLES.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/SLES.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml
[skip ci]
Signed-off-by: Jenny Chen <Jenny.Chen@ibm.com>
=> Add 32-bit C Library to Adopt Unix Playbook

ansible/pbTestScripts/testScript.sh
Will update the git repository without git throwing "Please tell me who you are".
=> pbTests: Don't specify URL when git pulling

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/GIT_Source/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NVidia_Cuda_Toolkit/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/curl/tasks/main.yml
After #1000 , Decided it'd be best to add retries to other links that tend to fail, like the (still growing) list on #994.
=> UnixPB: Added retries to roles that often fail

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Swap_File/tasks/main.yml
=> add missing swap_file tag

ansible/inventory.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml, ansible/plugins/inventory/adoptopenjdk_yaml.py
closes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1037
FYI @smlambert
=> add additional aarch64 test machines

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Swap_File/tasks/main.yml
FIx @gdams indentation, introduced in https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1057 ;-)
=> Fix earlier swap_file tag indentation

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/7-Zip/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/ANT/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Clang_32bit/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Clang_64bit/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Firefox/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Freemarker/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Freetype/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/GIT/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/IcedTea-Web/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java7/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2010/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2017/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/NVidia_Cuda_Toolkit/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/OpenSSL/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Rust/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Strawberry_Perl/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cmake/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/nasm/tasks/main.yml
Additional to #998 and #1051 .
Tested on Windows Vagrant VM and succeeded:
https://ci.adoptopenjdk.net/job/SXA-PlaybookCheckParallel/OS=Win2012,label=vagrant/lastBuild/console
=> WinPB: Added Checksums to win_get_url modules

ansible/pbTestScripts/vmDestroy.sh
=> Allow Debian8 as an option to vmDestroy.sh

ansible/pbTestScripts/buildJDK.sh, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Debian.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Debian.yml
Hopefully fixes https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1067
=> ansible: Add adoptopenjdk8 to Debian

ansible/pbTestScripts/vagrantPlaybookCheck.sh
=> Fixup last commit which had wrong main Vagrantfile path

FAQ.md, README.md
=> Add initial openjdk-infrastructure FAQ

ansible/inventory.yml
also removes 1012-2 (got removed a while back)
=> add build-macstadium-macos1014-1

ansible/inventory.yml
Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/146
=> inventory: Add new AIX systems

ansible/inventory.yml
=> inventory: Add first 2 AWS Win2019 systems

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/CPAN/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NTP_TIME/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gmake/tasks/main.yml
Added tasks for RHEL8 to install Common packages, and skip CPAN & gmake roles for issue #1125.
=> updates to support RHEL 8 playbooks

ansible/inventory.yml
Adding full set of AIX systems with correct roles
=> More aix machines woohoo

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
* apply change to windows playbook as performed in #1017
* AdoptOpenJDK/openjdk-infrastructure#423
=> winPB: Passed the value of hosts from command line

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml
=> win: Adjust cygwin setup checksum as it's been updated

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/SLES.yml
=> unixPB: Remove repeat in SLES package list

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java_install/tasks/main.yml
=> winPB: Switch adoptopenjdk download to use APIv3

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_7/tasks/main.yml
Need to make sure this doesn't break anything before merging, hence WIP
=> unixPB: Remove devtoolset-7 and require Adopt's GCC7.5

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/git-hg-jenkins.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/git-hg/tasks/main.yml
This pr includes a playbook to help setup machines for git-hg, jemmy, jtreg and jtharness jenkins tasks. See https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/819
=> Git-hg playbook

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/maven/tasks/main.yml
Signed-off-by: Rajdeep Singh <rajdeep.singh@ibm.com>
=> Adding Apache Maven Role

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java8/tasks/main.yml
Ref: #1167 
Ensuring Java8 uses APIv3 as well
=> WinPB: Make Java8 role use APIv3

ansible/pbTestScripts/qemu_test_script.sh
Useful change so we can test new changes to the playbooks on different architectures, requested by @sxa555
=> pbTests: Add options to specify infra repo/branch for qemu script

.travis.yml, ansible/playbooks/AdoptOpenJDK_ITW_Playbook/roles/automake/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_ITW_Playbook/roles/pkg-config/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_ITW_Playbook/roles/rust/tasks/main.yml, ansible/playbooks/vagrant.yml
I noticed whilst looking at #783 and #782 that the new playbooks written by @Haroon-Khel and I weren't added to the `.travis.yml` file.
=> Add additional playbooks to .travis.yml

ansible/pbTestScripts/buildJDK.sh, ansible/pbTestScripts/vagrantPlaybookCheck.sh
Beforehand, both `buildJDKwin.sh` and `buildJDK.sh` had the ability to build with Hotspot, however this wasn't usable by the VagrantPlaybookCheck Jenkins job as it wasn't be passed through to them via `vagrantPlaybookCheck.sh`.
I also noticed that when building a JDK version other than 8 on linux, the `JDK_BOOT_DIR` was just being set as `JAVA_HOME` which was being set to JDK8 to run Gradle. I've improved the logic so it will first look for JDK_VERSION-1 , and if it can't find it, it will settle for JDK_VERSION. With the playbooks installing 8,10,12 and 13, this should suffice to build them all.
=> pbTests: Add option for Hotspot & improve JDK_BOOT_DIR detection

ansible/inventory.yml, ansible/plugins/inventory/adoptopenjdk_yaml.py
Would avoid the confusion in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1201
Fixes https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1203#event-3134063564
=> inventory: Add docker- prefixed machines

ansible/pbTestScripts/testJDK.sh
Fixing a syntax error introduced in #1199
=> pbTest: Fixing a syntax error

ansible/plugins/inventory/adoptopenjdk_yaml.py
small nit from @sxa555's last PR
=> swap double quotes for single quotes

ansible/inventory.yml
- Windows Server 2008R2 rebooted
- Public IP changed.
=> Update to Azure machine IP address.

ansible/inventory.yml
Adding the machines @gdams and I setup today. They've got most of the pre-reqs and should be ready to use by tomorrow :-)
=> inv: Add Azure-Win2012r2 machines

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/WiX/tasks/main.yml
Add's tool documented in https://github.com/AdoptOpenJDK/openjdk-installer/blob/master/wix/README.md#requirements-for-build-environment
=> add wix role

ansible/inventory.yml
=> inventory: Add AWS docker x64 machines

ansible/inventory.yml
=> inventory: Add build-rhel7 (for GAO and maybe more) systems

ansible/inventory.yml
removes the old deleted machines
=> remove build-azure-2008r2 machines

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml
It's changed again.
@sxa555 How'd you feel about taking the checksum off the Cygwin Setup?
=> winPB: Change Cygwin checksum

ansible/inventory.yml
@gdams and I setup a new Softlayer Windows Test machine.
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/52/console
=> inv: Add new softlayer win2012 test machine

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/OpenSSL/tasks/main.yml
OpenSSL-1.1.1f
**Update:** Now OpenSSL-1.1.1g
Pav.Salimon@ibm.com
=> winPB: Updated OpenSSL role

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/MacOSX.yml
fixes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1301
=> add adoptopenjdk10 to macos playbook

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/MacOSX.yml
=> UnixPB: Add cmake to list for brew to install on OSX

ansible/inventory.yml
Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1338#discussion_r431779754
=> inv: Put back test-softlayer-win2012r2-x64-1

ansible/Dockerfile.CentOS6, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Ant-Contrib/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Clean_Up/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/SLES.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/GIT_Source/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NVidia_Cuda_Toolkit/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/ccache/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/cmake/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/freemarker/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_48/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gmake/tasks/main.yml
fixes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1312
=> cleanup leftover tarballs and dockerfiles

ansible/Dockerfile.CentOS6
you cannot use variables in the same ENV block
=> swap JDK variables to hard coded

.github/workflows/build.yml, .github/workflows/linter.yml, .travis.yml, ansible/Dockerfile.CentOS6, ansible/Dockerfile.CentOS7, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/GIT_Source/tasks/main.yml
Makes the centos7 build image available on ppc64le and arm64.
Switched the build to Travis as GH Actions doesn't support those architectures
=> WIP: docker multi-arch builds

ansible/Dockerfile.CentOS6
broken by https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1426
=> fix JDK8_BOOT_PATH

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml
=> WinPB: Update Cygwin_checksum

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/cmake/tasks/main.yml
Ref https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1462
This pr includes a condition in the cmake role to install cmake on aarch64
=> UnixPB: Install cmake on aarch64

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NVidia_Cuda_Toolkit/tasks/main.yml
=> unixPB: Fix typo in message while installing CUDA

ansible/Dockerfile.CentOS6, ansible/Dockerfile.CentOS7
Fixes: https://github.com/AdoptOpenJDK/openjdk-build/issues/2005
=> docker: Remove Jenkins user from Dockerfiles

ansible/Dockerfile.CentOS6, ansible/Dockerfile.CentOS7
Reverts AdoptOpenJDK/openjdk-infrastructure#1497
this has broken all the builds. needs more investigation
=> Revert "docker: Remove Jenkins user from Dockerfiles"

.github/workflows/build.yml, ansible/Dockerfile.Alpine3, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Alpine.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Alpine.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NTP_TIME/tasks/main.yml
Allows us to build musl openjdk binaries
See https://github.com/AdoptOpenJDK/TSC/issues/168 for more information
=> ansible: add alpine build image

ansible/pbTestScripts/qemuPlaybookCheck.sh
ref https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1471
=> Add support for arm32 to qemuPlaybookCheck.sh

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Debian.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Debian.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_7/tasks/main.yml
ref https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1528
related https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1533
Added a condition to the `gcc_7` role so that it runs on Debian for arm32
=> unixPb: Add gcc_7 role to arm32

docs/Setup-QEMU-Images.md
Added a summarised version of the instructions that I used to create a debian 8 arm32 disk image. Ive also included a link to the instructions
=> Add debian8.arm32 setup to qemu docs

.github/workflows/build_windows.yml
fixes the failing docker login command on windows
=> docker: fix docker login command windows

.github/workflows/build_windows.yml
Currently the job won’t run if the workflow file is changed. This PR adds the workflow to the paths
=> docker: Add workflow to windows action

.github/workflows/build_mac.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/MacOSX.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/MacOSX.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/zulu7/tasks/main.yml
linked to https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1638
Also replaces https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1317
=> actions: add macOS playbook tester

ansible/inventory.yml
=> inventory: add trss.adoptopenjdk.net on AWS

ansible/inventory.yml
=> Update TRSS IP address

ansible/inventory.yml, ansible/plugins/inventory/adoptopenjdk_yaml.py
=> delete all perf machines

ansible/playbooks/Supporting_Scripts/Nagios_Ansible_Config_tool/templates/template.cfg, ansible/playbooks/Supporting_Scripts/Nagios_Ansible_Config_tool/templates/template_with_graph.cfg
ref: #1660 
Correct a mistake I made in the templates- It's `notifications_enabled 0` , not `enable_notifications 0` :man_facepalming:  
https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/objectdefinitions.html#service
=> Nagios: Correct notification option in templates

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Dragonwell/tasks/main.yml
- [ x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
=> ansible : add dragonwell bootstrap image for windows

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2019/tasks/main.yml
=> winPB: add arm components to VS2019 role

ansible/inventory.yml, ansible/plugins/inventory/adoptopenjdk_yaml.py
Added the machines build-alibaba-win2012r2-x64-1 and 2 to the inventory file. They are already in jenkins
@sxa Bastillion will need to be updated, if it already hasnt been
=> Inventory: add alibaba machines

ansible/inventory.yml
=> inventory: Remove decomissioned AWS machines

.github/ISSUE_TEMPLATE/systemfaulty.md, .github/PULL_REQUEST_TEMPLATE.md, FAQ.md
FYI @lumpfish - let me know if you're happy with the wording in here ;-)
=> github: add system faulty issue template, and add nagios to PR template

ansible/inventory.yml
=> inventory: Add alibaba aarch64 machines

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Jenkins_User/tasks/main.yml
=> unixPB: Fix typo macoS -> macos

ansible/inventory.yml
=> Remove linaro

ansible/inventory.yml
Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1932
=> inventory: Add Azure win2016/2019 machines

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/OpenSSL/tasks/main.yml
=> winPB: Update Openssl to 1.1.1j

.github/labeler.yml, .github/workflows/build.yml, .github/workflows/build_vagrant.yml, .github/workflows/labeler.yml
=> github: add label bot to help with triaging

.github/regex_labeler.yml, .github/workflows/labeler.yml
=> github: add regex parsing bot for additional labelling

.github/regex_labeler.yml
=> switch mac regex to macos to fix matching

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml
=> unixPB: Add ssh client to CentOS common packages

.github/labeler.yml, .github/regex_labeler.yml
=> github: add nine label to bot and update docs

FAQ.md
(This was written quickly before I forgot what I was going to write and so there may be gibberish in it but hopefully it's vaguely useful gibberish that we can base further updates on ... Reviewers can check out the rendered markdown in my branch at https://github.com/sxa/openjdk-infrastructure/blob/build_test_faq/FAQ.md#how-do-i-replicate-a-build-failure)
=> Update FAQ.md with some brief guidance and links to build/test problem reproduction

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/OpenSSL/tasks/main.yml
=> winPB: Update Openssl to 1.1.1k

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, FAQ.md
Changes split out from https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1974
=> doc: miscellaneous updates to CONTRIBUTING guide

FAQ.md
Split out from https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1974
=> docs: add information about the build dockerfiles

ansible/inventory.yml
=> inventory: add test macos m1 machines

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/MacOSX.yml
=> unixPB: install gnupg on macOS machines

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml
=> unixPB: Install pigz on CentOS to speed up final build compression

FAQ.md
=> docs: Update FAQ with information on DockerStatic containers

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.alp313, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/tasks/main.yml
=> Updated for Alpine Linux 3.13 based on Part 1 & 2 instructions

ansible/inventory.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Solaris.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Solaris.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_Solaris.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/maven/tasks/main.yml, ansible/plugins/inventory/adoptopenjdk_yaml.py
Adds support for Solaris Sparc in our playbooks
=> inventory: add new solaris sparc machines

.github/workflows/build_vagrant.yml
=> github: fix vagrant install

.ansible-lint, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml
fixes: https://github.com/adoptium/infrastructure/issues/2226
=> fix ansible lint errors

ansible/pbTestScripts/qemuPlaybookCheck.sh
Fixes: #2194 
Checks every 10 seconds whether the QEMU VM has booted, by querying the log file. Timeout is currently set for 180s, as that appears to be the shortest time it takes for all VMs in QPC to boot - so if anything goes wrong with booting, it'd timeout and fail quickly. 
Testing on the `infra-ibmcloud-vagrant-x64-1` machine, though only on Ubuntu18/PPC64LE, I will put it through QPC just to make sure all the platforms work, and that the timeout isn't too restrictive.
=> pbTests: Better logic for checking Qemu VM has booted

ansible/inventory.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Get_Vendor_Files/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Get_Vendor_Files/tasks/main.yml, ansible/plugins/inventory/adoptopenjdk_yaml.py
=> inventory: add skytap ppc64le linux machines

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Solaris.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Get_Vendor_Files/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Get_Vendor_Files/tasks/main.yml, ansible/plugins/inventory/adoptopenjdk_yaml.py
=> unixPB: playbook tweaks from running on new jck solaris x64 machines

README.md
=> docs: Add Infrastructure Providers logos

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/MacOSX.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/MacOSX.yml
Also removed xquartz which is no longer needed
=> unixPB: macOS install thunderbird, blackhole and PDFwrite for JCK

FAQ.md, ONBOARDING.md, README.md, ansible/README.md, ansible/pbTestScripts/buildJDK.sh, ansible/pbTestScripts/qemuPlaybookCheck.sh, ansible/pbTestScripts/vagrantPlaybookCheck.sh, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/aixfs/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/rbac/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/yum/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/additional_plugins/nagios_server_plugins/check_inventory, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/additional_plugins/nagios_server_plugins/check_nagios_sync, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_MacOSX.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Tunnel/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Python2.7/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_7/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gmake/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/README.md, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Common/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Windows_Updates/tasks/main.yml, ansible/playbooks/Supporting_Scripts/Nagios_Ansible_Config_tool/README.md, ansible/playbooks/aix.yml.old, ansible/vagrant/Vagrantfile.Debian10, ansible/vagrant/Vagrantfile.Win2012, ansible/vagrant/Vagrantfile.Win2016, docs/Setup-QEMU-Images.md
=> fix: change links to adoptium

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/jckservices_iptables/tasks/main.yml
=> add 139.178.86.125 to jckservices iptables

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/OpenSSL/tasks/main.yml
Issue: https://github.com/eclipse-openj9/openj9/issues/13373
=> winPB: Update Openssl to 1.1.1l

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/yum/tasks/main.yml
=> aixPB: remove unneeded libXrender-devel and related packages

README.md
=> docs: add skytap logo to sponsors page

ansible/inventory.yml
ref https://github.com/adoptium/infrastructure/issues/2377
=> inventory: add new alibaba machines to inventory

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/OpenSSL/tasks/main.yml
=> Update Win playbook to OpenSSL 1.1.1m

FAQ.md, README.md
=> docs: update links

FAQ.md
=> docs: fix typo

ansible/docker/Dockerfile.Alpine3, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.alp314
This is in the other Alpine files, but not 3.14, so this makes them all consistent. I've applied this to the existing 3.14 images
=> Alpine314 fakeroot

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/debian.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/rhel.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/sles.yml
- for Debian <10, install different packages
- missing enable docker repo for Debian >=10
- always restart docker service, not only based on if docker client is installed or not
- waiting for VPC job done
- [ x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ x] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
=> ansible: fix docker role

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_11/tasks/main.yml
=> unixPB: Add gcc11.2 role for jdk19+

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/trss.yml
- use unarchive download and unpack nodejs
- use apt_* module handle mongodb key repo
- use user module create jenkins
- use blockinfile append two lines in nginx default config
- move tasks to to more consistent
=> ansible: refact trss

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/bootjdk/tasks/openjdk.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Ant-Contrib/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Xcode/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml
- vars list syntax: https://github.com/adoptium/infrastructure/actions/runs/2494052012
- removed empty "when"
- make 1 as string
=> ansible: fix linter

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/trss.yml
=> trssPB: Install java for the TRSS jenkins agent

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/trss.yml
Fixes: https://github.com/adoptium/infrastructure/issues/2591
=> unixPB: upgrade nodejs from 12.x to 16.x for TRSS

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.deb11, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/scripts/updatepackages.sh, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/tasks/main.yml
=> docker: Add Dockerstatic File for Debian 11.

.github/ISSUE_TEMPLATE/testcasefail.md
=> github: Provide more suggestions for info to include for a test failure

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Clean_Up/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Solaris.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Solaris.yml
Fixes Aqa 3831 ( https://github.com/adoptium/aqa-tests/issues/3831 )
=> UnixPB: Update Git To Newer Version On Solaris 10.

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/SLES.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/SLES.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Jenkins_User/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Superuser/tasks/main.yml
Fixes #2670 
- [] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
=> unixPB: SLES15(SP3) Compatibility Fixes & Updates

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Debian.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/openSUSE.yml
Please put the name of the software product (and affected platforms if relevant) in the title of this issue
The Adoptium AQAvit tests require `Xvfb` to be started on Linux in order to test GUI capabilities. Our playbooks currently install both Xvfb and Xorg - the latter of which shouldn't be necessary since the machines themselves are all either virtual or sitting in data centres, so I believe we can remove it (Perhaps it predates Xvfb?). On some Linux distributions (Certainly Ubuntu, possibly others) the `xorg` package, when installed via ansible, pulls in `gdm3` which results in it starting a GUI greeter on the "console" of the machine, chewin up resources unnecesarily.
ALTERNATE OPTION: We could continue to let it be installed, but …
=> unixPB: Remove xorg packages to avoid dragging in gdm

ansible/inventory.yml
New systems from Marist to replace the existing ones. At the time of writing these have not been set up but having this PR in place will allow us to set them up with AWX.
=> inventory: Add replacement Linux/s390x systems from Marist

ansible/inventory.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/SLES.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/SLES.yml
=> UnixPB: sles15 python interpreter default change, add cron to package list.

.github/ISSUE_TEMPLATE/teamaccess.md
=> docs: Typo in git issue template

.github/workflows/build_vagrant.yml
Download the adoptium solaris10 box image if not present in vagrant.
Fixes #2694
=> github: Download Solaris10 box Image If Missing

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/SLES.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/SLES.yml
=> UnixPB: Correct issues with Git on SLES12 SP5.

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/jckservices_iptables/tasks/main.yml
Add two new marist machines, remove old windows machines, cleanup
=> ansible: Update iptables

.github/workflows/code-freeze.yml
=> github: forward repo secrets to code freeze workflow

ansible/playbooks/nagios/README.md
Fixes : #2767 
Signed-off by Sarah Aligbe sarahligbe12@gmail.com
=> add disk space check for /home/jenkins in AIX hosts

ansible/playbooks/nagios/README.md
Fixes https://github.com/adoptium/infrastructure/issues/2766
cc @steelhead31 @smlambert @sxa
=> Add Additional Disk Space Check For /tmp on AIX hosts

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/main.yml
Updated the checksum for the nagios check_mem plugin.
Fixes #2810
=> UnixPb: Update checksum for check_mem.pl

ansible/playbooks/nagios/roles/Nagios_Server/scripts/nagios_host_group_add.sh
Edited "`enter enter the hostgroup members`" to "`enter the hostgroup members`"
cc @steelhead31 @zdtsw
=> Refactor code

ansible/playbooks/nagios/HOW_TO_ADD_WINDOWS_TO_NAGIOS.md
Documented and tested Process i took  to add a Windows Host To a Nagios Server 
Output:
fixes #2802 
signed off by @lumuchris256 
cc @steelhead31 @sxa @smlambert @Haroon-Khel @karianna
=> Enhancement: Adding windows machine to Nagios

ansible/inventory.yml
=> inventory: add skytap dockerhost to inventory.yml

ansible/playbooks/nagios/roles/Nagios_Config/defaults/main.yml, ansible/playbooks/nagios/roles/Nagios_Config/scripts/Create_Nagios_Servicegroups_config_file.py, ansible/playbooks/nagios/roles/Nagios_Config/tasks/Create_Nagios_Server_Configurations.yml, ansible/playbooks/nagios/roles/Nagios_Config/tasks/Create_Nagios_Servicegroups.yml, ansible/playbooks/nagios/roles/Nagios_Config/tasks/main.yml, ansible/playbooks/nagios/vars_configure_server.yml
Updated the Nagios_Config playbook to create the servicegroups.cfg file that contains a service group entry for each of the group types in the inventory
fixes #2865 
signed off by @lumuchris256 
cc @steelhead31 @Haroon-Khel @smlambert
=> Amend Nagios/Ansible Config Role To Create Service Groups Config File 

README.md
Fixes https://github.com/adoptium/infrastructure/issues/2749
=> docs: add Scott Fryer as infrastructure team member

ansible/inventory.yml
Removing 2 machines from the inventory that are no longer in service.
=> inventory: Remove 2 defunct docker- hosts.

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/X11/tasks/main.yml
Fixes https://github.com/adoptium/infrastructure/issues/2906
=> unixPB: fix linter

CONTRIBUTING.md
Update contributing docs to include QEMU-playbook-check pr check
=> Docs: update pr testing information

ansible/inventory.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Jenkins/tasks/main.yml, ansible/plugins/inventory/adoptopenjdk_yaml.py
=> winPB: add windows aarch64 machines

docs/AccessControl.md
FAQ will be updated later to point at this, but since https://github.com/adoptium/infrastructure/pull/2977 is in-flight I'm holding off on that for now.
Fixes https://github.com/adoptium/infrastructure/issues/2967 and https://github.com/adoptium/infrastructure/issues/2970
=> doc: Add document describing access controls at the project

FAQ.md
Mostly fixes https://github.com/adoptium/infrastructure/issues/2458
=> doc: Update FAQ.md to list correct set of GH teams

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/README.md, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Get_Vendor_Files/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Jenkins_Service_Installation/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Jenkins_Service_Installation/templates/JenkinsAgentService.xml.j2
=> winPB: automate jenkins service installation

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/bootjdk/tasks/openjdk.yml
Noticed the condition was not skipping on jdk versions 10 and 16. Fixed and works as expected
=> aixPb: Change numbers to strings in condition

ansible/inventory.yml
as test-osuosl-aix72-ppc64-[3,4]
=> ansible: rebrand test-osuosl-aix715-ppc64-[3,4] 

ansible/inventory.yml
=> inventory: remove old Scaleway system

ansible/inventory.yml
as test-osuosl-aix72-ppc64-[5,6]
=> ansible: rebrand test-osuosl-aix715-ppc64-[1,2] 

ansible/docker/Dockerfile.Ubuntu1604
Fixes https://github.com/adoptium/infrastructure/issues/3150
=> docker: Lock PyYAML for Ubuntu 16 build dockerfile

ansible/README.md, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/main.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/security/handlers/main.yml, ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/security/tasks/main.yml
EF issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3430#note_1190148
ansible: Update /etc/ssh/sshd_config
ansible: force_handlers: True
=> Update ansible for AIX - X11 forwarding.

ansible/inventory.yml
=> ansible: rebrand build-osuosl-aix71-ppc64-1 as test-osuosl-aix73-ppc64-1

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml
Use dnf config-manager to enable powertools repo.
Fix libdwarf package name.
=> UnixPb: CentOS8 Updates

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/jckservices_iptables/tasks/main.yml
Inventory: Add jck-skytap-aix72-ppc64-4
EF issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3430
=> Add jck-skytap-aix72-ppc64-4

docs/AccessControl.md
=> doc: Update AccessControl.md with repository information

CONTRIBUTING.md
Draft while we're in a release cycle
=> docs: Update CONTRIBUTING.md which is a bit stale

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2022/tasks/main.yml
Fixes #3260 
Update VS2022 Checksum.
=> WindowsPB: Update checksum for vs 2022 community download

CONTRIBUTING.md, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2022/tasks/main.yml, wazuh/README.md, wazuh/agent/windows/agent.snippet.conf, wazuh/agent/windows/anti_flooding_config.MD, wazuh/server/ssh-key-logging/0310-ssh_decoders.snippet.xml, wazuh/server/ssh-key-logging/Extending_The_SSH_Logger.MD
Fixes #3212 
Initial commit and creation of Wazuh specific area of repository.
This should allow contributions and storage of custom code/configuration snippets used for amending a default Wazuh installation.
(https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
=> Wazuh: Initial commit of Wazuh code sharing repository.

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Alpine.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Debian.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Fedora.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/FreeBSD.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/SLES.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Solaris.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/openSUSE.yml
Fixes https://github.com/adoptium/infrastructure/issues/3251
=> unixPB: Add strace tooling for Unix platforms, and truss for Solaris

ansible/inventory.yml
In draft pending addition to the services in the last checkbox above :-)
Noting also that at present the playbooks have not been run on the machine.
Fixes #3208 
Thank you to @aixtools for doing the intial OS+compiler setup 👍🏻
=> inventory: Add OSUOSL aix build-3 with 7.2TL05+XLC17

FAQ.md
ref https://github.com/adoptium/infrastructure/issues/2753#issuecomment-1853901010
=> doc: update FAQ with how to add new repository to AdoptOpenJDK dockerhub

ansible/inventory.yml
=> inventory: Add new trss server to inventory.yml

ansible/inventory.yml
=> inventory: add new OSUOSL jenkins-worker

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/README.md
Documentation updated for work done in this pr https://github.com/adoptium/infrastructure/pull/3390
=> docs: Update documentation with how to use dockernode.yml playbook

ansible/inventory.yml
Ref: https://github.com/adoptium/infrastructure/issues/3378
=> inventory: add azure dockerhost

.github/labeler.yml, .github/workflows/labeler.yml
Following the bump to the labeler actions version, the configuration for the labeler needs updating.
=> Github: Update Labeler Configuration File To New Format.

.github/workflows/code-freeze.yml, .github/workflows/labeler.yml, ansible/inventory.yml, ansible/plugins/inventory/adoptopenjdk_yaml.py
=> inventory: add scaleway risc-v hosts to inventory

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/SLES.yml
Fixes: https://github.com/adoptium/infrastructure/issues/3436
Updated the devel-tools URL with 15.5
=> unixPB: Fix SLES 15 Devel-Tools repo url

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Providers/tasks/main.yml
=> apply cloud.cfg etc/hosts fix for scaleway

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/jckservices_iptables/tasks/main.yml
EF issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4285
=> ansible: decommission skytap AIX 7.1 machines

ansible/inventory.yml
Following a restart , the public IP address of this machine has changed, and the inventory requires an update.
=> inventory: Update public IP for win2019 test machine

ansible/inventory.yml, ansible/plugins/inventory/adoptopenjdk_yaml.py
=> inventory: Remove equinix_esxi systems

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2022/tasks/main.yml
Fixes #3541 
VPC in progress: https://ci.adoptium.net/job/VagrantPlaybookCheck/OS=Win2022,label=vagrant/1870/console
=> WindowsPB: Update checksum for VS2022 bootstrap installer.

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.u2404
ref https://github.com/adoptium/infrastructure/issues/3501
=> docker: Add Ubuntu 24.04 dockerfile

ansible/DockerInventory.json
[DockerInventory.json](https://github.com/adoptium/infrastructure/blob/master/ansible/DockerInventory.json) updated with [updateDockerStaticInventory.py](https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/scripts/updateDockerStaticInventory.py)
=> inventory: Update docker static inventory

.github/workflows/semgrep_diff.yml
Add the permissions scheme required for github actions.
=> gha : Add permissions scheme

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2022/tasks/main.yml
Update the MSVS2022 CE bootstrap checksum
Fixes #3607
=> WindowsPB: Update VS2022 Download Checksum

.github/workflows/packer.yml
=> packer: fix sed command for linux

.github/workflows/packer.yml
=> packer: use matrix to speed up builds

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/ANT/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/GPG_signature_verification/tasks/main.yml
Fixes #3638 
VPC OK: https://ci.adoptium.net/job/VagrantPlaybookCheck/OS=Win2022,label=vagrant/1895/console 
Fails on wix installation, which is fixed in this PR, which will be rebased with these changes:
https://github.com/adoptium/infrastructure/pull/3628
=> WinPB: Update GPG Verification Process For Ant Binary

ansible/inventory.yml
(https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
Machine added to Nagios & Wazuh
=> inventory: Add 3rd Windows 2022 Host

.github/workflows/packer.yml
=> Add missing token

ansible/DockerInventory.json
Latest changes to `DockerInventory.json` using the updateDockerStaticInventory.py script
=> docker: Update the static docker inventory file

ansible/DockerInventory.json, ansible/inventory.yml
ref https://github.com/adoptium/infrastructure/issues/3693
I updated the docker inventory in the same pr. Alot of the changes detected by git in the DockerInventory.json file are line position changes which is confusing git, but its fine
=> inventory: Update azure x64 dockerhost to ubuntu 2404 and update DockerInventory.json

README.md
=> doc: add note about non-pipeline jobs to jenkins upgrade guide

ansible/inventory.yml
Add test-azure-windows2022-4 machine.
Machine has been tested, had playbooks run, added to Nagios / Wazuh / Jenkins etc.
=> Inventory: Add Azure Test Windows 4 Machine

tools/restart_trss.sh, tools/run_backups
=> tools: Improve TRSS MongoDB Backup Plan

.github/workflows/build_mac.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/MacOSX.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/MacOSX.yml
fixes: https://github.com/adoptium/infrastructure/issues/3987
=> unixPB: install make on macOS via brew

ansible/packer/README.md, ansible/packer/orka-base.pkr.hcl, ansible/packer/orka.pkr.hcl, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Xcode11/tasks/main.yml, ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Xcode15/tasks/main.yml
=> unixPB: fix orka VM templates

README.md
=> doc: link to jenkins LTS changelog
