ansible/playbooks/ubuntu.yml

Was: with items:
changed to with_items:

missing underscore in Cleanup cmake

---

ansible/playbooks/rhel.yml

Disabled 'Enable rhel-7-server-extras-rpms Repo' on s390 hosts
- ansible_architecture != "s390x"
Changed 'ansible_processor_vcpus' to use 'ansible_processor_cores' when the host is s390
This is a workaround as ansible only shows 1 cpu on s390 when using ansible_processor_vcpus
cmake and ccache
Disabled Docker install on S390
- ansible_architecture != "s390x"

RHEL 7 s390 updates

---

ansible/playbooks/rhel.yml

* add libstdc++-static and libexpat-dev
* compile and install git from source as default 1.8 does not met minimum requirement

Update for rhel7 ppcle OpenJ9 requirements

---

ansible/playbooks/rhel.yml

Updated title of 'Cleanup NVidia CUDA toolkit' to 'Cleanup NVidia CUDA toolkit - PPC64LE'
Fixed ansible_distribution_major_version in 'Cleanup NVidia CUDA toolkit - PPC64LE' (was 16 changed 7)
Removed doubled up build_tools
- libXrender-devel
- libXt-devel
- libXtst-devel

fixes to  NVidia CUDA toolkit and build_tools

---

ansible/playbooks/centos_7.yml
ansible/playbooks/ubuntu.yml

Ubuntu: Updated the list of supported OS/Arch's at the top of the playbook
Major rewrtie of centos playbook
- Added symlink for gmake
- Changed 'jenkins' '{{ Jenkins_Username }}' to allow for AdoptOpenJDKs variable file
- Added use of {{ ansible_processor_vcpus }} to speed up compiles
- Removed JQ (not longer a requirement)
- Reordered ant-contrib/cmake to align it with how we do it in the rhel.yml
- Added Docker to Playbook
- Nagios - disabled it as there is not playbook for it right now
- Supperuser - Added 'when: Superuser_Account == "Enabled"' 
- Updated how we check for swapfile already exists
- Updated creation of swapfile to use DD as fallocate fails
- Added NVidia Cuda Toolkit
- Removed doubled up build_tools: libXrender-devel, libXt-devel, libXtst-devel
- Added additional build …

CentOS - Rewrite / Ubuntu - Updated list of supported OS/Arch's

---

ansible/playbooks/ubuntu.yml

This change broke the playbook for all archs other than x86
https://github.com/AdoptOpenJDK/openjdk-infrastructure/commit/75195f8750abbf18869220ac5f84633bf3cc5e58
GPG error occurs while executing apt-get after "Add the azul repository to apt" was added to the playbook.
Issue: Azul Zulu's GPG key needs to be appiled to the instance.
Solution:
Add:
- name: Add Azul Zulu GPG Package Signing Key
apt_key:
url: http://repos.azulsystems.com/RPM-GPG-KEY-azulsystems
state: present
Remove: zulu-9-amd64 from main build_tools
Add:
- name: Install zulu-9-amd64
apt: pkg={{ item }} state=latest
with_items:
- zulu-9-amd64
when:
- ansible_architecture == "x86_64"
tags: build_tools

Fixed issues caused by azul repository

---

ansible/playbooks/windows.yml

Cleanup NVidia CUDA toolkit - Windows 10 and Server 2016
using 'file' not 'win_file'
** we need to be more diligent when checking code
and ensure the 'coder' tested it

cuda clean sections - using 'file' not 'win_file'

---

ansible/playbooks/ubuntu.yml

We HAVE to use ccache 3.1.9 so fetching from APT won't work for us hence the manual steps below

Remove CCACHE from APT

---

ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Common/vars/Ubuntu.yml

During #114 I failed to remove 
- g++-4.8
- gcc-4.8
from Build_Tool_Packages which was moved into gcc_compiler

removed gcc g++ 4.8 from Build_Tool_Packages

---

ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/GIT_Source/tasks/main.yml

- Issues have been found when the version of git as only 1 char in the second field
example: git version 2.7.1 would be cut down to 2.7.

change cut to awk

---

ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Common/vars/Ubuntu.yml

- Required to build git properly from source
- Tested on ub14,16 x86, ppcle, s390
Fixes Issue #125
Signed-off-by: Adam Brousseau <adam.brousseau@ca.ibm.com>

Add libcurl4-openssl-dev to packages

---

infrastructure.md

Hostnames on the machines themselves don't have "ppcle" in them (They are jck-ubuntu-16-04-[12]) - I have left the table with the name as they are registered in jenkins.

Add PPCLE JCK machines to infrastructure.md

---

ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Common/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Jenkins_User/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Superuser/tasks/main.yml

Depending on how the base OS was setup/provided to us, a system wide password policy maybe in effect that could expire these user accounts. (example: force change of password ever 90 days) 
These changes to the 'expire date' and 'max days' will prevent this from occuring.

Ensure root, Jenkins User and Superuser accounts never expires

---

ansible/playbooks/ubuntu-jckservices.yml

Executes `iptables-save` after setting the firewall rules so they survive the machine being restarted

Ensure iptables changes are made permanently

---

ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Common/tasks/Ubuntu.yml
ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Common/vars/Ubuntu.yml

Was unable to test it using the vagrant/ansible box. The location of the Ubuntu.yml ansible script changed to a new location. 
README.md was amended during the process.
Currently unable to run the command:
```
ansible-playbook -i hosts -s AdoptOpenJDK_Linux_Playbook/roles/Common/tasks/Ubuntu.yml 
``` 
from inside the vagrant box.
There should be a straight-forward way to run this playbook in your local environment.

Added mercurial program to be installed on Ubuntu box via the respective ansible script

---

ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Common/tasks/Ubuntu.yml
ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Common/vars/Ubuntu.yml
ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/ccache/tasks/main.yml

moved pulseaudio to its own section - failures seen on arm7l
Removed unneeded sudo command in ccache

minor updates

---

ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Nagios_Plugins/tasks/nagios_CentOS.yml

Create an Ansible playbook that sets up a CentOS machine ready to be
monitored from Nagios.
CentOS is derived from RedHat, so the playbook is a copy of the RedHat
playbook nagios_RedHat.yml, with some minor changes.

#89 Add Ansible playbook to set up  CentOS machine for Nagios monitoring

---

ansible/playbooks/ubuntu-jck.yml

Still tempted to just remove this section and leave the starting of it to the person running it (The scripts in the repository will do that if it's not already running) but the Xvfb seems to need to be more than the default 8 bit depth in order for the JCK UI tests to pass on non-x86 platforms.

Start Xvfb with 24-bit screen depth

---

infrastructure.md

Fixes #189.
The IP address listed for machine build-joyent-x64-ubuntu-16-04-2 is currently listed as 37.153.108.194. This is not correct. Changed it to 37.153.109.201.

Correct the IP address listed for machine build-joyent-x64-ubuntu-16-04-2

---

infrastructure.md

Machine build-joyent-x64-ubuntu-16.04-1 no longer exists. This pull request deletes it from infrastructure.md.

Deletes build-joyent-x64-ubuntu-16.04-1 from infrastructure.md

---

.gitignore
ansible/ansible.cfg
ansible/inventory.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/group_vars/all/adoptopenjdk_variables.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Debug/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Master_Config/tasks/main.yml
ansible/plugins/filter/filters.py
ansible/plugins/inventory/adoptopenjdk_yaml.py
ansible/plugins/inventory/host_vars/README.md
ansible/plugins/library/ssh_config.py

So I have used some of the fantastic code written at https://github.com/nodejs/build to setup an inventory based system. The key thing to this is that the backend python does some pretty clever stuff. You can see the inventory [here](https://github.com/gdams/openjdk-infrastructure/blob/inventory/ansible/inventory.yml).
```yaml
hosts:
- build:
- cloudcone:
ubuntu1604-x64-1: {ip: 173.82.219.221}
```
Becomes `build-cloudcone-ubuntu1604-x64-1`
And this in turn means that the ansible variables are a bit more useful:
```bash
ok: [build-cloudcone-ubuntu1604-x64-1] => {
"msg": [
"inventory_hostname: build-cloudcone-ubuntu1604-x64-1 ", 
"ansible_hostname: build-cloudcone-x64-ubuntu-16-04-1", 
"ansible_ssh_private_key_file: ~/.ssh/id_rsa", 
"ansible_fqdn: …
```

Initial attempt at formatting hostnames/inventory

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/GIT_Source/tasks/main.yml

The check fails on freebsd
```
root@build-packet-freebsd11-x64-1:~ # git --version >/dev/null | sed -e 's/git version //g' | awk -F'[.]' '{print $1 "." $2}'
Ambiguous output redirect.
```
changing it to the below fixes things
```
root@build-packet-freebsd11-x64-1:~ # git --version | sed -e 's/git version //g' | awk -F'[.]' '{print $1 "." $2}'
2.15
```

freebsd tweak

---

ansible/inventory.yml

keybox has been switched to use root now so linux1 is no longer needed

switch s390x to use root rather that linux1

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_Ubuntu.yml

I have added `aarch64` to the nagios setup. I have checked that there is nothing that the ubuntu aarch64 machines cannot do in the playbook so we should be all good

include aarch64 in nagios

---

ansible/inventory.yml

We use box number as a jump box to number 2 (we only have 1 external IP). This also gives us a chance to fixup any bugs with centos7 on aarch64 which I don't believe that we have ever run the playbook against

add linaro aarch64 machines

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml

- package installs permit inclusion of an ubuntu machine to jck testing

Add xvfb and acl to playbooks

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml

- The way the 'hosts' module is currently configured would force others to use the same naming convention as AdoptOpenJDK build/test-vendor-xxx-arch-num
- Changed hosts to allow for Vendor groups
- (*Ansible's hosts module doesn't allow for the use of loops/with_items)
```yml
from:
- hosts:
- build		
- test		
- "!*zos*"		
- "!*win*"		
- "!*macos*"		
- "!*aix*"
to:
- hosts: "{{ groups['Vendor_groups'] | default('build:test:!*zos*:!*win*:!*macos*:!*aix*') }}"
```
Thus if 'Vendor_groups' is not found it will default to the standard limits

Change hosts to allow for Vendor groups

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/SLES.yml

This pull request satisfies the SLES requirement of issue #184.
Xvfb on SLES is provided by the `xorg-x11-server-extra` package.

Added xorg-x11-server-extra to SLES test tool package

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/main.yml

- Removed ```backup: yes```, this creates unnecessary backup files, one everytime the playbook is run on the system. 
The following was added to allow for alternative inventory methods
- Added ```when: Domain == "adoptopenjdk.net"``` to ```Set hostname to inventory_hostname```
- Added ```when: Domain == "adoptopenjdk.net"``` to ```Update /etc/hosts file - IP FQDN hostname```
- Added task ```Update /etc/hosts file - IP FQDN hostname (Domain != "adoptopenjdk.net")``` with when ``` Domain != "adoptopenjdk.net" ```

Allow alternative inventory methods

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml

- OpenJ9 needs this lib in order to compile on x86 RHEL7

Move libstdc++-static from only ppc64le to all arch

---

ansible/playbooks/aix.yml

This was missing on both AIX machines and is needed to build openjdk10

Add fontconfig-devel to aix

---

ansible/inventory.yml
ansible/playbooks/AdoptOpenJDK_Services_Playbooks/ubuntu-api.yml
ansible/playbooks/AdoptOpenJDK_Services_Playbooks/ubuntu-jckservices.yml
ansible/playbooks/AdoptOpenJDK_Services_Playbooks/variables/adoptopenjdk_variables.yml
ansible/plugins/inventory/adoptopenjdk_yaml.py

This PR adds a playbook to recreate the api server. I have also added a new section to the inventory called `service` which is where all of the service machines will be stored

add api setup playbook

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml

* zulu java9 causes intermittant failures for jenkins clients when using Xvfb

Add java8 as default java on ubuntu16 x86 machines

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/OracleLinux.yml

Adding add-xvfb-to-oraclelinux because that's what's used on RHEL, which this o/s is based on.

Added xorg-x11-server-Xvfb

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml

- We were missing `unzip`
- Added RedHat's `ant-contrib`
Related to issue #269

Added additional tools

---

ansible/playbooks/ubuntu-jck.yml

From @lumpfish
_One of the JCK tests requires that I drag and drop some text out of the JCK GUI and paste into a native application.  The JCK machine doesn't appear to have gedit installed.  Anyone have another suggestion?_

Add xterm/gedit/gnome-terminal to playbook to support JCK interactives

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/GIT_Source/tasks/main.yml

Ensure curl-devel is installed on RHEL 6 before compiling git
Ref issue #299

Ensure curl-devel is installed on RHEL 6

---

ansible/playbooks/aix.yml

- Added `libiconv` as its required by `libunistring`
- Added `ulimit` settings to address `out of memory` issues in `cpan`
- Changed link to download `ant` to use apache's archive site as the main site will change
- Added title (name) to `stat` command
- `Uninstall conflicting packages` -- added `ignore_errors: True` so that it doesn't fail if none of these packages are installed
- After Perl 24 is installed, update symlink, this prevents failure from cpan when it finds perl 20

Aix playlist revisions

---

ansible/playbooks/ubuntu-jck.yml

Added `gv` and `printer-driver-cups-pdf` to the list of prerequisite packages.
Answers issue #307.

Added printer-driver-cups-pdf and gv to the JCK playbook

---

ansible/README.md

I was reading through this, and was confused by what the vagrant box is used for. I'd expected to be running `ansible-playbook` commands on my dev machine, and for ansible to connect to the VM to run the tasks.
I tried to emphasize this, and tried to make the formatting a bit nicer in the process.
cc/ @gdams @bblondin 
I assume when the playbooks are actually used, they're usually run on the dev's machine, and connect to remote hosts to run commands. If so it would probably make sense to do the same thing when testing with vagrant.

Formatting in the ansible readme

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/SLES.yml

This package is required on zLinux to enable OpenJDK to find
freetype without patching, as it changes the locations we search
for freetype to include the default location.
Tried contributing the patch so we search the *right* locations
for freetype, but OpenJDK has chosen not to accept this.
Signed-off-by: Adam Farley <adam.farley@uk.ibm.com>

WIP: Adding pkg-config into the ansible playbooks

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml

* enable anyone to be able to run on a single machine without
* Ansible Tower installed or the use of a inventory file.

Add ability to run ansible on a specific machine

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2010/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2013/tasks/main.yml

OpenJ9 uses the ddrgen tool from OMR; that tool depends on msdia100.dll which must be registered. This change arranges that both the 32-bit and 64-bit variants are registered as part of installing Visual Studio 2010.

Register Visual Studio DIA SDK shared libraries

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_48/tasks/main.yml

Fixes for gcc 4.8.5:
- install libmpc-devel package instead of building mpc from source
- install 32 bits glibc package
- add c++ symlink
- add libstdc++.so.6.0.19 symlink
Move dwarf and elf packages to build tools
Add ant-apache-regexp package to test tools

Updates for RHEL6

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml

* OpenJ9 sanity testing has a requirement on having this module installed

Add HiRes Time perl module to CentOS

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2017/tasks/main.yml

The changes are to install VS2017 so as to compile
JDK11 on Windows.
Signed-off-by: CHENGJin <jincheng@ca.ibm.com>

Update Ansible script to install VS2017 for JDK11

---

ansible/playbooks/aix.yml

Installing the CSV package as root should install to the default folders of 
/opt/freeware/lib/perl5/site_perl/5.24.0/ppc-aix-thread-multi
/opt/freeware/lib/perl5/site_perl/5.24.0
/opt/freeware/lib/perl5/5.24.0/ppc-aix-thread-multi
/opt/freeware/lib/perl5/5.24.0
But I have seen setups where a logged on user isn't getting those directories in their search path.
`Can't locate Text/CSV.pm in @INC (you may need to install the Text::CSV module)...` 
Setting the installation location and then the export of PERL5LIB resolves this issue.

Add user directory for perl module to search path

---

ansible/inventory.yml

Machine has been reinstalled as per https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/396

Replace sles12-s390x-1 build box with rhel74-s390x-2

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/RedHat.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml

The glibc-devel.i686 package shouldn't be installed in the common Build_Tool_Packages section because it doesn't apply to non-x86 architectures, so have moved it into a new Additional_Build_Tools_RHEL_x86_64 section for x86_64 only.
Fixes [issue #446](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/446)

don't install glibc-devel.i686 on non-x86 architectures

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/autoconf/tasks/main.yml

rc check is done even when the version check operation was skipped on the platform. This re-orders the check until after the distribution check is done. This is blocking x/z Linux playbook executions which are on RHEL7 machines
```
TASK [autoconf : Test if Autoconf v2.69 is installed] **************************
14:19:22
skipping: [build-osuosl-centos74-ppc64le-2]
TASK [autoconf : Download Autoconf v2.69] **************************************
14:19:22
fatal: [build-osuosl-centos74-ppc64le-2]: FAILED! => {"failed": true, "msg": "The conditional check '((autoconf_version.rc == 0) and (autoconf_version.stdout | version_compare('2.69', operator='lt')))' failed. The error was: error while evaluating conditional (((autoconf_version.rc == 0) and (autoconf_version.stdout | version_compare('2.69', …
```

ansible: autoconf role is failing when not on RHEL6

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_7/tasks/main.yml

This is the same issue we had for autoconf. We need to do the OS checks before the rc checks otherwise we will be trying to use `gcc7_installed` on OSs other than RedHat/CentOS where the check isn't executed. This is causing all Ubuntu-based systems to fail to deploy the Unix playbook successfully

ansible: Don't check for gcc7_installed.rc if we haven't set it

---

ansible/inventory.yml

We should likely consider whether to keep the machine around (assuming it's even assigned to us) but at the moment ansible is not able to communicate with it and we are not currently building anything on FreeBSD. We can regenerate the machines if required int he future.

inventory: Remove unused build-packet-freebsd11-x64-1

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/autoconf/tasks/main.yml

This reverts commit 97323e925ee35c00220474e1574183e2db780db5.
Pushing this through as it is not working on our AWX server (although it does work with my local ansible 2.6.3)
```
TASK [autoconf : Download Autoconf v2.69] **************************************
14:24:43
fatal: [build-joyent-centos69-x64-1]: FAILED! => {"failed": true, "msg": "The conditional check '((autoconf_version.stdout == '') or ((autoconf_version.stdout != '') and (autoconf_version.stdout is version('2.69', operator='lt', strict=True))))' failed. The error was: template error while templating string: no test named 'version'. String: {% if ((autoconf_version.stdout == '') or ((autoconf_version.stdout != '') and (autoconf_version.stdout is version('2.69', operator='lt', strict=True)))) %} True {% else %} False {% endif …
```

Revert "Fix conditional for autoconf version check (#443)"

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml

Unblocks https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/408 and is a prereq for https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/256

ansible: Add libstdc++-static on CentOS (already on RedHat)

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/7-Zip/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MinGW-W64/tasks/main.yml

- install 7zip
- install MinGW from a 7zip package

WIP: Install MinGW-W64 on Windows

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Firefox/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml

This add a couple of steps to Cygwin role to download grep 2.27 and install it (overwrite since cygwin doesn't allow us to downgrade a package unattended).
Fixes #384.

Downgrade grep to 2.27

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/GIT_Source/tasks/main.yml

- Installing to /usr/bin/git seems to be
causing issues when yum updates and
overwrites this version back to default.
- Install to /usr/local/bin/git instead.
- This is on the PATH before /usr/bin
- Tested on rhel7 ppc64le.

Install git to /usr/local to avoid package manager collision

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/ccache/tasks/main.yml

To be honest, this method of checking if it's installed by seeing if `~jenkins/ccache-3.x.z` is present is a terrible idea, but I feel this isn't the only product not doing a proper version check so I'll leave it for now and overhaul everything later.

Update ccache to 3.4.2 (For compatibility with gcc 7)

---

.travis.yml
ansible/playbooks/AdoptOpenJDK_Services_Playbooks/ubuntu-api.yml
ansible/playbooks/AdoptOpenJDK_Services_Playbooks/ubuntu-jckservices.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/CPAN/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/GIT_Source/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Jenkins_User/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NTP_TIME/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NVidia_Cuda_Toolkit/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Swap_File/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk9/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/cmake/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_48/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/x11/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml
ansible/playbooks/aix.yml
ansible/playbooks/nagios/nagios_aix.yml
ansible/playbooks/ubuntu-jck.yml
ansible/yamllint.yml
yamllint.yml

This one adds Ansible-lint to the build pipeline.
Both YAMLLint and Ansible-lint are prerequisites for the `Molecule` automated testing system.
* Added ansible-linting to Travis build
* Fixed simple and unambigious issues, such as using `shell` instead of `command` and missing task names.
* For all the other cases added `skip_ansible_lint` tag and added TODO comments.
* Removed the duplicated yamllint.yml file and increased the line length threshold from 80 to 120.
Most unresolved Anslible-lint issues relate to the places in code that are just 'ansibilized' shell scripts, without guaranteed idempotency and usage of respecting Ansible modules.
Deeper refactoring is possible, but, as any refactoring, it requires the automated tests. 
The further steps could be adding `molecule` testing to …

Add Ansible-lint to the build pipeline

---

README.md

Going to need to remove all his keys etc. but this is a partial fix for https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/524

Remove bblondin from infrastructure team

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/OpenSSL/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Protobuf/tasks/main.yml

Required by OpenJ9 for JITasS (out-of-process JIT compilation)
Issue: #493

Add Protobuf and OpenSSL 1.1.0g to Linux x86

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/ccache/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/nasm/tasks/main.yml

* also update ccache role to use /tmp as workspace as is
standard in other roles

Add steps for cleanup of artifacts for nasm and ccache

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml

The library is used by git-http-fetch, git-fetch.

Add libcurl-devel package for CentOS

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/ANT/tasks/main.yml

1.10.3 is missing, used the same url as in the Unix playbook.
This issue came up when installing on windows 2012.
#553

Changed url of apache ant binaries

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/ANT/tasks/main.yml

The ant url was changed but forgot to update 1.10.3 to 1.10.5 when
testing if ant was already installed ([see PR](https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/556)). Also added /m when declaring
ANT_HOME so the variable will be set at the system level.

Fixed bugs in ANT windows role

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/OpenSSL/tasks/main.yml

OpenSSL is required to compile java on windows, so the OpenSSL role will
ensure the 32bit and 64bit versions are both installed into C:\openjdk

Install OpenSSL in windows playbook

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Freetype/tasks/main.yml

JDK8 compile will fail unless freetype is built beforehand, so these changes
will build freetype 32bit and 64bit versions inside C:\openjdk\freetype-2.5.3
Fixes #367 

Adding to Freetype windows role

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gmake/tasks/main.yml

Same reasoning as https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/576 - it causes the playbooks to fail :-\

Dont replace usrbingmake

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/nasm/tasks/main.yml

Windows playbook will now install nasm-2.13.03 into C:\openjdk

Added nasm role to Windows playbook

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml

This will make them a bit closer. Diff now as follows, bit it means common packages are listed in the same places in both files after this PR. Fixes https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/498 - I've removed `expat-devel` as I've no idea why it was in there (@smlambert if you know, shout now!) and it wasn't in the CentOS playbook (We use CentOS build machines on x64 and ppc64le without problems...), so if there's a problem we'll see it at some point in the future.
```
[sxa@sxat470p vars]$ diff CentOS.yml RedHat.yml
3c3
< # CentOS #
---
> # RedHat #
11a12
>   - bzip2
26,27d26
<   - java-1.7.0-openjdk-devel
<   - java-1.8.0-openjdk-devel
29a29,30
>   - libffi-devel
>   - libmpc-devel
34d34
<   - lbzip2
38d37
<   - numactl-devel
42d40
<   - perl-DBI
44,46c42
<   - …
```

Sync RedHat/CentOS ansible definitions

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml

OpenJFX prereqs won't be needed by most people, therefore have those sections tagged appropriately so they can be exlcuded with `--skip-tags`
Should assist with https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/532

ansible: Add tag to openjfx prereqs so can be excluded

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml

Required for https://github.com/AdoptOpenJDK/openjdk-build/pull/758

ansible: Add libpng-devel to CentOS/RHEL (required for freetype build)

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gmake/tasks/main.yml

No longer needed after https://github.com/AdoptOpenJDK/openjdk-build/pull/759 is been committed (I hope)
This pretty much repeats https://github.com/AdoptOpenJDK/openjdk-infrastructure/commit/19b3c388e828229ebffcb39610b767458ec5f6c9#diff-b21149752cf9be3ad357fc6cdd81cc9c with a better solution after that was backed out again ...

ansible: Stop symlinking new make to /usr/bin

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk10/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk11/tasks/main.yml

Puts correct change into s390x section of the adoptopenjdk11 setup (Now matches the comment)
Fixes https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/594

ansible: Switch adoptopenjdk11 role to install OpenJ9 on s390x

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml

Docker will now be installed on ubuntu (x86_64/s390x/ppc64le), RHEL7 (x86_64/s390x/
ppc64le), cent7 (x86_64/s390x/ppc64le), and SLES12 (x86_64). Formerly docker was
only installed on these operating systems on x86_64.
Related to #347 

Added s390x and ppc64le arch to docker role

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Ant-Contrib/tasks/main.yml

Part of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/607, supercedes https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/611 #CanOfWorms #YakShaving :-)
Spoke to @smlambert who says this isn't needed, and it's causing a failure. If needed again Junit 4.1 can be installed from the SLES12 zypper repo.
```
build-marist-sles12-s390x-1:/tmp # zypper --non-interactive install --type package --auto-agree-with-licenses --no-recommends -- /tmp/junit-3.8.2-8.1.noarch.rpm
Refreshing service 'SMT-http_lxslsmt'.
Loading repository data...
Reading installed packages...
Resolving package dependencies...
The following NEW package is going to be installed:
junit
The following package has no support information from it's vendor:
junit
1 new package to install.
Overall download …
```

ansible: Remove junit install on SLES as test team does not require it

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml

Docker will not be installed on cent/rhel 7 for s390x and
ppc64le, because on these operating systems, docker is only
supported for x86_64.
Fixes #615

Updated docker install in unix playbook

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Windows_Updates/tasks/main.yml

Ansible thinks the when statement is a part of the
win_reboot module, and the register statement is a
part of the win_updates module causing errors. Removed
spaces so when and register statements will work. Removed
shutdown_timeout as it is deprecated

Updated Windows_Updates role

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml

Cygwin will now be added to the system path instead of
the User path.

Updated cygwin role

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/7-Zip/tasks/main.yml

7-zip role was not being executed by ansible, so tasks
directory was created and main.yml moved inside. Added
the /S option to the 7-zip installation so it wouldn't
hang waiting for input.

Fixed 7-zip role

---

ansible/playbooks/aix.yml

- Pull latest OpenJ9 release from Adopt via website API
- Install in /usr/java11_64
Issue #594

Add Bootjdk11 to AIX playbook

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Clang_32bit/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Clang_64bit/tasks/main.yml

The changes are to install LLVM/Clang so as to 
compile JDK 8 & JDK 11 on Windows.
Signed-off-by: CHENGJin <jincheng@ca.ibm.com>

Update Ansible script to install Clang on Windows

---

.travis.yml

Specified the versions of linters -- to avoid unexpected build failures because of linters' updates

Specified versions of Yamllint and AnsibleLint (fix #641)

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Clang_32bit/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Clang_64bit/tasks/main.yml

* remove erroneous whitespace that caused playbook errors
* remove trailing  `\` in symlink target directories causing playbook errors
* fix syntax error when unzipping llvm 32bit
Signed-off-by: Husain Yusufali husainyusufali7@gmail.com

Clang_32bit and Clang_64bit syntax fixes

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java11/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java7/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java8/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java9/tasks/main.yml

* remove trailing backslashes from Java 7, 8, 9, 11 symlinks
* found an incorrect symlink in Java 9 while testing
* Java 9 symlink has been fixed to point to correct location  
Signed-off-by: Husain Yusufali husainyusufali7@gmail.com

Remove trailing backslashes from Java roles in Windows Playbook

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/7-Zip/tasks/main.yml

* Change the 7-Zip installation directory by adding an argument
* Tested to make sure installation directory is `C:\7-Zip` and playbook will skip installation if 7-Zip is already is installed 
* Fixes pull request #644 

ansible: Changing 7-Zip installation directory in Windows Playbook

---

ansible/Vagrantfile

This will move the image up from 14.04 (which isn't our main platform) to 16.04 and also use an image that will work with providers other than VirtualBox (generic/ubuntu1604 supports):
- hyperv
- libvirt
- parallels
- virtualbox
- vmware_desktop
Explicit entry for /vagrant is because it wasn't working for me by default
Reviewers: PLEASE test this on your setup and let me know if it works (especially the `/vagrant` mount) and whether it causes regressions compared to the previous image - I'm going to leave this as WIP for at least a few days until I'm confident it doesn't break anything.

Switch Vagrant file from using ubuntu/trusty64 to generic/ubuntu1604

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Jenkins_User/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Master_Config/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_CentOS.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_FreeBSD.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_RedHat.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_SLES.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_Ubuntu.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Tunnel/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Security/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Superuser/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/freemarker/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/x11/tasks/main.yml

Fixes https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/532 https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/626
May remove the x11 role entirely is it's not persistent ... But for now this will stop "normal" people having to exclude a billion tags to make the playbooks work, after this change `--skip-tags=adoptopenjdk,test_tools` on the `ansible-playbook` command should be enough

ansible: Linux: Add 'adoptopenjdk' tag to make exclusions easier

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java9/tasks/main.yml

* Change Java 9 download and extracted file name to satisfy the test cases and match symlink functions that were changed in PR #652  
* Test cases work correctly and do not reinstall or download Java if it is already installed or downloaded
* Has been tested on clean VM to verify changes made work

ansible: Fix Java 9 test cases

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/NVidia_Cuda_Toolkit/tasks/main.yml

* Errors were caused due to using `file` module instead of  the `win_file` module
* Testing cleans downloaded files and allows playbooks to pass

Ansible: NVidia Toolkit Role, Fix syntax of cleanup task

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml

* Add the name of the environment variable
* Make sure that the PATH is available on the entire machine's users instead of just the Administrator user
* This change gets rid of an error when the cygwin path portion of the playbook is rerun against a machine

Ansible: Change the syntax of removing and adding cygwin to PATH

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/cmake/tasks/main.yml

We are installing 3.11.4 for OpenJFX, but that version is a bit of a pain to install on RHEL6.9, therefore we should tolerate having 3.7.2 for now, but install 3.11.4 for now unless it can be proven
that OpenJFX can't be built with 3.7.2.

Don't upgrade cmake if it's already at 3.7.2

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml

- <s>Checking if docker is installed task was not working correctly</s>
- <s>New command uses `docker version` command to check if it is installed</s>
- Remove `docker_installed` check from `Add Jenkins user to the docker group` task as it's not required
- Add `s390x` and `ppcle64` architectures to RHEL, CENT, and SLES docker tasks
@jdekonin 

Ansible: Add s390x and ppcle64 to RHEL, CENT, and SLES docker tasks

---

ansible/playbooks/adoptopenjdk_variables.yml
ansible/playbooks/aix.yml

- When using the AIX playbook, Java 8 & 9 by default is the hotspot jdk
- If OpenJ9 Java 8 & 9 are to be installed instead of hotspot the extra variable `bootjdk = openj9` must be specified at runtime
- Issue #708 
fyi @jdekonin 

Add hotspot jdk and openj9 parameter to AIX

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Rust/tasks/main.yml

Rust is required to compile IcedTea-Web. The Rust role will
ensure that Rust is installed and on the path.
Signed-off-by: Charlie Gracie <charlie.gracie@gmail.com>

Install Rust in Windows playbook

---

ansible/playbooks/aix.yml

- Removed redundant installation of JDK 11
fyi @jdekonin 

Ansible: Remove duplicate jdk11 task on aix

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Rust/tasks/main.yml

The IcedTea-Web makefiles can not handle the default installer
path for Rust. The path appears to not be able to have spaces in
it. This change installs rust in `c:\rust' instead of the default.
Signed-off-by: Charlie Gracie <charlie.gracie@gmail.com>

Modify the install location of Rust

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml

Spotted the windows playbook trying to install the X11 packages under cygwin (xinit, xorg-server, xterm) but after looking at https://github.com/search?q=org%3AAdoptOpenJDK+xinit&type=Issues and after discussions with @smlambert we cannot see any reason why they are required therefore I am removing them for now. If this turns out to be a mistake, we can re-enable it with a suitable explanatory comment.

Remove X11 packages from Windows playbook

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk9/tasks/main.yml

Some machines have the adoptopenjdk9 code in `/usr/lib/jvm/jdk-9+191` which is not being correctly by the playbooks which are looking for `/usr/lib/jvm/jdk-9.*` ... We could either replace the `.` with `[.+]` or just trap any case by looking for `jdk-9*` which is what I've done in this PR

ansible: handle jdk9 in either jdk-9+191 or jdk-9.0.4 path

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk10/tasks/main.yml

https://adoptopenjdk.net/archive.html?variant=openjdk10&jvmVariant=hotspot has no download for JDK10 on Linux/ppc64le so adjusting the playbooks to install the openj9 version

ansible: Install OpenJ9 JDK10 on Linux/ppc64le

---

ansible/playbooks/aix.yml

- correct some comments
- alternate users to the system should not require access to another /home directory

Install perl modules to system generic location on aix

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/group_vars/all/adoptopenjdk_variables.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java11/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java8/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java9/tasks/main.yml

This pull request fixes issue #715 
* Add bootjdk variable to adoptopenjdk_variables.yml
* Load adoptopenjdk_variables.yml into the main.yml file
* Change hard link to API when downloading Windows JDK
* API downloads the latest Windows hotspot or openj9 jdk for Java[8,9,11]
* Remove versions from test cases and zip files as they can change across playbook deployments
* Powershell commands that create persistent environment variable of Java folder that is installed
* Create symlink using environment variable
* NOTE: win_shell module acts differently when creating environmental variable vs creating a symlink
fyi @jdekonin

Ansible: Add bootjdk variable to install hotspot or openj9 on Windows

---

ansible/playbooks/aix.yml

* OpenJ9 JDK12 tasks added to aix.yml
* There is no option to install hotspot JDK12 on aix
Resolves issue #710

Ansible: Add OpenJ9 JDK12 to aix playbook

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk9/tasks/main.yml

We don't have an arm32 JDK9 available to download, therefore this will stop the playbook aborting when it can't access the directory it expects to find it.
Without it, this is the failure:
```
TASK [adoptopenjdk9 : Check if jdk9 is already installed in the target location] ***
19:18:14
fatal: [build-scaleway-ubuntu1604-armv7-2]: FAILED! => {"changed": true, "cmd": "ls -ld /usr/lib/jvm/jdk-9* >/dev/null 2>&1", "delta": "0:00:00.028071", "end": "2019-04-02 18:18:15.722551", "failed": true, "msg": "non-zero return code", "rc": 2, "start": "2019-04-02 18:18:15.694480", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
...ignoring
TASK [adoptopenjdk9 : Install latest release if one not already installed] *****
19:18:15
skipping: [build-scaleway-ubuntu1604-armv7-2]
TASK …
```

Ansible: Stop playbook failing on adoptopenjdk9 role on arm32

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/GIT_Source/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Version/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/curl/tasks/main.yml

ansible 2.5.1 (included in Ubuntu 18.04) throws the following warnings at various steps. This PR will remove those warnings:
`[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using 'result|version_compare' instead use 'result is version_compare'. This feature will be removed in version 2.9.`
~~Need to validate that our AWX server is using a version of ansible that won't object to this - the [ansible 2.4 docs](https://docs.ansible.com/ansible) (we test for that as a minimum) does show the old format:~~ EDIT: Our AWX uses 2.4.3.0 and it works with the updated syntax so this change should be safe.

Remove version_compare deprecation warnings from UNIX Playbooks

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Freetype/tasks/main.yml

This reverts commit 0628f935dccbc37a2ffdde135ec5222ce43b1828.
@jdekonin @karianna this PR reverts #766. 
Is it ok if we remove `freetype` from `main.yml` but leave the role definition?

Revert "Remove freetype from windows playbook (#766)"

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/OpenSSL102/tasks/main.yml

This can be downloaded live, but I'd rather have it cached. CentOS6 (used on x64 for building) has openssl 1.0.1 which cannot be used by OpenJ9.
Separate PR in to the build repository to start using this https://github.com/AdoptOpenJDK/openjdk-build/pull/1023

Add OpenSSL 1.0.2 prereq on CentOS/RHEL6 for OpenJ9

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Protobuf/tasks/main.yml

This role optional. 
Remove role from top main.yml.
To add the role include Protobuf role to the top main.yml.

Add protobuf libraries to the linker search path

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Python3_Source/tasks/main.yml

* Install Python 3.7.3 to Unix Playbook
* Installs from source to Redhat, CentOS, Ubuntu, and SLES
* The following issues require python3 to satisfy the JitBuilder Python dependency:
* eclipse/omr#2397
* eclipse/omr#2915
* eclipse/omr#2968
fyi @jdekonin @vsebe 
Signed-off-by: HusainYusufali husainyusufali7@gmail.com

Ansible: Install Python 3.7.3 to Unix Playbook

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml

This should fix the issue caused by the entry with an erroneous `"` mark in the SQL Server PATH that causes `SETX` to get very confused resulting in this error:
```
TASK [cygwin : Add c:\cygwin64\bin to front of %PATH%] *************************
fatal: [40.121.164.56]: FAILED! => {"changed": true, "cmd": "setx /M PATH \"C:\\cygwin64\\bin;%PATH%\"", "delta": "0:00:00.125003", "end": "2019-05-28 03:32:41.392060", "msg": "non-zero return code", "rc": 1, "start": "2019-05-28 03:32:41.267057", "stderr": "ERROR: Invalid syntax. Default option is not allowed more than '2' time(s).\r\nType \"SETX /?\" for usage.\r\n", "stderr_lines": ["ERROR: Invalid syntax. Default option is not allowed more than '2' time(s).", "Type \"SETX /?\" for usage."], "stdout": "", "stdout_lines": []}
to retry, use: …
```

Fix problem setting PATH with erroneous quote in SQLServer path

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java11/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java12/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java8/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java9/tasks/main.yml

Switch java symlink creation to use CMD to avoid PS upgrade

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml

Without this extra dependency the `XML::Parser` role fails as it cannot locate the `expat.h` header file

Add expat_devel on RHEL/CentOS (dep of CPAN XML::Parser)

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_48/tasks/main.yml

Build is missing a step. Surprised this wasn't spotted previously but I guess few people are using RHEL6 :-)

Add download_prerequisites to RHEL6/GCC48 build

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml

Variable name in the task doesn't match the definition

Fix variable name for Ubuntu/s390x build tools

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/cmake/tasks/main.yml

Without this fix you get this error on RHEL6 with onluy GCC 4.4.7 available:
```
Error when bootstrapping CMake:", "Cannot find a C++ compiler supporting C++11 on this system.", "Please specify one using environment variable CXX
```

Ensure GCC4.8 is available before building cmake (Requires C++11)

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Protobuf/tasks/main.yml

Compile Protobuf with -fPIC floag to ensure shared and static libraries
are PIC-enabled. OpenJ9 used to dynamically link with the version of
protobuf available on the system.
eclipse/openj9#6091 changes to statically link.
Issue: https://github.com/eclipse/openj9/issues/6092

Set C/C++ flags for Protobuf

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/RedHat.yml

* fix conditional such that openjdk7/8 are installed
* correct alternative for x86 as its openjdk and not the ibm
package that installed
* #807

Fixes to permit Redhat6 on x86 to apply cleanly

---

ansible/README.md

Adding a quick-start guide for macOS in the /ansible/README.md allows for quickly installing programmes that are required to test the playbooks.

Adding quickstart guide to readme

---

ansible/MANUAL_STEPS.md
ansible/inventory.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/CPAN/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/scripts/install-homebrew.sh
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/scripts/install-xcode.sh
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/MacOSX.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/MacOSX.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Jenkins_User/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Superuser/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/ant/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/freemarker/tasks/main.yml
ansible/yamllint.yml

This adds the initial macOS playbooks for test machines. It's probably missing build deps but we'll get to that when we add a new build mac.

add mac playbooks and new macincloud test machines

---

ansible/inventory.yml

Introduced in https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/824
I still think my version looks better - seems a bit overkill not to allow an extra space after the : to line the entries up

fix linter problem in inventory.yml (but makes it less pretty)

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml

Fixes the key signing problem for Azul on the Ubuntu Playbook by swapping 2 of the tasks.
Fixes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/836

Fixed Azul signing keys for Ubuntu

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml

Found an issue whilst fixing #836 , the libgstreamer package was attempting to download an Ubuntu 16.04 version, whilst using an 18.04 VM. Just removed a couple lines, as it's installed later on anyway.

Stopped libgstreamer Issue with Ubuntu 1804

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml

Found another issue when fixing #836 , the Task "Add Docker repo for Ubuntu x86_64" would fail when executing the Ubuntu playbook on Ubuntu 18.04, but not on ubuntu 16.04. I've added the task to get the GPG key before adding this repo. This appears to have fixed the problem for Ubuntu 18.04, whilst not breaking anything for Ubuntu 16.04

Fixed Docker issue with Ubuntu 1804

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/main.yml

Relates to #341 
The pull request in #573 doesn't seem to have fixed the issue when running on an Ubuntu 16.04 VM. It appears to be a syntax error from reading the files before executing any of them, therefore it will fail before getting to the "version" task in the Unix Playbook. Therefore, I've commented in a message so when this error occurs, it tells the user to update to Ansible >=2.4, as that will fix the issue, and we can't automatically update ansible from within a playbook.

Put in a more useful error message for Ansible's version check

---

ansible/pbTestScripts/README.md
ansible/pbTestScripts/testScript.sh
ansible/pbTestScripts/vmDestroy.sh

Added a folder into the "ansible" folder that contains all the scripts (and directions on how to use it). Works by creating 3 Vagrant VMs (For Ubuntu 18, 16 and CentOS6), logging all the ansible-playbook command output and searching it to determine if it works or not. Then you can destroy the VMs, or not, if they're needed for more debugging.
Fixes: #842

Added scripts for testing the Unix PBs

---

ansible/playbooks/aix.yml

Running the playbooks on AIX is currently causing a yum breakage due to `python-pycurl` being upgraded and it being incompatible with `curl`. We have an entry in the playbook to stop `curl` being upgraded. This PR will stop `python-pycurl` being upgraded too.
We may need to revisit why curl is being excluded and see if we can reinstate it, but this will at least stop terminally breaking yum (Can be unbroken by force removing python-pycurl and reinstalling the one in the AIX toolbox download ...)
```
There was a problem importing one of the Python modules
required to run yum. The error leading to this problem was:
pycurl: libcurl link-time version (7.52.1) is older than compile-time version (7.56.1)
Please install a package which provides this module, or
verify that the module is installed …
```

Allow curl to update in AIX playbook

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/SLES.yml

Fix download link (no secure/https link available).
Add task to compile and install zlib from source on Linux 390 systems.

Install zlib on SLES s390x

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/GIT_Source/tasks/main.yml

Even if a VM didn't have Git installed, the task "Compile and install git from source on everything else" would still be skipped. Turns out Ansible wasn't picking up the `!` , but it does pick up `not` instead.
Fixes #743

Installs GIT correctly now on Unix Playbooks

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/SLES.yml

Modify conditional to allow expat installation on Linux s390x.
Add task for Linux s390x to compile and install expat from source.

Install expat on Linux s390x

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/cmake/tasks/main.yml

On zlinux machines the ansible_processor_vcpus variable isn't defined,
but the ansible_processor_cores variable is. This change will set the
ansible_processor_vcpus variable to equal ansible_processor_cores so
the cmake role won't fail on zlinux.

Changed ansible_processor_vcpus variable for cmake

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/ant/tasks/main.yml

There are two tasks meant for setting up an ant symlink, one for Mac,
and one for other any other OS. Although both tasks have when statements
that specify to only run on MacOS, causing non Mac hosts to not have ant
set up properly. This change fixes the when statement on the task that
sets up a symlink on a non Mac host.

Changed condition of setup of ant symlink

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/MacOSX.yml

install bash v4 or later on macOS

---

ansible/pbTestScripts/buildJDK.sh
ansible/pbTestScripts/testScript.sh

Added into the script that builds the vagrant machines to test the playbooks, the scripts to run and build openJDk on the machines, to ensure the ansible playbook correctly installed everything.

Added/Modified Scripts to verify OpenJDK builds

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/MacOSX.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Jenkins_User/tasks/main.yml

as requested in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/840
I've already run this on all the test mac's but they will need to be disconnected and reconnected in order to have the new umask.

ensure macOS has enough mapped shared memory

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/MacOSX.yml

this was missing on the new 10.12 build machine, needed to speed builds up.

add ccache to macOS playbooks

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/ant/tasks/main.yml

Fixes the playbook failure that occurs when there is no usr/local/bin directory when trying to create a symlink for ant, by checking and subsequently creating the directory if it's not there.
Fixes: #666

Added directory check for the Ant role

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/ccache/tasks/main.yml

I had to do this by using the `shell` module in ansible, which isn't really suggested, hence `warn=False`. Works for now, though could be looked at later.
helps towards: #807

Changed the Unix PB to complete ccache

---

ansible/pbTestScripts/testScript.sh
ansible/pbTestScripts/vmDestroy.sh

Added checks that determine if the URL contains the word "tree". If it does, it makes a note of the branch name, and `git clone`s that single branch to test on. 
Also some small other additions:
- Changed `~` to `$HOME`
- Added CentOS7 to the list of tested OSs.
- Changed `set -eu` to `set -u`, as `-eu` was causing the test script to cancel when failing on a particular OS, without testing the proceeding OSs.

Added checks in PB test script to allow testing of branches

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/group_vars/all/adoptopenjdk_variables.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java11/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java12/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java8/tasks/main.yml

- Heap size variable added to playbook. It defaults to normal
- To change heap size the extra variable must be added when running the playbook
- Playbook tested and still install hotspot with normal heap_size as the default
- Fixes #882 

Add heap size variable for Windows playbook

---

ansible/pbTestScripts/testScript.sh

Fixing bugs that were found when testing another feature.
- Changing the variable "urlSplit" back to "IFS", as IFS is a bash variable that is used to determine the split delimiter when using "read". A comment was also added to explain this.
- Changing an incorrect variable assignment: `$branchName="master"` to `branchName="master"`

Bugfixes to "testScript.sh"

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/CPAN/tasks/main.yml

Found issue whilst working with the CentOS6 playbook. The `Install JSON` task would fail due to the `Install cpanminus RedHat 6, CentOS 6 and SLES` task skipping, despite being on CentOS6.
With issue #696 closed and this, the CentOS6 playbook runs to completion.
Fixes: #807

Altered CPAN's conditional so it doesn't skip installing cpanminus on CentOS6

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml

This is required as test builds fail due to inability to finding an PKG_CONFIG file- `openssl.pc`. This is because the OpenSSL version that is normally installed with the Ubuntu OS isn't the development version.

Adding libssl-dev role into Unix PB for Ubuntu

---

ansible/pbTestScripts/buildDocker.sh

More work towards #842.
This is a script that will automatically clone the build repository and make a docker build for whatever machine is running the script.
Several options allow the script to automatically build a specific jdk version, or all of them one after the other, using either hotspot (default) or openJ9.  
Eventually this will be put into the Jenkins job that tests each playbook on a regular basis.
Requested by @sxa555 in https://github.com/AdoptOpenJDK/openjdk-build/issues/1216#issuecomment-520852066.

Adding script to automatically test Docker builds on VMs

---

ansible/pbTestScripts/buildDocker.sh

Apparently `./make-any-platform.sh --clean-docker-build` does not cause the JDK to be made in a Docker container, but instead just make a clean one. The addition of the `--docker` argument is required to make it build in the container.

Added arguments to buildDocker.sh

---

ansible/pbTestScripts/testScript.sh

Requested by @sxa555 .
Changes to the script include:
- Option to build a single, user specified OS, VM, or all of them as before.
- Option to build a JDK on the VM, or not, thereby allowing JUST playbook testing if needed.
- Tidied up passing arguments to the script.
- Added a usage message.

Update to testScript.sh to allow for Parallelisation

---

ansible/playbooks/aix.yml

In the AIX playbook, the java will now extract the Java versions to `/usr`, and then rename them to `JavaX_64`, as opposed to making the subdirectory.
Sets Java8 to be the default Java once extracting.
Fixes #858

Java versions subdirectories fix & java8 symlink made

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/NVidia_Cuda_Toolkit/tasks/main.yml

Changed as per the conversation on #851 .
Tested on a Windows 2012R2 Vagrant VM. Once playbook was ran with the changes, `include` is in the `C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0` directory, and contains `cuda.h`, as that's what the build checks for.

Changed NVidia_Cuda_Toolkit role to fully install on Windows

---

ansible/Vagrantfile.Win2012
ansible/pbTestScripts/testScript.sh

Edits have been done to allow for automating testing of the Windows playbook, using the Win2012 vagrantfile.
Edits include:
- Adding into the Vagrantfile's inline script, commands to find the IP address of the Vagrant VM, and save it to a file within the shared folder.
- Automatically changing various files to enable connection through ansible:
- Changed ` - hosts: "{{ groups['Vendo ... ` to ` - hosts: all`;
- Enabling the ansible_password var in `../AdoptOpenJDK_Windows_Playbook/group_vars/all/adoptopenjdk_variables.yml`
- Adding `ansible_winrm_transport: credssp` to the same file.
- Changing `testScript.sh` to allow "Win2012", and variations as a viable OS.
Note: Unfortunately, if `./testScript.sh --build -v Win2012` is executed, it won't build a JDK on the Vagrant VM yet. The `--build` …

Automation of Windows playbook testing

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/main.yml

Don't override hostname if the `adoptopenjdk` tags are being skipped (as a non-adopt admin user would do)

Do not change hostname if adoptopenjdk tags are being skipped

---

ansible/Vagrantfile.Win2012

Required for issue #924 
The vagrant box that the Vagrantfile uses automatically boots a Windows GUI when running `vagrant up`. This is causing issues as the Jenkins Job is unable to produce that GUI, causing an error. 
With #927 being merged and the Vagrantfile's inline shell configuring the Windows VM on `vagrant up`, the GUI isn't necessary anyway.

Disabled GUI for Windows Vagrantfile on VagrantUp

---

ansible/pbTestScripts/testScript.sh

Done in preparation for #926 , so when running through the Windows playbook, the tasks and roles that require the Vendor_Files folder can be skipped.

Added "adoptopenjdk" to skip-tags for Windows in testScript

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Freemarker/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Jenkins/tasks/main.yml

As per @sxa555 's request.
The addition of these tags are to remain consistent with the Unix playbook's Jenkins tag, and allows testing of the playbook that don't require parts of the `Vendor_Files` folder.

Adding correct tags to the Windows Playbook

---

ansible/pbTestScripts/testJDK.sh
ansible/pbTestScripts/testScript.sh

Ref: #939 
Currently only implemented for the unix playbooks. If the option is specified, the script will run the `MachineInfo` test against a version of JDK8 that is built on the VM, having been setup by the playbook. It won't allow a test to be ran unless a JDK is built.

Added functionality for testScript.sh to run a test on a built JDK

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/VS2010_SP1/tasks/main.yml

Fixes: #383 
Ref: #553 , #942 
Found a way that should download and install VS2010_SP1 from the Windows Playbook. Must have MSVS2010 installed first. I've tested this on a Windows VM that did have MSVS2010 installed prior, but having ran MSVS_2010 and the new VS2010_SP1 tags on the playbook, it showed `Microsoft Visual Studio 2010 Version 10.0.40219.1 SP1Rel` under `help --> about microsoft visual studio`, which I believe means SP1 installed correctly.

Added VS2010_SP1 role to Windows playbook

---

ansible/pbTestScripts/README.md
ansible/pbTestScripts/buildJDK.sh
ansible/pbTestScripts/testScript.sh
ansible/pbTestScripts/vmDestroy.sh

Small updates to the scripts I've written over the last couple months that have been annoying me:
- Updating `README.md` to reflect how to use the scripts, and adding an options table.
- Changing in `buildJDK.sh` tilde to `$WORKSPACE` and a subsequent check incase `WORKSPACE` isn't detected.
-  Changing `testScript.sh` so it uses  just `echo` and not a mix of `echo` and `printf`. Also to be more specific with the log file searches.
- in `vmDestroy.sh`, add `Win2012` to the list of OSs, change `$HOME` to `$WORKSPACE` (with the aforementioned check), and standardised the use of `echo`, not `echo` and `printf`

Refactor of Playbook Scripts

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/NVidia_Cuda_Toolkit/tasks/main.yml

Whilst going through the PR to test builds on Windows, I've found an issue that the Windows PB doesn't install the NVidia Management Library as part of the Cuda toolkit, (an error stated that it couldn't find `nvml.h`). With the addition of this component put into the CUDA installation, the correct file is there.

Added install component to Windows PB CUDA role

---

ansible/README.md
ansible/Vagrantfile.Win2012
ansible/pbTestScripts/testScript.sh

Required to allow for the Ansible Playbook to fully run through - otherwise it ends up running out of diskspace around the `Clang` roles. Also added info into `README.md` as it requires the host machine install a vagrant plugin.

Added disksize parameter to Win2012 Vagrantfile

---

ansible/pbTestScripts/testScript.sh

Stops the Jenkins builds from saying "Success" when the playbook failed.

pbTest: added exits for use in Jenkins

---

ansible/pbTestScripts/testScript.sh

Removes the folder once the test has been completed. This will stop builds on the Jenkins machine from failing due to changes to the git repository in the Windows VM (changes that are required to connect to the Windows VM).

pbTest: Removes folder once completed

---

ansible/pbTestScripts/buildJDK.sh

Required to run Gradle - I remember the old iteration of this script working, so I'm puzzled as to why it doesn't suddenly. Either way, this fixes the issue.
Error message below from before the fix:
```
BUILD SUCCESSFUL in 29s
3 actionable tasks: 2 executed, 1 up-to-date
/home/vagrant/openjdk-build/sbin/build.sh: line 420: /bin/java: No such file or directory
Connection to 127.0.0.1 closed.
```

PbTest: Add JAVA_HOME var for buildJDK script

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Clean_Up/tasks/main.yml

Changed the spelling of CentOS, from centos to CentOS in AdoptOpenJDK_Unix_Playbook/roles/Clean_Up/tasks/main.yml playbook. 
The misspelling prevented a clean up task from being executed on CentOS machines.

correct centos misspelling

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml

Fixes: #739 
Based off the Ubuntu version. Tested on the Debian vagrant VM made from the vagrant file in #890 
Note: I removed the `update-cache` from the "Install Docker Prerequisites from Debian / Ubuntu " as there was the following error message: `E:The method driver /usr/lib/apt/methods/https could not be found.`
The packages that the playbook is installing in that method will fix that issue for future installations in the playbook.

Unix PB: Added Docker to Debian PB

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Jenkins_User/tasks/main.yml

This change sets specified limits on the Jenkins User, such as max files
open (nofile), max user processes (nproc), and max core file size (core).

Set limits for Jenkins_User

---

ansible/Vagrantfile.Win2012
ansible/pbTestScripts/buildJDKWin.sh
ansible/pbTestScripts/testScript.sh

Fixes: #977 
Changes made as follows:
- Removed all instances of `vagrant powershell` 
- Made the vagrant machine change to 100GB disksize in the Vagrantfile instead.
- Moved the cloning of openjdk-build and the changing of Git's CRLF settings into the `buildJDKWin.sh` file
Tested on a Lenovo ThinkPad running Linux Mint, as well as a Mac.

pbTests: Removed vagrant powershell. Put in workarounds

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/ccache/tasks/main.yml

Fixes the consistent error when running the playbook on CentOS6, as seen here: https://ci.adoptopenjdk.net/job/SXA-PlaybookCheckParallel/OS=CentOS6,label=infra-vagrant-1/lastBuild/consoleText
Changed the URL from the Samba website to the git-hub releases as whenever `wget` (or the `get_url` module) was used inside of Ansible, a 403 error would be given. However, it would work when executing `wget` manually. This was also working for a fair amount of time before, so it seems most likely to be a problem with the Samba website.

UnixPB: Changed Ccache URL

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Freemarker/tasks/main.yml

Initially this was put in to keep consistency with the Unix playbook, however, a Windows machine can't build a j9-JDK without this being run as part of the playbook.

WinPB: Remove adoptopenjdk tag from Freemarker

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Clean_Up/tasks/main.yml

The unix playbook would fail on CentOS6, as `yum -y autoremove` isn't a command apparently: 
https://ci.adoptopenjdk.net/job/SXA-PlaybookCheckParallel/OS=CentOS6,label=infra-vagrant-1/29/console
Made it specific to CentOS7

Fixed Clean_up role for Centos6

---

ansible/Vagrantfile.Win2012

Currently the IP address is found through taking the 5th line from `Get-NetIPAddress | % {$_.IPAddress }`. This is usually fine, however occasionally, the IP Address on the machine is on the 4th line - resulting in Ansible attemping to connect to the wrong IP address 
e.g.: https://ci.adoptopenjdk.net/job/SXA-PlaybookCheckParallel/OS=Win2012,label=infra-vagrant-1/30/console
I've found that the IP Address will always start with `172` so I use that as a basis to find the correct IP from the output.

WinVF: Fixed finding IP

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/GIT_Source/tasks/main.yml

`git_installed.rc` has to be 0, to carry out the action, because you can't remove what isn't there.

Unix PB: Removed unnecessary check in Git_source

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Clean_Up/tasks/main.yml

An update to a fix yesterday - I felt this was better as it just blacklists CentOS6, as opposed to whitelisting CentOS7, meaning it's more future proof if other versions of CentOS are added.

UnixPB: Changed condition for yum autoremove in Clean_Up

---

ansible/Vagrantfile.Win2012
ansible/pbTestScripts/testScript.sh

This is a more reliable check to find the correct IP address of the Windows Vagrant machine. It will output all IP addresses under the alias `Ethernet*`, into a temporary file and then sort by the largest found number and output that into the file ansible uses. The largest number always appears to be the IP address that Ansible will use to connect to the vagrant machine.

pbTest: More reliable Windows IP check; Removal of carridge return from output file.

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml

To fix this error from the Windows playbook:
`TASK [OpenSSL : Install OpenSSL-1.1.1 32-bit] **********************************************************************************************************************************
fatal: [jsvt288]: FAILED! => {"changed": true, "cmd": "set PATH=C:\\Strawberry\\perl\\bin;C:\\openjdk\\nasm-2.13.03;%PATH% && .\\vsvars32.bat && cd C:\\temp\\openssl-1.1.1 && perl C:\\temp\\openssl-1.1.1\\Configure VC-WIN32 --prefix=C:\\openjdk\\OpenSSL-1.1.1-x86_32 && nmake install > C:\\temp\\openssl32.log && nmake -f makefile clean", "delta": "0:00:04.374979", "end": "2019-10-22 07:43:05.908558", "msg": "non-zero return code", "rc": 1, "start": "2019-10-22 07:43:01.533578", "stderr": "\r\nFailure!  build file wasn't produced.\r\nPlease read INSTALL and associated …

switch openssl & nasm because openssl depends on nasm

---

ansible/pbTestScripts/testScript.sh

Outputs the time the playbook finishes. They're helpful for debugging the Jenkins Job (`SXA-PlaybookCheckParallel`) as theres been issues of the playbooks failing (due to timeout or some other reason) and knocking out Vagrant connections. They're also be helpful when we add the `--build` option to the job. 
Otherwise, it doesn't hurt to have them in when running `testScript.sh` locally.

pbTests: Addition of time messages for debug

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Ant-Contrib/tasks/main.yml

At least one of the sourceforget mirrors when downloading the `ant-contrib` tarball is vorboss.dl.sourceforge.net and that one seems to be rather intermittent. I suspect that's why we're seeing problems with that work item. Even the second attempt here took a while to get going
```
sxa@x220t:/dev/shm$ wget https://vorboss.dl.sourceforge.net/project/ant-contrib/ant-contrib/ant-contrib-1.0b2/ant-contrib-1.0b2-bin.tar.gz 
--2019-11-16 18:53:11--  https://vorboss.dl.sourceforge.net/project/ant-contrib/ant-contrib/ant-contrib-1.0b2/ant-contrib-1.0b2-bin.tar.gz
Resolving vorboss.dl.sourceforge.net (vorboss.dl.sourceforge.net)... 5.10.152.194
Connecting to vorboss.dl.sourceforge.net (vorboss.dl.sourceforge.net)|5.10.152.194|:443... failed: Connection timed out.
Retrying.
--2019-11-16 18:55:22-- …
```

Use retries on ant_contrib URL to resolve sourceforge URL connection issues

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Ant-Contrib/tasks/main.yml

Extension to #995 
The `until` tag is required for the retries to happen.

UnixPB: Retry Ant-Contrib role properly

---

ansible/pbTestScripts/testScript.sh

Mainly put in to help towards getting the `SXA-PlaybookCheckParallel` job run-able on Jenkins, as it seems the `vagrant halt` seems to affect multiple VMs running in parallel.

PBTests: Added --no-halt option

---

ansible/pbTestScripts/vmDestroy.sh

Updates to make the script a bit more useful - this will destroy all of the VMs that have the OS that is passed to the script. This is more work towards #865 as a way of halting and destroying all VMs before all the `testScript.sh` s are ran, but not interfering with the playbook being executed.
This will still be useful if using `testScript.sh` locally, however would need to be used with more caution if there's VMs that are required to be retained.

pbTests: Updated VMDestroy

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml

This was working ok with latest ansible but not with my laptop's 2.6.1 ... Since we have a trap to ensure we have >=2.4 and this works fine without a nested variable, I'm changing this to work ok with the earlier version.

Remove nested variables from adoptopenjdk_install role

---

ansible/pbTestScripts/testScript.sh

Cleans up the files that are required for ansible to connect to the Windows VM once the playbook, build and test has ran. This doesn't interfere with interacting with the VM, so the `--retainVM` option is still usable - it just can't run the playbook again without restoring the file.
Required to ensure the Jenkins job doesn't attempt to connect to an incorrect IP when re-running.

pbTests: Cleanup Windows files

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Jenkins/tasks/main.yml

Add user to Performance Log Users to view counter data.
Related Issue: https://github.com/eclipse/openj9/issues/7716

Add Jenkins user to Performance Log Users group

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Version/tasks/main.yml

Recently updated the Ansible version on jenkins slave `infra-vagrant-1` and the Windows playbook would fail with the following error message:
```
TASK [Version : Verify if Ansible version is 2.4 or above] *********************
fatal: [172.28.128.33]: FAILED! => {"msg": "template error while templating string: no filter named 'version_compare'. String: {{ ansible_version.string | version_compare('2.4', '>=') }}"}
```
This PR fixes that and reflects what the unix playbook does.

WinPB: Change Ansible version check to reflect Unix's

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/OpenSSL102/tasks/main.yml

Similar to #1012 
Found whilst running through the CentOS6 playbook with `SXA-PlaybookCheckParallel`

UnixPB: Change OpenSSL102 role to have correct version checks

---

ansible/Vagrantfile.CentOS6
ansible/Vagrantfile.CentOS7
ansible/Vagrantfile.Ubuntu1604
ansible/Vagrantfile.Ubuntu1804
ansible/pbTestScripts/testScript.sh

The change will make `testScript.sh` run the playbook on each Linux VM as it does with the Windows - runs ansible locally and points it at the VM.
This have been put in because currently, when running the jenkins job `SXA-PlaybookCheckParallel`, the use of `vagrant ssh -c` appears to be the cause of vagrant VMs being halted unintentionally. 
The `--build` and `--test` options have also been changed to not use `vagrant ssh -c`.
Has been tested on macOS and on the Jenkins job.

pbTests: alter testScript to run ansible locally and point at VM

---

ansible/pbTestScripts/buildJDK.sh
ansible/pbTestScripts/testScript.sh
ansible/pbTestScripts/vmDestroy.sh

Among other changes, this will ensure that ansible uses the correct id_rsa to try and connect to the vagrant machines. This PR also : 
- Moves git clone to `buildJDK.sh` as this was taken out with #1016 
- Ensures `vmDestroy.sh` doesn't fail when `vagrant global-status` has invalid entries
- Removes the IP of the vagrant machine from the host's `known_hosts` file, as not to encounter ssh warnings about man-in-the-middle attacks
Unfortunately, this only works when the system running `testScript.sh` uses `GNU sed`.

pbTests: Ensure ansible uses correct private key

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Debian.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Debian.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/OpenSSL102/tasks/main.yml

fixes: #1015 
@sxa555 @gdams 
These are all the changes I've had to implement to allow for a complete run through of the playbook. I was also able to build JDK8-openJ9, JDK11-openj9 and JDK13-HS when it ran through.
I've based the `Common/tasks/Debian.yml` and `Common/vars/Debian.yml` files on the `Ubuntu.yml` files of the respective repositories and changed them to suit:
- Made sure `update_cache=no` is put in for the first 2 repositories, as the source files are required to be changed from `Jessie` to `Trusty`
- Added the above task to change `Jessie` to `Trusty`
- Removed all the assigning Java tasks
- Removed openjdk-8-jdk from the "Build_Tool_Packages" *
In addition to this I have:
- Changed the conditionals to include Debian in the OpenSSL102 roles, as system OpenSSL from the …

UnixPB: Changes to allow for Debian8 playbook run through

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Firefox/tasks/main.yml

To solve the issue found here : https://ci.adoptopenjdk.net/job/SXA-PlaybookCheckParallel/163/OS=Win2012,label=vagrant/console
This PR will just use a different URL to download the same version of Firefox, as I think the download link of it was causing the installation issue. Tested on macOS and Linux.

WinPB: Changed Firefox download link

---

ansible/pbTestScripts/buildJDK.sh

To fix the issue here where CentOS6 (and 7) are finishing the playbooks and compiling `GIT_SOURCE`, however still can't find `git` in the path.

pbTests: Added /usr/local/bin to path when building JDK on unix

---

ansible/playbooks/vagrant.yml

Requested by @sxa555 to setup the machines to run the `SXA-PlaybookCheckParallel`.
Tested on an Ubuntu1804 machine, by running the following commands:
- Took note of the IP
- Created a host file called `vagrant_hosts`, with `<IP_Address> ansible_ssh_user='root' ansible_ssh_pass=<Password>`
- Installed `sshPass` on my Macbook
- Running `ansible-playbook -i vagrant_host vagrant.yml`.
I've written the playbook for the software versions to reflect the version that are currently installed on my Macbook

PBs: Added PB for setting up vagrant machines

---

ansible/playbooks/aix.yml

Signed off by : Pav.Salimon@ibm.com
The new X11 content was pulled from an AIX 7.1 Install ISO along with the dependancies.
`AIX_v7.1_Base_Install_7100-04-06-1806_Flash_52018.iso`

Fixed X11 Install from AIX Ansible Playbook

---

ansible/playbooks/aix.yml

* renamed existing registers and tags for xlc -> xlc13
* added a cleanup for xlc13 and xlc16 temporary files

Adding XLC16 to aix playbook as its a requirement for JDK13

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/GIT/tasks/main.yml

There was an error with downloading GIt on the windows playbook : 
```
TASK [GIT : Install GIT] *******************************************************
fatal: [172.28.128.4]: FAILED! => {"changed": false, "cmd": "C:\\temp\\git.exe /SILENT /COMPONENTS=\"icons,ext\\reg\\shellhere,assoc,assoc_sh\"", "msg": "Exception calling \"CreateProcess\" with \"5\" argument(s): \"CreateProcessW() failed (The file or directory is corrupted and unreadable, Win32ErrorCode 1392)\"", "rc": 2}
```
The downloading task before it seemed to incorrectly downloading the git executable, as the size was much smaller than what it should've been. Narrowed it down to the `win_get_url` module being the issue. 
The addition of the line `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12` is …

winPB: Change Git version to latest; use win_shell module

---

ansible/pbTestScripts/testJDK.sh

Updated `testJDK.sh` to work now that builds are semi reliable (once #1034 is merged).
Tested on built JDKs in Ubuntu1604. Ubuntu1804 and CentOS6.

pbTests: Update testJDK.sh

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Debian.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml

Extension of #1021 
Changes to allow the playbook to run through on Raspbian Buster. I noticed there was an override to cause Raspbian to run the Ubuntu version of the playbook. I deleted this as there is now a Debian 
specific playbook. 
The only additions were adding a couple of repositories to allow for the playbook to install gcc-4.8 on the RPI - This is not available to Raspbian Buster by default. I also had to add the Raspbian specific repository and gpg key for Docker, as the Debian repository relies on the `auf-dkms` package that is not available on Raspbian (ref: https://github.com/raspberrypi/linux/issues/3021).

UnixPB: Changes so PB runs on Raspbian Buster

---

ansible/pbTestScripts/buildJDK.sh

As the build in `SXA-PlaybookCheckParallel` are JDK8-J9 builds, they need a higher GCC version to be set, so this PR ensures that.
Different OSs have different names for the OpenJDK-8 that's installed via the playbook. The change made should allow both Ubuntu and CentOS OSs in the job to find the correct JDK.
i.e, CentOS6 has `java-1.8.0-openjdk-1.8.0.232.b09-1.el6_10.x86_64`
and Ubuntu1604 has `java-1.8.0-openjdk-amd64`

pbTests: Find correct JDK versions for different OSs

---

ansible/pbTestScripts/testScript.sh

General refactor of the script to make it more readable and put the order of functions more like the order of execution. 
Also changed the `checkVagrantOS` function to detect which vagrant files are available, to then provision the VM and run the playbook against it. It future proofs it for when additional Vagrantfiles are added.
A `clean-workspace` option has been added as well. This will delete the old workspace if detected before git cloning a brand new one. Added this as it will stop any "Please stash your git changes before attempting to pull" messages that occur in the `SXA-PlaybookCheckParallel` job.

pbTests: Refactor and clean-workspace option

---

ansible/pbTestScripts/testScript.sh

Fixed an issue where the script would stop, and not start a build of the JDK on the VM, even if the playbook succeeded, due to the `pbFailed` var not being set.

pbTests: Fixed pbFailed var assignment

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml

- The variable groups['Vendor_groups']
is skipped due to lack of definition when we
run AdoptOpenJDK Unix Playbook internally
- Replaced it with a command line variable
and set the value to all or a specific group
Signed-off-by: Jenny Chen <Jenny.Chen@ibm.com>

Passed the value of hosts from command line

---

ansible/pbTestScripts/buildJDKWin.sh
ansible/pbTestScripts/testJDKWin.sh
ansible/pbTestScripts/testScript.sh

Fixes: #865 (I hope) - https://ci.adoptopenjdk.net/job/SXA-PlaybookCheckParallel/208/
Last commit that should get the SXA-PlaybookCheckParallel job finished and working. Fixes the `buildJDK.sh` to remove the git config line as that should be set in #1047 . Changed `testJDKWin.sh` to find `TKG` not `TestConfig`. Added `vagrant reload` to `testScript.sh` as the Windows VM seems to have its shared folder disappear after the playbook runs. `vagrant reload` will just restart the vagrant box and remount the shared folders.

pbTests: Altered Windows Scripts to build and test

---

ansible/Vagrantfile.Debian8
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Ant-Contrib/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Debian.yml

Fixing incorrect names of Ansible modules in the `../Common/tasks/Debian.yml` file.
Also added the commands necessary for ansible to connect to a Debian8 Vagrant VM, tp `Vagrantfile.Debian8`, and fixed a trailing space.

UnixPB: Debian Fixes + trailing space fix

---

ansible/pbTestScripts/testScript.sh

Not in the correct directory as there is no Vagrant environment. Think this may've been a commit I accidentally dropped instead of squashed from  #1053 .

pbTests: Put vagrant reload in the right place

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/GIT/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml

Ref: #1023 
The issue is that the way Git is being installed means it will be changing the line endings as `git clone` is happening on a windows machine. This PR will change the git config so that it won't change the line endings.
As it's unclear whether the `git` being used is from Cygwin, or "git-for-windows", so this PR will contain changes to both roles, as there's no benefit to them converting the line endings for Windows in our situation anyway. 
git-for-windows: This involves creating a config file for the installation to use to determine settings. 
Cygwin: Once installation of Cygwin and its packages are done, a task will change the `.gitconfig` that's there once Cygwin is installed. Git falls under the `Devel` category of Cygwin Packages being installed, and in the playbooks …

WinPB: Fix the Git installation for Windows

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Ant-Contrib/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/CentOS.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/SLES.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/GIT_Source/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NVidia_Cuda_Toolkit/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_FreeBSD.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_RedHat.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_SLES.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Tunnel/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/OpenSSL102/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Protobuf/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Python3_Source/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/ant/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/autoconf/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/cmake/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/curl/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_48/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_7/tasks/main.yml
ansible/playbooks/vagrant.yml

Fixes: #998 
This will be broken up into a few groups:
- The 1st group of checksums commit entail all the roles with `get_url` tasks that have provided a checksum with the download. I.e. `cmake`s one is from https://cmake.org/files/v3.11/cmake-3.11.4-SHA-256.txt
- The 2nd group will entail all roles that don't provide a checksum. These will be found by executing `wget` on each URL and installing them onto a VM. If the installation works correctly, I'll assume the downloaded item was correct and use that checksum.

UnixPB: Add checksums to all `get_url` modules

---

ansible/README.md
ansible/pbTestScripts/README.md

Updating the `README`s to more accurately describe how to manually setup a Windows VM and run the playbook and how to automatically build them using `testScript.sh`

PbTests: Updated READMEs relevant to the Test Scripts

---

ansible/Vagrantfile.Debian8

`ifconfig` is unfortunately not a thing in Debian8, therefore I found a new way to output a list of IP addresses, like the rest of the Vagrantfiles do.

Made Deb8 VF find IP correctly

---

ansible/pbTestScripts/README.md

pbTestScripts: Add Debian8 reference and link to VagrantPlaybookCheck job

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/CPAN/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/SLES.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/SLES.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NVidia_Cuda_Toolkit/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Swap_File/tasks/main.yml

fixes: #1033 
Fixes all of the issues listed in 1033. 
The only concern I have is the changes implemented to not install CPAN's XML::Parser, and instead install `perl-xml-parser` under the `test-tool-packages` section. Supposedly that's meant to be equivalent, according to this : https://github.com/chorny/XML-Parser/blob/master/README
However, I don't know how to verify this. It does install however.
I've done this as CPAN XML::Parser has a dependency for `libexpat1-dev` (or `libexpat-dev`) or `expat-dev` depending on the OS, that appears to not be available to SLES12-SP4 (The machine both @Haroon-Khel and I were testing on).
Note: Currently testing using the `vagrantPlaybookCheck.sh` script. https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/220/

UnixPB: Update playbook to allow SLES12 to work

---

ansible/Vagrantfile.FreeBSD12
ansible/Vagrantfile.SLES12
ansible/pbTestScripts/vagrantPlaybookCheck.sh
ansible/pbTestScripts/vmDestroy.sh

fixes: #1061 
This PR will allow us to test the unix playbooks for the above OSs, so we don't run into a series of unexpected errors such as #1033 . 
FreeBSD12: I have managed to get the `generic` box working, which is the FreeBSD12 box with the most downloads and looks the most trustworthy. https://app.vagrantup.com/generic/boxes/freebsd12. FreeBSD12 doesn't support the `vboxsf` file type, so between the 2 alternatives of `smb` and `rsync`, `rsync` has been used as `smb` is not supported on linux hosts. Due to `rsync`s inability to share files from the guest VM to the host machine, the plugin `vagrant-rsync-back` has had to be used to do this.
SLES12: I've got this working using a Vagrantfile provided by SUSE. Unfortunately, this is only SLES12SP1, however there were no SLES12SP3 or SP4 …

VFs: Add FreeBSD12 and SLES12 Vagrantfiles

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml

This is due to FreeBSD12 having the group called `wheels` instead. However, the group should default to `root` in the case of the other OSs anyway.
I also changed the tags on the final 2 tasks as these are incorrect.

UnixPB: Remove 'group' tag from adoptopenjdk_install role

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/FreeBSD.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/ccache/tasks/main.yml

Continuation from #1061 
This will allow the playbook to run entirely on a Vagrant VM made from the FreeBSD12 Vagrantfile.

UnixPB: Make changes so FreeBSD works

---

ansible/pbTestScripts/testJDKWin.sh

Fixes: #1072 
A suite of tests that are still quite fast to run, but will also validate the installation of `Strawberry Perl` on the VM that had the Playbook ran on it.
Tested on a VM that skipped the `Strawberry Perl` role, to ensure that it does fail when it isn't installed, and it does:
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/275/OS=Win2012,label=vagrant/console

pbTest: Run extended.system tests on Windows instead of _MachineInfo

---

.travis.yml
ansible/inventory.yml

Part of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1031
NOTE: WIP until we are ready to decomission the old ones.
NOTE2: I'm not sure if the z/OS ones we had are worth keeping now since we cannot currently build on z/OS (even assuming those systems are really still there)

Update Marist zlinux inventory to the new z15 linux machines

---

ansible/pbTestScripts/vagrantPlaybookCheck.sh

Fixes the issue where it would say something such as :
`No Vagrantfile for Ubuntu1804 available - please select from one of the following
CentOS6 CentOS7 Debian8 FreeBSD12 SLES12 Ubuntu1604 Ubuntu1804 Win2012`

pbTests: Fix 'checkVagrantOS' error message

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml
ansible/playbooks/aix.yml

May resolve issues with API instability as per https://github.com/AdoptOpenJDK/openjdk-api/issues/190

ansible: Switch adoptopenjdk downloads to APIv3 from APIv2

---

ansible/pbTestScripts/README.md
ansible/pbTestScripts/vagrantPlaybookCheck.sh

new `-sm` parameter that adds extra tags that can be skipped but still allow the `buildJDK.sh` and `testJDK.sh` to run. Useful for quickly testing changes 

pbTests: add optional extra skip tags to speed up testing

---

ansible/pbTestScripts/vagrantPlaybookCheck.sh

Requested by @sxa555 
An issue found where if not building/testing a JDK and `no-halt` hasn't been specified, the script will attempt to run `vagrant halt` in the wrong directory, causing the following error message.
This is due to the `cd` command that it needs being in an `if` statement that returns false if not building a JDK.
Error message: 
```
The playbook finished at : 13:41:11
A Vagrant environment or target machine is required to run this
command. Run `vagrant init` to create a new Vagrant environment. Or,
get an ID of a target machine from `vagrant global-status` to run
this command on. A final option is to change to a directory with a
Vagrantfile and to try again.
```

pbTests: ensure in correct directory to vagrant halt

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/FreeBSD.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/ccache/tasks/main.yml

A couple of issues I found whilst running through the FreeBSD12 playbook locally.
- if `gtar` is not installed, then creating the symlink later on isn't possible.
- `wget` is required to be installed, otherwise the `ccache` role will fail
- the `ansible_processor_cores` variable is undefined at the point it runs the `ccache` role. The `ansible_processor_vcpus` is FreeBSD's equivalent.
- The override task to turn `amd64` to `x86_64` was testing and setting the wrong variable. FreeBSD is the first instance of it being an issue, as the `ansible_architecture` variable is set to `amd64`. If not corrected, the `adoptopenjdk_install` role doesn't download or install the JDK, and then fails at the `chown` task.

UnixPB: Fixes for FreeBSD12

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/SLES.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/ccache/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/cmake/tasks/main.yml

fixes: #1090 
The addition of the task in the `../Common` role will stop there being any point of having so many tasks that are specific to `s390x` that just replace the `ansible_processor_vcpus` variable with `ansible_processor_cores` variable.

UnixPB: Set vars for s390x and remove unneeded tasks

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml

Jan 2020 OpenJ9 releases on Linux/x64 will be built with JITserver support enabled, which requires protobuf.
Discussed in https://ci.adoptopenjdk.net/view/work%20in%20progress/job/VagrantPlaybookCheck/
Testing at https://ci.adoptopenjdk.net/view/work%20in%20progress/job/VagrantPlaybookCheck/323/

unixPB: Enable protobuf for OpenJ9 JITserver

---

ansible/pbTestScripts/buildJDK.sh
ansible/pbTestScripts/testJDK.sh

Now that FreeBSD12 passes the playbook, `buildJDK.sh` needs to be altered to be able to set the correct environment variables for it to build the correct JDK.
I've also added in the ability to pass in JDKs, so we have the option to build more than JDK8 on these playbooks. 
As we don't build openJ9 on FreeBSD, that defaults to Hotspot, however linux distributions are built in `openJ9` as they require more dependencies be installed.

pbTests: Update buildJDK.sh to support FreeBSD & openSUSE

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/CentOS.yml

CentOS6 - set Java 8 as the default with the Alternatives utility/command.

Set Java 8 as Default in Alternatives 

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Protobuf/tasks/main.yml

Upgrade protobuf version from 3.5.1 to 3.7.1 and update the download
link accordingly.

Upgrade protobuf to v3.7.1

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/SLES.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml

Related to https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/683
The tags `build_tools`, `build_tools_openj9` and `build_tools_openjfx` have been added to certain roles/tasks so that these can be skipped if creating only a test machine.
~~This is a work in progress, please do not merge yet~~

Added build tags to appropriate roles

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Protobuf/tasks/main.yml

Problem found as of upgrading Ansible to 2.9.4 - Using the `set_fact` module doesn't actually set the variables for the environment anymore, therefore they need to be passed in on the task. 
This wouldn't be an issue as supposedly GCC 4.8 can build Protobuf, as well as GCC-7, however in the instances when the default GCC is <4.8 (i.e. the OpenSUSE Vagrant VM), this is required.

unixPB: Pass CC/CXX variables to Protobuf build task

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/7-Zip/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/ANT/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Clang_32bit/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Clang_64bit/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Firefox/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Freemarker/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Freetype/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/GIT/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/IcedTea-Web/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java7/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2010/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2017/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/NVidia_Cuda_Toolkit/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/OpenSSL/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Rust/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Strawberry_Perl/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cmake/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/nasm/tasks/main.yml

Ref: #1058 
@Haroon-Khel found that as of ansible 2.8, the `win_get_url` module separates the checksum and checksum algorithm fields, however (weirdly) not Unix's `get_url` module. Before ansible 2.8, `checksum` wasn't in the documentation at all.
https://docs.ansible.com/ansible/latest/modules/win_get_url_module.html   <-- latest
https://docs.ansible.com/ansible/2.7/modules/win_get_url_module.html       <-- 2.7
However, before ansible 2.8, it must've been planned as putting the checksum option in (as it is now) doesn't cause crashes. This wasn't noticed as the Jenkins nodes that runs the `vagrantPlaybookCheck` job are on ansible 2.5.1, where (presumably) the checksum option was just ignored.

winPB: Update checksums for win_get_url module

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/CentOS.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Debian.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml

The inclusion of zulu-9 in the Additional_Build_Tools variables lists causes the `/etc/alternatives/java` symlink to be redirected to the zulu-9 version of java on those systems where it is installed.
Removing zulu-9 from the list fixes #1108

Remove zulu-9 from Additional_Build_Tools var lists

---

ansible/playbooks/AdoptOpenJDK_ITW_Playbook/roles/Common/tasks/CentOS.yml

Following on from https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1108, it would make sense to remove the task of adding the Zulu repo from the icedtea web playbook.

Remove azul repo from Icedtea web playbook

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/main.yml

Set ansible_processor_vcpus to ansible_processor_cores when defined or
default it to 1.

Set ansible_processor_vcpus for cmake role

---

ansible/pbTestScripts/buildJDK.sh

The main openjdk-build repository goes not have all of the changes required to build freebsd yet -  using @gdams' alternate branch on that platform

vagrant: Temporarily use alternate openjdk-build branch

---

ansible/pbTestScripts/testJDK.sh

After the removal of `run_configure.mk` , the script would fail if it can't find it, therefore taking it out. Also `MachineInfo` has been move to `system` tests.

pbTests: update testJDK.sh to not use run_configure.mk

---

ansible/pbTestScripts/buildJDK.sh

Removed the extra arguments from `git clone`, move the function into a better place (i.e after `$TARGET_OS` is defined), and use `$TARGET_OS` to determine if we should build use @gdams FreeBSD build repo, or the standard build repo.

pbTests: Fixup last buildJDK.sh commit

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml

We wish to use the separate role in order to force the use of GCC7 for the OpenJ9 builds as the code is statically linked in during build time.

unixPB: Remove duplicate protobuf install

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/MacOSX.yml

remove p7zip dependency on macOS

---

ansible/Vagrantfile.CentOS6
ansible/Vagrantfile.CentOS7
ansible/Vagrantfile.Debian8
ansible/Vagrantfile.FreeBSD12
ansible/Vagrantfile.SUSE12
ansible/Vagrantfile.Ubuntu1604
ansible/Vagrantfile.Ubuntu1804

Stops Vagrantfiles from showing: 
```
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
At the end of `vagrant up` if no `id_rsa.pub` file is found.

VFs: Ref #685 non-zero exit status fix

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/SLES.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/SLES.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NTP_TIME/tasks/main.yml

Requested by @sej-jackson 
Additions to the `../common/*/SLES.yml` files, to allow for the playbook to run through on SLES15 and build JDK8-J9 on it. Most of the added packages were available from the default repos on the machine, however `devel-tools` was added for `libdwarf-devel` to be installed. 
Tested on a SLES15 SP0 internal machine. This initially didn't have `sudo` installed however - the `git_source` role will fail if this is the case, however I assumed that _actual_ machines would already have this on the machine?

UnixPB: Add support for SLES15-SP0

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/GIT_Source/tasks/main.yml

Noticed whilst fixing the playbooks for SLES15 SP1, that the `GIT_SOURCE` role has tasks that use `sudo`. The SLES15 SP1 environment I was running didn't have `sudo` installed, and so the `./configure and make` task failed. However, `sudo` isn't required to be used as `become: yes` is used. 
VagrantPlaybookCheck Run: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/365/

UnixPB: remove sudo from GIT_SOURCE role

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Protobuf/tasks/main.yml

Latest playbooks only install GCC 7.5 into /usr/local/gcc (from https://github.com/AdoptOpenJDK/openjdk-build/issues/1508) so this removes 7.4 and 7.3 options from the list of things to search for.

Build protobuf with gcc 7.5 and remove 7.3/7.4 locally installed options

---

ansible/pbTestScripts/buildJDK.sh

Requested by @sxa555 
Update `buildJDK.sh` to be able to build JDKs other than JDK8-J9, as well as give it the option to use other branches of the openjdk-build repository.

pbTests: Change buildJDK to build from other URLs

---

ansible/pbTestScripts/qemu_test_script.sh

As mentioned here: https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1119#issuecomment-582798063
Required to `git clone` from the correct branch

pbTests: Change URLs to run the playbook from

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/SLES.yml

fixes: #1141 
ref: #1140 , #1147 
Should be the last thing to allow SLES15-SP1 to work with our playbooks. SLES15-SP1 specific repos don't have `pulseaudio` like SP0 does. However, this has been determined to not be needed anyway: https://adoptopenjdk.slack.com/archives/C5219G28G/p1582041329095100?thread_ts=1582035001.094600&cid=C5219G28G

UnixPB: Remove pulseaudio from Common/vars/SLES.yml

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_7/tasks/main.yml

This should resolve the failing CentOS8/SUSE12 playbook executions - issue introduced by https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1148

playbook: Update gcc-7 role to install gcc 7.5

---

ansible/Vagrantfile.CentOS6
ansible/Vagrantfile.CentOS7
ansible/Vagrantfile.Debian8
ansible/Vagrantfile.FreeBSD12
ansible/Vagrantfile.SUSE12
ansible/Vagrantfile.Ubuntu1604
ansible/Vagrantfile.Ubuntu1804
ansible/Vagrantfile.Win2012

Increase RAM available to Vagrant machines (especially Windows) and cap the CPU on the hypervisor for each individual one so that the build jobs don't overwhelm it

Ram increase for Vagrant VMs

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2017/tasks/main.yml

ref: #1149  
To fix the problem seen here:
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Win2012,label=vagrant/369/console
The checksum must've been changed around the same time as the cygwin one.

winPB: Change checksum for MSVS_2017

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_7/tasks/main.yml

Ref: #1158 
Initially I was going to change the checksum to be correct now that we've changed what we're downloading, however now the role has been changed to only have one downloading task for all of the architectures, we can't put only one checksum on the task. Therefore, removing it.

unixPB: Remove checksum for gcc_7 task

---

ansible/pbTestScripts/buildJDK.sh
ansible/pbTestScripts/vagrantPlaybookCheck.sh
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/FreeBSD.yml

Ref: #1152 
Added the option to specify the build repo so these can be checked in the `VagrantPlaybookCheck` Jenkins job too. This will also allow the FreeBSD12 Vagrant VM to pull from @gdams 's fork of `openjdk-build` to build, in the job.
I've also added jdk11 to the `../Common/vars/FreeBSD.yml` list as this is required to build JDK11.

pbTests: Added option to specify openjdk-build repo

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gmake/tasks/main.yml

ref: #1129 , https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1106#issuecomment-590349778
Fixing the conditionals added in from here. In the current situation, a system will run these roles if it is both SLES/SUSE12 or Ubuntu14 on x86_64, AND CentOS/RHEL6/7, which isn't possible.

unixPB: Fix conditions to gmake

---

ansible/pbTestScripts/testJDK.sh

ref: https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/OS=FreeBSD12,label=vagrant/381/
FreeBSD (when building using @gdams openjdk-build/freebsd branch) will put it's built jdk in the same equivalent folders, but call it just `jdk`, therefore, alter in the case of testing FreeBSD's built JDK.

pbTests: Alter location of FreeBSD built JDK

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/trss.yml

The `AdoptOpenJDK_Unix_Playbook/trss.yml` contains **most** of the manual steps to configure machines to run the TRSS service. 
The playbook currently only supports Ubuntu 18 on x86_64.
The manual steps that were omitted from the playbook are:
- `forever-service install TRSSFrontend -e "NODE_ENV=production" -f " --workingDir /home/jenkins/openjdk-test-tools/TestResultSummaryService" --script /home/jenkins/openjdk-test-tools/TestResultSummaryService/frontend.js  -o " --configFile=path-to-trssConf.json"`
- `forever-service install TRSSBackend -e "NODE_ENV=production" -f " --workingDir /home/jenkins/openjdk-test-tools/TestResultSummaryService" --script /home/jenkins/openjdk-test-tools/TestResultSummaryService/backend.js  -o " --configFile=/dev/mongodb/credentials/path-to-trssConf.json"`
- …

Playbook to configure machines for TRSS

---

ansible/inventory.yml

Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1171 (xLinux)
and https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1154 (zLinux) - we may not keep all four zLinux systems though

inventory: add softlayer centos6+marist build machines

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml

fixes: #697 
The issues listed on the #697  are no longer relevant to the current playbooks as the `adoptopenjdk9` role no longer exists, and we're not able to add the `openjdk-7-jdk` package as the `openjdk-r` repository doesn't have it available for `arm`, however we can build `jdk8` with `jdk8` so this isn't an issue.
However, whilst running through the playbook to ensure it worked, the `adoptopenjdk_install` role doesn't work as the `ansible_architecture` variable is set as `armv7l`, not `arm` as APIv3 requires, so I've made an ARM specific role for it.

UnixPB: Arm specific adoptopenjdk_install task

---

ansible/pbTestScripts/buildJDKWin.sh
ansible/pbTestScripts/vagrantPlaybookCheck.sh

Update to allow the VagrantPlaybookCheck Jenkins job to specify which jdk we want to build for both Unix and Windows, with defaults to JDK8 - OpenJ9.

pbTests: Update buildJDKWin to specify which JDK to build

---

ansible/pbTestScripts/buildJDKWin.sh

ref: #1187 
Currently cloning `openjdk-build` to `/home/vagrant` but then tries to start `make-adopt-build-farm.sh` as if the repo is in `/cygdrive/c/`.

Correct buildJDKWin path

---

ansible/pbTestScripts/testJDK.sh

Currently, when running VagrantPlaybookCheck and building any JDKs other than 11, the tests are failing as it can't find the jdk to set `TEST_JDK_HOME`.

pbTests: alter testJDK to find all JDK versions

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/OpenSSL/tasks/main.yml

Ref: #1159 , https://github.com/AdoptOpenJDK/openjdk-build/issues/1556
Add OpenSSL 1.1.1d 64-bit built with VS_2017 into the playbooks for OpenJ9 JDK11+ on Windows.

WinPB: Install OpenSSL 1.1.1d 64-bit MSVS_2017 to machine

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml

Cygwin setup has been updated to 2.903 so the checksum has changed

winPB: Update Cygwin checksum

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml

fixes: #1210 
Fix-up the playbooks to use https://ci.adoptopenjdk.net/userContent/winansible/ to significantly reduce time of Cygwin installation.
Testing at:
https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/425/OS=Win2012,label=infra-vagrant-1/console

winPB: Update Cygwin to use a prebuilt folder

---

ansible/pbTestScripts/testJDK.sh

Tested on Debian8 VM - was able to build/test `jdk11` and `jdk14`.

pbTests: Detect TEST_JDK_HOME properly

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/CentOS.yml

Ref: https://github.com/ansible/ansible/issues/44708
#1190 
With the above PR, CentOS' locale jobs were changes from using the `shell` module to the `locale_gen` module, however this caused an issue with `CentOS7` in the `vagrantPlaybookCheck` job (See: https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/420/OS=CentOS7,label=vagrant/)
This PR reverts those changes, as well as adding the `skip_ansible_lint` tag, to stop the linter flagging `[305] Use shell only when shell functionality is required` rule.

unixPB: Revert CentOS locale changes

---

ansible/pbTestScripts/README.md
ansible/pbTestScripts/buildJDK.sh
ansible/pbTestScripts/testJDK.sh

Remove one of the `*` from `testJDK.sh` as it was attemping to set the `__strip_jdk` directory as `TEST_JDK_HOME`. 
Updates to the documentation to include all the additional options put in recently. I've also rearranged the order of them as to group them somewhat.

pbTests: Docs update & remove search from testJDK.sh

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/openSUSE.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/nasm/tasks/main.yml

Issues noticed when running the VagrantPlaybookCheck job.
nasm was looking for gcc7.3, which has been taken out of the playbooks since #1158 ,
The OpenSUSE role had to be reverted back from #1190 , as replacing the `shell` module for the `zypper` module means the `--force-resolution` argument can't be put in. The `skip_ansible_lint` tag has been put in, with a comment for justification.

UnixPB: Make nasm pickup gcc7.5, revert opensuse gcc4.3 install task

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/openSUSE.yml

Due to : https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/OS=SUSE12,label=infra-vagrant-1/441/consoleFull
Not quite sure how we got this far without it, to be honest. Tested on the SUSE Vagrant VM, installs `autoconf v2.69` fine.

unixPB: Add autoconf to SUSE playbook

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml

As discussed in the infrastructure channel in the Adopt workspace, we are not currently using these tasks when setting up new Adopt machines, hence I have commented them out of the top level playbook for now

Temporarily comment out Nagios tasks

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Clang_32bit/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Clang_64bit/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/OpenSSL/tasks/main.yml

On the windows playbook, I have changed download source of the openssl and llvm 32bit from `userContent` to `userContent/winansible` (https://ci.adoptopenjdk.net/userContent/winansible/), as per https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1215
The source for the cygwin download was already set to the winansible directory by a previous commit

Ansible pulls from userContent/winansible

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml

I've taken the Cygwin cache PR ( #1219 ) out, as there were some issues with Git : 
```
Cloning into 'C://openjdk-build'...
fatal: unable to access 'https://github.com/adoptopenjdk/openjdk-build/': SSL: couldn't create a context: error:0E079065:configuration file routines:def_load_bio:missing equal sign
``` 
When installed normally, this issue doesn't occur.
I've also pinned Cygwin's Make version to `4.2.1-2` as there was an issue building JDK11 with Make version 4.3 : https://www.mail-archive.com/bug-make@gnu.org/msg12006.html
which causes this issue: 
```
make[3]: *** No rule to make target '/cygdrive/c/workspace/build/src/build/windows-x86_64-normal-server-release/buildtools/langtools_tools_classes/_the.BUILD_TOOLS_LANGTOOLS.vardeps', needed by …
```

[wip] WinPB: Revert Cygwin cache, pin Make to v4.2.1-2

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/riscv_cross_compiler/tasks/main.yml

ref: https://github.com/eclipse/openj9/issues/7421
This adds a role that installs all the additional tools necessary to build JDK11/J9 for riscv64. Currently, the tasks have the `adoptopenjdk` tags on them as this isn't necessarily wanted as standard on the machines. This roles is also only for CentOS x86_64 machines, as the `riscv_toolchain_linux` was built for CentOS. 
The role is currently pulling from https://ci.adoptopenjdk.net/userContent/riscv/ to get the prebuilt toolchain and qemu fedora `sysroot` folder. The UserContent folder also includes instructions on how to setup a machine manually, and start that build. 
Given the tag, this role can't be tested on `VagrantPlaybookCheck`, however I manually tested on a CentOS6 VM made from our Vagrantfiles and was able to build the JDK :-)

UnixPB: Add role for riscv building

---

ansible/pbTestScripts/buildJDKWin.sh
ansible/pbTestScripts/testJDK.sh
ansible/pbTestScripts/testJDKWin.sh

Additional fixes to :
1) stop `testJDK.sh` finding the `debug-image` thats produced when building JDKs
2) Allow `testJDKWin.sh` to find built JDKs other than JDK8

pbTests: Test script fixes

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/OpenSSL102/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/OpenSSL/tasks/main.yml

Recently OpenSSL change the URLs to retrieve the old versions of their source. Checksums won't need to change as the tarballs are the same (though I did check).

PBs: Update OpenSSL URL

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/CodesignCert/tasks/main.yml

Requested by @gdams 
When running the Installer job on the machine, it looks for the `windows.p12` file, which isn't added in by the playbook.

WinPB: Add CodesignCert roles

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Common/scripts/shortName.ps1
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/shortNames/scripts/shortName.ps1
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/shortNames/tasks/main.yml

Ref: #1239 
When setting up the Azure machines, `short names` weren't enabled on the `C:/` drive, which stopped builds as it didn't like the spaces in directories such as `Microsoft Visual Studio`.

WinPB: Add playbook role to set shortpaths in 'Program Files (x86)'

---

README.md
ansible/inventory.yml
ansible/plugins/inventory/adoptopenjdk_yaml.py

- Remove softlayer machines that had already been decomissioned
- Move aarch64 machine into a test role (New machine [test-packet-ubuntu1604-x64-2[(https://ci.adoptopenjdk.net/computer/test-packet-ubuntu1604-armv8-2/) active)
- Remove obsolete category from adoptopenjdk_yaml.py
- Update README.md to remove decommissioned ci-jck server

inventory: Remove already-decommissioned JCK systems

---

ansible/inventory.yml

Also move `docker` section to be in the correct place alphabetically :-)

inventory: Move ubuntu build machines to docker group

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/WMF_5.1/tasks/main.yml

ref: #1239 
Updates Powershell to `v5.1`. Required for the `Expand-Archive` cmdlet.

winPB: Add WMF install role

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/WMF_5.1/tasks/main.yml

ref: #1239 #1255 
`hotfix_install.reboot_required` was undefined when the Powershell version was already 5, as the proceeding task didn't run.

winPB: WMF role Condition fix

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml

fixes: #1251 
Add JDK-11 to the list of JDKs to install for the Unix PB, as requested by @sxa555.

UnixPB: add JDK11 to list of JDKs to install

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/riscv_cross_compiler/tasks/main.yml

Ref: #1251 
Rearranging the conditions to this, stops ansible from reading the variable that would be undefined if the `check` tasks are skipped, i.e. in the situation of RHEL7.

unixPB: Rearrange riscv conditions

---

ansible/inventory.yml

Found a machine that was offline but still available to us, so I've cleared it up (full of old docker images) and have connected it back into jenkins to increase capacity

inventory: Add ex-build Ubuntu/s390x machine to docker group

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/MacOSX.yml

closes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1271
Also removes `p7zip` as it's no longer needed

add gnu-sed to macOS playbook

---

ansible/pbTestScripts/vagrantPlaybookCheck.sh

Small changes I've been meaning to get round to.
1) Remove `SLES-12` to run `vagrant rsync-back`, as we no longer have a SLES vagrantfile
2) Remove MSVS_2017 from 'fastmode', as it's required for Window's OpenSSL role now, and OpenJ9 requires MSVS_2017 for some (if not all) builds.
- Add VS2012_SP1 to fastmode as MSVS_2010 is required to install it, but is ignored when fastmode is specified.
3) Replace `vagrant reload` for `vagrant halt --force && vagrant up` and add `--force` on standalone `vagrant halt`s. This is due to a bug where the Windows Vagrant VM hangs when `vagrant halt` tries to shutdown the VM 'gracefully'. 
4) Added a note explaining why the VM needs to be restarted via Vagrant

pbTests: Force vagrant halt for Windows runs

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_7/tasks/main.yml

Noticed the discrepancy awhile ago. I'm going to try running the change through the `vagrantPlaybookCheck` job as I'm not sure the condition is necessary required anymore. As can be seen from the below link, the gcc_7 task is run despite it not being intended to, but the build still succeeded: https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/OS=CentOS6,label=infra-vagrant-1/464/consoleFull
It's been succeeding in CentOS7 and CentOS8, so it's worth testing them too.

UnixPB: Correct gcc_7 conditions

---

ansible/inventory.yml

Two machines were created in order to check out solutions to https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1154 - I gave back the "middle two" in order to retain one we had created with 16Gb of RAM. That was `-4` and is now `-2` after removing the middle two

inventory: Renumber marist zlinux build machines after handing two back

---

ansible/pbTestScripts/buildJDKWin.sh
ansible/pbTestScripts/testJDKWin.sh
ansible/pbTestScripts/vagrantPlaybookCheck.sh

When running VagrantPlaybookCheck Jenkins job and building JDK8, the Windows VM will fail as it attempts to run Gradle with jdk-7, as that was `JDK_BOOT_DIR` was set to. I've found that setting the `JDK8_BOOT_DIR` variable will run Gradle w/ JDK8, but keep the `JDK_BOOT_DIR` variable at jdk-7, thereby simulating what we do on our Jenkins build jobs.

pbTest: set correct params running buildJDKWin w/JDK8

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java_install/tasks/main.yml

ref : https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1289#issuecomment-618856873
At ~200mb each, it'd be better to remove these after unarchiving them.

WinPB: Remove .zip file of jdk after installation

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/openSUSE.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/openSUSE.yml

Adding all libraries that were in `Common/vars/centos.yml`, and removing the self built `zlib` as it was causing issues with finding `libpng` in the build: 
https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/507/OS=SUSE12,label=infra-vagrant-1/console
VPC Run: https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/515/

unixPB: Add openj9 libraries, remove self-built zlib for OpenSUSE

---

ansible/pbTestScripts/vagrantPlaybookCheck.sh

ref : https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/OS=CentOS8,label=infra-vagrant-1/523/console
I noticed at the end of this run, that the function was destroying all of the currently running VMs, not just the one that had finished. Addition of `grep $OS` will stop this.

pbTests: VPC.sh: destroy only the correct OS VM

---

ansible/pbTestScripts/vagrantPlaybookCheck.sh
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/OpenSSL/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/shortNames/tasks/main.yml

As this script is mainly for the `vagrantPlaybookCheck` Jenkins job, I've only catered for the parameters that are able to be entered in that Jenkins job. (i.e. put in the cases for JDK8, 11, 13 and 14)
Fast-mode now gives the option for some roles to be skipped (mainly in the case of Windows), depending on what JDK is being built and it's variant, so that it only installs what's required to build that specific JDK.
ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1273#pullrequestreview-392833354
When given a chance, I'll put this through the VagrantPlaybookCheck job to ensure it works- I'll keep the [wip] tag until I can get a successful build on at least JDK8 and JDK11

pbTests: Change Fast-mode to change depending on other parameters

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/IPv6/tasks/main.yml

Added IPv6 Role
Enables IPv6 via sysctl.conf on RHEL systems.
Allows for IPv6 testing.
Pav.Salimon@ibm.com

UnixPB:IPv6

---

ansible/Vagrantfile.Win2012
ansible/pbTestScripts/startScriptWin.py
ansible/pbTestScripts/vagrantPlaybookCheck.sh

Fixes: #1296 
ref: https://github.com/Willsparker/pywinrm/pull/1
Switching to using ssh/winrm as we want to have live stdout from the build/tests as they run on the `vagrantPlaybookCheck` Jenkins job.
Windows:
Linux: 
Testing:

pbTests: Alter VPC to use ssh/WinRM to start build/test scripts

---

FAQ.md
ansible/README.md

Hi,
In the README.md, the option **-s** seems an option not anymore present with ansible-playbook CLI, at least for the version 2.9.7.
On my Ubuntu 18.04, it seems to run correctly without this option.
Regards

Replace -s to -b in ansible-playbook command-line examples

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Debian.yml

Ref: https://adoptopenjdk.slack.com/archives/C53GHCXL4/p1588329011104200
Annoyingly, one of Debian 8 's GPG keys have been expired since 25/04, with no indication that it will be renewed as Debian 8 falls out of support on the 30th of June. However, as we have some test machines that are still running Debian 8, for the time being it's better to have the capability to install packages in case we need it, rather than not.

UnixPB: Allow unauthorised packages on Deb8

---

ansible/pbTestScripts/vagrantPlaybookCheck.sh

Fixes: #1287 
See above issue for more in depth details.
This variable should effectively stop Jenkins from killing the process that keeps the vagrant VMs running - and allowing the `VagrantPlaybookCheck` job to run in parallel.
https://wiki.jenkins.io/display/JENKINS/ProcessTreeKiller

pbTests: Add BUILD_ID variable for Jenkins

---

ansible/Vagrantfile.Debian10
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Debian.yml

ref: #1308 
As mentioned in the above PR, Debian 8 out is out of support at the end of June, therefore we should probably look into our playbook supporting a newer version - Debian 10.
The 2 issues (that I'm aware of) that remain after this PR will be that `gcc-4.8` won't be installed, and neither will a version of `jdk7`, so this may not be able to build JDK8/HS out the box.
Apart from the Vagrantfile, the primary thing this PR is doing is just making sure all the repos that are meant for other versions of Debian, aren't added to a Debian 10 run.

UnixPB: Add Deb10 VF and 'Common/task/Debian.yml' changes to support it

---

ansible/playbooks/aix.yml

Currently playbooks are trying to place the openjdk7 required for bootstrapping JDK8 into `/usr/java7_64` which is the location that the IBM Java uses. If an IBM Java7 is installed then this will cause confusion.
To prevent ambiguity I want to leave this in it's original location of `/usr/j2sdk_image` and this can be set in the jenkins definition for the machine as `JDK7_BOOT_DIR`
Resolves https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1319

aixPB: Do not move openjdk7 into IBM java7 location

---

ansible/pbTestScripts/buildJDK.sh
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/zulu7/tasks/main.yml

ref: https://github.com/AdoptOpenJDK/openjdk-build/issues/1732
Add in Zulu-7 to Unix playbook, as it can be a consistent JDK-7 amongst all the distributions, as some new linux distros are unable to install `openjdk-7` with their package manager.

UnixPB: Add Zulu7 for JDK8 Build bootstrap, make buildJDK.sh use JDK7

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2017/tasks/main.yml

Ref: 
https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/593/OS=Win2012,label=infra-softlayer-ubuntu1804-x64-1/console
They've changed it again..

WinPB: Correct MSVS_2017 checksum

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml

Ref https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1226
Made changes to the `Docker` and `Common` role to accommodate for Ubuntu 20.
Skips installing `gcc-4.8` and `g++-4.8`. Installs `docker.io` instead of `docker-ce`
Still have yet to find a fix for the failing NTP_TIME role, but I thought id push these changes in the meantime

UnixPB: docker and gcc4.8 changes

---

ansible/pbTestScripts/buildJDK.sh
ansible/pbTestScripts/vmDestroy.sh
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Debian.yml

Several changes to allow building JDK8 / HS on Debian10:
1) Change `buildJDK.sh` to detect `JAVA_HOME`. correctly for Debian Buster
2) Add a condition to ensure it doesn't attempt to install gcc-4.8 (as this is unavailable for Debian 10's repos)
3) Symlink `/usr/bin/gcc-7` and `/usr/bin/gcc` and the same for `g++`. As `gcc-4.8` is unavailable to Debian 10, the gcc to use to build JDK8/HS should be the lowest version available - `gcc-7.4`. Tested and it does build JDK8/HS now.

UnixPB: Alter Deb Common file & pb script to build JDK8/HS on Deb10

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml

- Changed `libstdc++.so.5` to `libstdc++`
libstdc++.so.5 fails due to no valid package name, which is a blocker when running the Common task for Adopt_Unix_playbook on RHEL7 ppc64le.
```
TASK [Common : Install additional build tools for RHEL 7 on ppc64le] ***********
failed: [rhel7lert-11.fyre.ibm.com] (item=libstdc++.so.5) => {"ansible_loop_var": "item", "changed": false, "item": "libstdc++.so.5", "msg": "No package matching 'libstdc++.so.5' found available, installed or updated", "rc": 126, "results": ["No package matching 'libstdc++.so.5' found available, installed or updated"]}
```
This is fixed when changing the var in roles/Common/vars/RedHat.yml from libstdc++.so.5 to libstdc++
Signed-off-by: kevin-bonilla <kevin.bonilla@ibm.com>

UnixPB: Fix libstdc++ for Redhat vars on ppc64le

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/WiX/tasks/main.yml

This is what I believe is the best alternative to #1322 and #1323 (and so I'm going to close those PRs).
In it's current state, `windows-sdk-10.1.1776.1` is installed using chocolatey. I have also noticed that when running `VagrantPlaybookCheck`, the task is only ran when you _don't_ install `MSVS_2017`. When you do, the task does run but errors when attempting to install it (see https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1322#issue-416660288 for logs / proof of this). 
I'm not sure what the cause of this is, but either way, the `win_chocolatey` task is broken in it's current form- whether it is skipped in `VPC` or not, the task should work. The other downside of skipping the `Wix` tag means that the installation of WiX isn't tested, which isn't ideal.
According to @gdams …

WinPB: Install Win-sdk-10.1 manually, not w/ chocolatey

---

ansible/inventory.yml
ansible/plugins/inventory/adoptopenjdk_yaml.py

Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/619
Noticed whilst working on https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1001 that the `inventory.yml` isn't particularly in sync with the node list at `ci.adoptopenjdk.net/computer`. This PR is to try and clean it up for the build machines. I've added the build machines that are ping-able and connected to Jenkins but not in `inventory.yml`, (from this list: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1001#issuecomment-631401001). I also rearranged the order as to make sure they are alphabetical, and made sure their names are correct. 
The `build-linaro-centos76-armv8-1` machine has been removed as we no longer have it, looking at `ci.adoptopenjdk.net/computer`

Inv: Update build machines to be inline w/Jenkins

---

ansible/inventory.yml

Fixes: #634 
This should get the `inventory.yml` more accurately reflecting Jenkins. This PR is primarily ensuring `inventory.yml` is in alphabetical order and adds in a couple machines that are on Jenkins but not here.
I have omitted from `inventory.yml` the machines with the `-sxa` prefix, on request of @sxa, as they're only meant to be temporary machines.
Currently `test-inspira-solaris10u11-sparcv9-1` is commented out as I'm unable to find the IP address for the machine (ping @gdams )

inv: Update Test/infra machine sections

---

ansible/pbTestScripts/vagrantPlaybookCheck.sh

Fixes #1281 
Previous issue encountered where Windows VMs would hang if `vagrant halt` was ran without a `--force` flag. I've been unable to recreate the issue, so I'll remove the flags. If it recurrs we can re-open the above issue

pbTests: Remove `--force` flag when using vagrant halt

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NTP_TIME/tasks/main.yml

Ref https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1226
Skips the `Set timedatectl set-ntp no` task for Ubuntu 20 as it causes the playbook to break, but instead runs an alternative, but equivalent, task of disabling the `systemd-timesyncd` service. This alternative task can also be run on distros that are not Ubuntu 20, since, after some inspection, our machines have the `systemd-timesyncd` service disabled by default.
However this service is not available on Centos or Redhat, hence the alternative task is skipped for those distros.

UnixPB: Failing NTP_TIME role for Ubuntu 20

---

ansible/Vagrantfile.Ubuntu1804

Fixes: #1344 
Fixes an issue specific to the Vagrant box that we use, where `grub-pc` needs to be upgraded with the `DEBIAN_FRONTEND=noninteractive` variable, to stop a prompt coming up on the `apt-get upgrade` task in the playbook. 
In draft until I can run it through `VPC` properly.

VF: Force no-prompt upgrade to grub-pc on U18

---

ansible/Vagrantfile.Ubuntu2004

Ref: #1226 #1340 
As the two above PRs are in and merged and `generic` recently releasing an Ubuntu20.04 vagrant box, I've added it so we can start testing it with `VPC`, when it eventually works. 
This is effectively the same as the other Ubuntu VFs, though I've stripped out the unnecessary code in the script session. I've also redone the command required to get the IP address as thats changed between U18 and U20.

VFs: Add Ubuntu20.04

---

ansible/pbTestScripts/vmDestroy.sh

Allow `vmDestroy.sh` to pickup Ubuntu2004 as a viable option, so it can be destroyed in the `VagrantPlaybookCheck` Jenkins job.

pbTests: Add Ubuntu2004 to vmDestroy.sh

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NTP_TIME/tasks/main.yml

Ref https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1364
Currently the `Ensure systemd-timesyncd service is disabled` fails on FreeBSD. However since this task is a "duplicate" of the `Set timedatectl set-ntp no` task which is skipped for FreeBSD it seem logical to skip this failing task too

UnixPD: Skip failing NTP_TIME task for FreeBSD

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/CentOS.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/RedHat.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml

- Added `numactl-devel` to `Additional_Build_Tools_RHEL7_PPC64LE`
numactl-devel is a required package for running builds. During my testing I ran into blocker due to missing numactl dependancies on Redhat 7 ppc64le
```
configure: error: Could not find numa!
```
This is fixed when adding `numactl-devel` to vars in roles/Common/vars/RedHat.yml, more specifically under `Additional_Build_Tools_RHEL7_PPC64LE`
Signed-off-by: kevin-bonilla <kevin.bonilla@ibm.com>

UnixPB: Add numactl-devel for Redhat vars on ppc64le

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml

Ref: #1001 
Stop install JDK12 on machines as we no longer build JDK13, start installing JDK14 for JDKNext.

PBs: Update which JDKs to install

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gmake/tasks/main.yml

Fixes: #1106 
This change will exclude `make` from auto-updating after creating the symlink to `gmake`. With the CentOS / RedHat system, the `yum` package of `make` is a dependency of `yum` itself and therefore can't be uninstalled, however if the updates are stopped, the symlink created won't be broken. 
This should stop machines reverting back to using an older version of `make`.

UnixPB: Exclude make from updating when gmake is built

---

ansible/pbTestScripts/buildJDK.sh

Recently the `VPC` job has been issues finding a JDK to run Gradle. 
I think this may be due to the `find` function in `buildJDK.sh` picking up multiple JDK8s - i.e. `/usr/lib/jvm/jdk8` and `/usr/lib/jvm/jdk8u242-b09`.
Hardcoding `JAVA_HOME` to `/usr/lib/jvm/jdk8` should be okay as the `adoptopenjdk_install` task ensures it's at that path.

pbTests: Force 'JAVA_HOME' to /usr/lib/jvm/jdk8

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/SLES.yml

Added missing dependancies for SLES that can be installed with zypper.
- libelf0-32bit
- libelf0-debuginfo-32bit
- libstdc++-devel-32bit
- libXtst6-32bit
Signed off by Pav.Salimon@ibm.com

UnixPB: Added missing dependancies

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2017/tasks/main.yml

Update MSVS_2017 chcksum as it's out of date again: 
https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/OS=Win2012,label=infra-softlayer-ubuntu1804-x64-1/691/console
I double checked the checksum that the above log says it was by running `sha256sum vs_community.exe` and I got the same result.

winPB: Update MSVS_2017 download checksum

---

ansible/pbTestScripts/buildJDK.sh

Ref: #1387 
I didn't realise that as part of the above PR we now symlink the JDK versions to `/usr/lib/jvm/jdk-XX` ( or `/usr/lib/jvm/jdk8`), like we do with the Windows playbooks. Due to this, the `find` functions that are being replaced in this PR pick up multiple entries, which confuse the build-scripts. (see all the Ubuntu runs and C6 / C7 in this `VPC` run: https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/692/ )
Hardcoding this fixes this :-)

pbTests: Hardcode JDK_BOOT_DIR in buildJDK.sh

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml

Fixes: #1401 
FYI @lumpfish 
Separates the task `Add c:\cygwin64\bin to front of %PATH%` and `Remove speech marks from %PATH%`,  as it makes it clearer how each task is being done, for people who don't know `cmd` / Windows.
As well as this, making sure that these changes are made only as we install cygwin, as the path changes are only needed directly after it's installed, and rerunning the current `Add c:\cygwin64\bin to front of %PATH%` task causes an error.

winPB: Separate remove speech mark & add cygwin to front of %PATH% task

---

docs/Setup-RISCV-VMs.md

As we've been doing a fair amount of stuff with RISC-V (i.e. https://github.com/AdoptOpenJDK/openjdk-build/pull/1577 ), I've had to setup a few different kinds of RISC-V VMs to test / build on.
I thought I'd create a guide to setup the VMs that are a little bit more user friendly than the ones I've had to use, for future reference. This also serves as a bit of a crash course in QEMU in general.

docs: Add doc to setup RISC-V QEMU VMs

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml

The centos7 dockerfile doesn't come with which by default

ansible: add which to centos packages

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Providers/tasks/main.yml

Fixes: #1427 
Add a role for tasks that are provider specific to go, along with finding the provider from the hostname on the machine- as most machines I tested had their hostnames the same as their name according to `inventory.yml` and ci.adoptopenjdk.net/computer.
I also added the tasks that were specific to GoDaddy machines (ref: #1145 #1423 ), in which to update `/etc/hosts` and make it persist through reboots, the template file must also be updated.
I've made sure that the tasks all have `adoptopenjdk` as a tag, as this is very specific to setting up machines for AdoptOpenJDK. (Note: Due to this tag, this PR won't be able to be tested through `VPC`)
This was tested on a CentOS6 vagrant VM, whose hostname was set to `test-godaddy-ubuntu1604-x64-1` for testing purposes. To test that …

UnixPB: Add provider specfic role & godaddy host tasks in it

---

.travis.yml

the arm64 builds kept crashing, travis support advised me to switch to graviton2

travis: fix arm64 build

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2017/tasks/main.yml

Found in `VPC`: https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/728/OS=Win2012,label=vagrant/console

WinPB: Update MSVS_2017 checksum

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Debian.yml

unixPB: don't try to install gcc 4.8 on any Debian 10 arch

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml

Ref: #1444 
WIP PR to keep a track of all changes needed to fix the S390x run of `QEMUPlaybookCheck` ( https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/ARCHITECTURE=s390x,label=vagrant/ )

UnixPB: apt_cache update on Ubuntu s390x Install

---

ansible/README.md

Fixes: #1436 
Add information on how to increase the timeout of ansible winrm connections to Windows guests, as well as provide a link to additional variables that could be helpful.

Docs: Add info on how to increase winrm timeouts

---

ansible/pbTestScripts/vagrantPlaybookCheck.sh

Multiple changes for usability:
- Mandate either `-a` or an explicit `Vagrantfile` (i.e. don't default to "all")
- Show help information if you don't do the above, so users can find out how to run it
- Display list of valid vagrantfiles (assumes they're in `..` relative to the current dir, won't work if you run it other than with `./vagrantPlaybookCheck`)
- Fixes the name of the script in the help screen which was `./testScript`
- Modifies the length of the lines on the help screens so (most of them) fit in 80 characters, and all of it fits on an 80x25 console
- Removes the tab characters fom the help screen to ensure the formatting is unambiguous

pbTests: Make OS mandatory for clarity, reduce size of help screen

---

ansible/pbTestScripts/vagrantPlaybookCheck.sh

Validate that the docker installation is usable. We should ideally run this as the jenkins user but for now I just want to validate that docker is installed and starting appropriately on platforms where the playbooks set it up.

pbTests: Allow testing of docker installation

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Debian.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml

ref: #1444  ; https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/46/ARCHITECTURE=arm64,label=vagrant/
For Debian10/aarch64 , `docker-ce` isn't an available package, however `docker.io` is : https://packages.debian.org/buster/arm64/docker.io/download
Running through QEMUPlaybookCheck here: https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/47/

UnixPB: Install docker.io for Debian, Add gcc-7 to Common role for aarch64 

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/RedHat.yml

Ref https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1470
Added a task into `Redhat.yml` which adds the EPEL repo for rhel 6.
Tested on a rhel 6 x86 machine. EPEL repo and `libdwarf-devel` are both installed without error. Im unable to test this on other architectures as only x86 rhel 6 machines are available to me through fyre. However, according to https://fedoraproject.org/wiki/EPEL#What_packages_and_versions_are_available_in_EPEL.3F, for rhel 6, EPEL is only available on x86 and i386. Hence I have added a condition which only installs the EPEL repo on x86

Enable EPEL repo for rhel 6

---

ansible/Vagrantfile.Win2012
ansible/pbTestScripts/vagrantPlaybookCheck.sh

Start to log builds and tests in a `VPC` run. This allows those logs to be searched as well, thereby stopping a `VPC` run from going onto testing if a build failed. This also stops false positives in Jenkins.
In additional, some other changes have been made:
- Adding the additional `.\ConfigureRemotingForAnsible.ps1` script calls into the Windows Vagrantfile. Previously, only the one to enable `Credssp` was ran, which did seem to suffice- however I've added these as it is required when setting up machines, and also seems to make connecting to the Windows VM via Ansible more stable.
- Change the `sed` commands that were used to add lines to the `ansible.cfg` file to an `awk` command, as this stops the requirement of `GNU sed`. (Thanks @sxa , for figuring that one out)

pbTests: Refactor searchLogFile functionality; Add logging for builds and tests

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Windows_Updates/tasks/main.yml

Ref: #1469 
While the above seems to be an isolated issue for those particular machines, it's shown that there's no point having `ignore_error: yes` on the first task, if it doesn't have it on the second task, as the `update_result` variable is undefined if the first task fails. This also allows for workarounds to be done for the group of machines that the referenced issue affects without the playbook failing or having to add `Windows_Updates` to the `ansible-playbook` `--skip-tags` option.
ping @lumpfish

winPB: Ignore errors on win_update reboot task

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/RedHat.yml

Fixes: #1467 
Changes include:
- Adding the `link` option to all the ansible alternatives modules, as RHEL based systems require it. https://docs.ansible.com/ansible/latest/modules/alternatives_module.html#parameter-link
- Changing the ppc64le / s390x `path` to use the `java-1.8.0-openjdk` symlink that is created, instead of the version specific version of the string- this also means we don't have to update this later on. 
- Remove the s390x task, and add `or ansible_architecture == "s390x"` to the ppc64le task as I've checked that these have the same path.
Note: This PR won't be able to run through either [vagrantPlaybookCheck](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [qemuPlaybookCheck](https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/) as they aren't able …

UnixPB: Fix java alternatives for RHEL7 ppc64le/s390x

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/cmake/tasks/main.yml

Despite it being there from the gcc_48 role in the playbook, the system cannot detect gcc-4.8.5 on the machine when building cmake during the `cmake` role, resulting in the error:
```
"C compiler on this system is: gcc       ",
"---------------------------------------------",
"Error when bootstrapping CMake:",
"Cannot find a C++ compiler supporting C++11 on this system.",
```
Placing the included PATH variable before ./configure seems to have fixed this.
I received this error on two different rhel 6 machines, and this fix worked for both of them.

UnixPB: Fix path variable for cmake on rhel6

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_7/tasks/main.yml

Fixes: #1472
Stops `ccache` being built from source when it is extracted from the binary retrieved in the `gcc_7` task. 
VPC Run: https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/773/
(Only CentOS VMs are ran as they're the only ones that have the `gcc_7` task ran on them)

UnixPB: Symlink ccache to stop building from source

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gcc_48/tasks/main.yml

Because https is always better than http ;-)

unixPB: Pull gcc48 source from an https URL

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml

Furthermore, I changed the URL to the one recommended in the Docker docs (see https://docs.docker.com/engine/install/debian/).

Fix URL for Docker GPG key

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/RedHat.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml

- Found a different approach (thanks @Willsparker for the help), for installing `docker-ce` on RH7 ppc64le. 
- Requires EPEL repo, modified `Common/RedHat.yml` to add RH7 to EPEL repo list
- Also following this [IBM documentation ](https://developer.ibm.com/linuxonpower/docker-on-power/), and using the `yum_repository` module, I had to add the correct docker.repo in order for RH7 ppc64le to install `docker-ce` 
Fyi: previous PR #1460
Signed-off-by: kevin-bonilla <kevin.bonilla@ibm.com>

UnixPB: Add RH7 to EPEL and add Docker repository for RH7 ppc64le

---

ansible/pbTestScripts/buildJDK.sh
ansible/pbTestScripts/buildJDKWin.sh

Ref: https://github.com/AdoptOpenJDK/openjdk-build/blob/master/docker/buildDocker.sh , https://github.com/AdoptOpenJDK/openjdk-build/pull/1982
Recently, I changed the above script to use the API to set the JDK versions as this will automatically update with every major release without having to alter `buildDocker.sh`- as the functionality changed there is also in the `buildJDK*.sh` scripts, I've copied what I needed from that and altered it to make it work. With #1481 , `VPC` is currently unable to test this PR as `buildJDKWin.sh` doesn't recognise `JDK15` as a valid JDK. As they'll need to be updated to include JDK15 anyway, I thought it'd be silly not to automate it considering I've done it before :-P
I've pre-tested the changes for both Windows and CentOS here: …

pbTests: Add better checkJDK logic to buildJDK*.sh

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Clang_32bit/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Clang_64bit/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java7/tasks/main.yml

Use `win_shell` instead of the `raw` module when creating symlinks in the Windows Playbook. This was prompted by getting an error message whilst investigating #1485 : 
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: winrm.exceptions.WinRMError: Access is denied.  (extended fault data: {'transport_message': 'Bad HTTP response returned from server. Code 500', 'http_status_code': 500, 'wsmanfault_code': '2147942405', 'fault_code': 's:Receiver', 'fault_subcode': 'w:InternalError'})
fatal: [9.20.194.40]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout":
```
This seems to only be specific to the Windows machines I was provisioning (@lumpfish didn't get this issue when using machines from the same provider), however I …

winPB: convert 'raw' modules to 'win_shell' when making symlinks

---

ansible/pbTestScripts/vmDestroy.sh

I noticed that `VPC` doesn't try to destroy CentOS8 machines. This due to it using the `all` option, in which `C8` was not in the list of the `case` statement. I've also removed `S12` as we've removed the Vagrantfile and removed SUSE12 from `VPC`.

pbTests: Add C8 to vmDestroy.sh

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Clean_Up/tasks/main.yml

Causing Travis failures. Skipping for now to unblock the builds

ansible: skip flaky cleanup on aarch64

---

ansible/pbTestScripts/vagrantPlaybookCheck.sh
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/riscv_cross_compiler/tasks/main.yml

It doesn't seem to be an adoptopenjdk setup specific task and it's currently getting skipped in the dockerfile builds

ansible: remove adoptopenjdk tag from riscv task

---

ansible/pbTestScripts/buildJDK.sh
ansible/pbTestScripts/qemuPlaybookCheck.sh

Ref: #1465 #1452 #1444 
Add logging to the build and test branches in `qemuPlaybookCheck.sh` to stop false positives (as it stops running a test if a build fails).  
If a build or test fails, it exits with error code `127` - the Jenkins jobs have been configured to report `unstable` if the build or tests fails, but `failure` if the playbook fails.
Tested at:
https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/60/
https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/61/. (The Jenkins job has been configured to report unstable if `exit 127` since this job ran)

pbTests: Add logging to QEMU builds/tests & Rename ARM64 to AARCH64

---

ansible/Vagrantfile.Win2012
ansible/pbTestScripts/vagrantPlaybookCheck.sh

Ref: #1504 (1st issue fix)
When looking to fix the connection issues when connecting to Windows VMs with Ansible, that happened (I would guess) around 60-70% of the time, I found that command `vagrant winrm` would work when Ansible connection wouldn't. This meant there was a different and more stable way to connect to these machines. I found one of the ports listed ( described as the `winrm_ssl` port ) could be used in the host file, not unlike the changes done here ( #1442 ). Since the change, every VPC run has been able to connect to the Windows VM without issue. 
I've tried to give links to comments explaining where the port numbers aren't necessarily intuitive (i.e. the python script uses the port before the one that ansible does).

pbTests: Connect to Windows VM using 127.0.0.1:%portNumber%

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2010/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml

Fixes: #1485 
ping @lumpfish 
Uses Powershell to remove the speech mark & put `C:/cygwin64/bin` to the beginning of the path, as the `setX /M` command didn't appear to work. When the speech mark was present in the Path, it also stopped building OpenSSL due to the speech mark causing the `./vcvarsall` script (or equivalent) to not work - however without producing an error message (otherwise this would've been spotted earlier).

WinPB: Fix task to remove quotes from path after cygwin install

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2019/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/OpenSSL/tasks/main.yml

* eclipse/openj9#9805
* add top level main.yml, MSVS_2019 role and add openssl 1.1.1g built with VS2019

WinPB: Add VS2019 support for Windows JDK15 builds

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/linux_installer/tasks/main.yml

Without this (e.g. if you only have a JRE) the installer job can fail with:
```gradle
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :buildSrc:compileJava FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':buildSrc:compileJava'.
> Could not find tools.jar. Please check that /usr/lib/jvm/java-8-openjdk-amd64 contains a valid JDK installation.
```

unixPB: Installer jobs need access to a full JDK

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2017/tasks/main.yml

Ref: https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/828/OS=Win2012,label=vagrant/
(Double checked by `wget`ing `vs_community.exe` and running `sha256sum` )

WinPB: Update MSVS_2017 checksum, 17/08/20

---

ansible/pbTestScripts/qemuPlaybookCheck.sh

This is due to the latest `s390x` run showing the error message ( https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/77/ARCHITECTURE=s390x,label=vagrant/console ) : 
```
TASK [Docker : Install Docker prerequisites for Ubuntu] ************************
fatal: [localhost]: FAILED! => {"msg": "Timeout (12s) waiting for privilege escalation prompt: "}
```
I've seen this before on `VPC`, awhile ago. The QEMUPlaybookCheck has a history of being very slow, due to the fact that QEMU has to virtualise different architectures to the main host, so I don't think increasing the timeout from 12s to 30s is unreasonable.

pbTests: Increase timeout for QEMUPlaybookCheck

---

ansible/pbTestScripts/buildJDK.sh

Ref: https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/78/ARCHITECTURE=aarch64,label=vagrant/console
The script currently changes the `JDK_TO_BUILD`, but not the `JDK_BOOT_DIR` as its meant to.

pbTests: Set JDK_BOOT_DIR correctly on QEMU aarch64

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2019/tasks/main.yml

Removing the checksum as it's changed twice in the span of a few days!
ref: 
https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/835/OS=Win2012,label=vagrant/console
https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1481#discussion_r472075910
Removing the checksum all together should save on PRs that just change the checksum.

winPB: Remove MSVS_2019 checksum

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Debian.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/RedHat.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml

Fixes: #1502 
Tested at: 
https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/834/
https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/77/
I ran both of the above tests as this is across several architectures. All of them got through the new playbook task (though s390x Ubuntu and x64 CentOS8 failed the run due to other reasons). The problem that this is fixing, however, wasn't found with `VPC` so I can't reproduce the environment that it was found- I'll need @sxa to confirm its fixed.

UnixPB: Ensure locales package is installed for locales tasks

---

ansible/pbTestScripts/qemuPlaybookCheck.sh

pbTest: Add RISC-V support to QEMUPlaybookCheck

---

docs/Setup-QEMU-Images.md

Useful in case we have to rebuild the machine that QEMUPlaybookCheck runs on. Alternatively, it just acts as a good centralised place, along with the `Setup-RISCV_VMs.md` file, to keep all the QEMU knowledge that has been gathered in the various issues/PRs that were made in creating / developing the QPC job.
ref: #1119 #1413 #1520 #1521 #1471 etc.

docs: Add doc on how to recreate QEMU images for QPC

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml

Fixes: #1210 
Ref: #1231 , #1219 
The cached used to install Cygwin in the #1219 was flawed. The cache was created using 7-Zip which apparently doesn't retain symlinks when creating archives. In addition, extracting the archive using 7-Zip can cause issues with the paths to the symlinks , i.e. `/etc/ssl/certs/` symlinked to `\etc\pki\tls\certs\` would go to `/etc/ssl/certs` to `C:/etc/pki/tls/certs` for some reason.
To get round this, @sxa had the idea to use `tar` and `xz` built by cygwin ( located at https://ci.adoptopenjdk.net/userContent/winansible/cygwin64/bin/ ), which can be extracted by 7-Zip, which can then be used to extract the main archive.
I've been able to prove the playbook works with https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/801/ , however the build …

WinPB: install Cygwin using a cache

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2019/tasks/main.yml

fixes: #1526 
Ensure that the MSVS_2019 task won't fail when it returns error code 3010 as that states that the installation was successful but the machine needs rebooting to fully install. As a reboot task is scheduled afterwards, this should be fine.
I've also removed the exception for error code 1, as according to https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2019 , `1` does indeed mean that an error has occured.
Looking at MSVS_2017, it appears that the [documentation](https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2017#error-codes) says 1 is an error code too, but according to #671 , it should be ignored as well. For the sake of testing, I'll run …

winPB: Stop MSVS_2019 installation failing on rc=3010

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/CentOS.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/RedHat.yml

Previously, a new alternative was created for java/javac that did not configure the slave commands (for example, keytool). This is not necessary, because the RHEL packages being used properly declare their alternatives. Futhermore, it made a lot of standard tools like keytool unavailable.
I'm unsure about the state of Debian/Ubuntu: Ubuntu has the same problematic configuration in https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml#L137-L161. But the proper way there is to use `update-java-alternatives`, not `alternatives`. The Debian playbooks don't do this at all. Happy to address that in a separate PR if someone helps me understand the thinking there.

Fix alternatives configuration on RHEL flavours

---

ansible/pbTestScripts/buildJDK.sh
ansible/pbTestScripts/qemuPlaybookCheck.sh

I realised that these options were missing from `QPC.sh`, despite `buildJDK.sh` having the functionality to do those things, so I thought I'd add them in.
Testing at : https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/92/ARCHITECTURE=arm32,label=vagrant/console
(I will make ready to review once I've ensured the above run will start a Hotspot JDK build)

pbTests: Add option to build Hotspot; Add options to specify build repo

---

ansible/README.md
ansible/pbTestScripts/vagrantPlaybookCheck.sh

This is a problem I came across when setting up a new laptop. I don't think we should reduce the memory of the Windows Vagrantfile, otherwise it can significantly increase the time taken to execute `VPC.sh` on it- but a warning should probably be put in to the docs, in case the user doesn't have enough available memory and is wondering why their VM is going to the aborted state straight away.

Vagrant: Add warning in docs about starting Windows VM with too little memory

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/CentOS.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/RedHat.yml

Fixes: #452 
From what I can see, the linked issue is pretty much done, however this PR removes some of the unnecessary distribution checks that are already in the distribution specific common files.

UnixPB: Remove unnecessary distro checks in distro specific common files

---

ansible/playbooks/aix.yml

I noticed some missing features on the aix playbook when using it earlier. 
The variables file would not load until I added the `./`. 
The task `name: Grant zeus sudo powers` requires the `/etc/sudoers` file to exist which only does if `sudo` is installed.
And some missing tags.

aixPB: Missing tags, install sudo, path to variables file

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/MacOSX.yml

We are switching the installers over to use [Packages](http://s.sudre.free.fr/Software/Packages/about.html) 
See https://github.com/AdoptOpenJDK/openjdk-installer/pull/248

ansible: add Packages (installer generator) to macOS playbook

---

ansible/pbTestScripts/buildJDK.sh

The aarch64 QPC runs keep failing the build portion as it keeps trying to use jdk8 as the boot dir. This is due to `JDK_BOOT_DIR` being set to `/usr/lib/jvm/jdk10`, which doesn't exist, so it defaults to setting the boot dir to be what `JAVA_HOME` is, which is jdk8.

pbTests: Add missing '-' char so aarch64 QPC uses correct boot jdk

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml

While following instructions [here](https://github.com/eclipse/openj9/wiki/Reproducing-Test-Failures-Locally#openjdk-tests) to run an openjdk sanity test on a rhel 6 and 7 x64 machine, during the `make compile` stage I hit the following error
```
[root@169 TKG]# make compile
JAVA_HOME is set to /root/jdk-11.0.8+10/
perl scripts/getDependencies.pl -path '/root/openjdk-tests/TKG/../TKG/lib' -task default
Can't locate Digest/SHA.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at scripts/getDependencies.pl line 19.
BEGIN failed--compilation aborted at scripts/getDependencies.pl line 19.
makefile:40: recipe for target 'getdependency' failed
make: *** [getdependency] Error 2 …
```

UnixPB: Add perl-Digest-SHA to rhel vars

---

.gitignore
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/group_vars/all/adoptopenjdk_variables.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Get_Vendor_Files/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Jenkins_User/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Security/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Superuser/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/group_vars/all/adoptopenjdk_variables.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Get_Vendor_Files/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Jenkins/tasks/main.yml
ansible/playbooks/adoptopenjdk_variables.yml

This PR allows us to pull all vendor file secrets from https://github.com/AdoptOpenJDK/secrets/tree/master/vendor_files
- The user running the job has to have permission to clone the secrets repo
- The user must have gpg access to the secrets. (see more information in the secrets repo readme)
- The user must have dotgpg installed to extract the secrets

ansible: dynamically pull vendor files from the secrets repo

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/CodesignCert/tasks/main.yml

Fixes: #1558 
ref: #1556 
In draft until #1560 is merged.
Retrieve the `windows.p12` file from the vendor files that are retrieved from the `Get_Vendor_Files` role that is put in with #1560 . Update the place in which the `windows.p12` file is located, to `C:/openjdk`

winPB: Update ccert role to get windows.p12 from vendor_files

---

ansible/pbTestScripts/qemuPlaybookCheck.sh

Spotted by @Haroon-Khel when looking at #1534 
Currently, the script will clone the user specified branch only to test the playbooks, and then clone the default adoptopenjdk/master branch to run `buildJDK.sh`. This makes it more difficult to test changes to `buildJDK.sh` on platforms other than `x86_64`. This way, it also more accurately reflects what `vagrantPlaybookCheck.sh` does, too.

QPC: Clone the specified branch for using buildJDK.sh

---

.ansible-lint
.github/workflows/linter.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Get_Vendor_Files/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Get_Vendor_Files/tasks/main.yml
ansible/plugins/filter/filters.py
ansible/plugins/inventory/adoptopenjdk_yaml.py
ansible/plugins/library/ssh_config.py

Adds python3 support to the inventory scripts
Fixes linter issue (caused by using deprecated python2.7 version)
Adds centralised ansible-lint config file

linter: fix ansible-lint

---

ansible/inventory.yml

This machine has been removed. We are now able to use the dynamic docker machines for building images

ansible: remove osuosl docker machine from inventory

---

.ansible-lint
ansible/Dockerfile.CentOS6
ansible/ansible.cfg
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/macos_codesign/tasks/main.yml

Adds the missing steps to install the macos codesign certs
Also bumps the centos6 build image to use python 3 because the retart module requires a more recent version of ansible

ansible: add macos codesign cert role

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2017/tasks/main.yml

To put in to let the windows playbooks work until we find a way to do #1572 legally :-)

winPB: Remove MSVS_2017 checksum

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/vars/main.yml

@gdams found a better way to install Cygwin on the OpenJDK-build github actions, so I thought it'd be best to do the same here: 
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/883/
This ends up installing in 2 minutes as opposed to the ~20-25 minutes to install it before.

winPB: Install Cygwin without a cache

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml

Ref: #1596 
Removed the `vars` file, but not the task that includes it :facepalm:

winPB: Remove cygwin include variables task

---

ansible/pbTestScripts/qemuPlaybookCheck.sh
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml

ref https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1538
I will be creating more qemu disk images, which will involve different OSs for already supported architectures.
Im currently adding a ubuntu 18 on arm64 qemu disk image onto `infra-softlayer-ubuntu1804-x64-1`. To accommodate the changes I have made to the script, I will rename the xz compressed disk images to support the `OS.ARCHITECTURE.dsk.xz` style.

QEMU: Add support to qpc script for multiple os

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/OpenSSL/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml

ref: #1578 
I just ran `sed -i -e 's/1.1.1g/1.1.1h/g' main.yml` and updated the checksum :-) 
Testing on VPC: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/884/

winPB: Update OpenSSL 1.1.1g to 1.1.1h

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/cmake/tasks/main.yml

The cmake website seems to have moved where cmake is stored. This is causing playbook executions to fail as it is not at the expected location. This moves it to the new location on github. Checksum is the same so this should be a safe change.
Testing along with another (build) change at https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/891

unixPB: Update cmake location (Downloads now on github)

---

ansible/playbooks/vagrant.yml

A few changes to make this better:
- Add the gather_facts output
- Remove unnecessary checks to the folders that are being created. Ansible's `file` module will check and skip creating the folder if it's already there.
- Install jdk8 using APIv3
- Rework the tasks that symlink `java` and `javac` to the `/usr/bin/` folder - Ansible's `file` module does not allow for wildcard searches, so I had to use `find` and register what was in the `/usr/lib/jvm` folder.
- Add `tags` to everything
- Fix typo in QEMU apt list
- Install QEMU 5.0.0 instead of 4.2.0 - I'm unable to `ssh` to the Fedora Rawhide RISC-V QEMU box in QEMU `4.2.0`, but it's fine in `5.0.0`

pbTests: Update/Fix vagrant.yml playbook

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml

Ref https://github.com/AdoptOpenJDK/openjdk-tests/issues/1998
It seems that `perl-Time-HiRes` isnt included in the standard Perl library so Ive added the package to the Rhel playbook

UnixPb: add perl-Time-HiRes to rhel vars

---

ansible/inventory.yml

We do not use Ubuntu bulid machines - the remaining one was switched to be a docker image production machine.
Fixes #1621 where the discrepencies were raised

inventory: Sync up marist machines with reality (jenkins)

---

ansible/pbTestScripts/vagrantPlaybookCheck.sh

Fixes this problem which occurs if there is no known_hosts file:
```
13:34:03 ++ cat playbooks/AdoptOpenJDK_Unix_Playbook/hosts.unx
13:34:03 + ssh-keygen -R '[127.0.0.1]:2200'
13:34:03 do_known_hosts: hostkeys_foreach failed: No such file or directory
13:34:04 Build step 'Execute shell' marked build as failure
13:34:05 [Checks API] No suitable checks publisher found.
13:34:05 Finished: FAILURE
```
Testing under https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/896/

vagrant: create known_hosts file if it does not exist

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/main.yml

Ive added a condition to prevent the playbooks from improperly changing the hostname or adding an incorrect line into /etc/hosts when the ip address is passed as the `inventory_hostname` variable

UnixPB: prevent improper hostname and /etc/hosts change

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/ANT/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java8/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Strawberry_Perl/tasks/main.yml

Just somethings I noticed were left over in the `C:\temp` folder, after setting up the `IBMCloud` machines.
FYI, I'm not sure if the `\` character will cause an issue with the yaml files, but it's flagging it as red

WinPB: Clean-up zip files

---

ansible/pbTestScripts/buildJDKWin.sh
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java7/tasks/main.yml

I would like to obtain explicit approval from EVERYONE on the reviewers list. Can I ask no-one else other than me to merge please (which is the default policy for the openjdk-infrastructure repo anyway, but let's make sure no-one misses it for this one ;-)
The link in `C:\openjdk` for the Java 7 boot JDK is created as `jdk7` instead of `jdk-7`. This is inconsistent with all other versions. The current production build machines seem to have a mix, so I'm choosing to standardise on the same as the other versions.
To all reviewers: Please let me know if this will impact you and if so when you will have mitigated it (or if you are unable to do so - in which case we would still have the option to put both in place but I'd rather avoid that)
Attempting test via …

ansible: Create Windows JDK7 link as jdk-7 instead of jdk7

---

ansible/inventory.yml
ansible/plugins/inventory/adoptopenjdk_yaml.py

The SoftLayer branding is no longer used on IBM cloud. This PR makes two changes:
1. Changes the softlayer provider name to ibmcloud
2. Replaces all of our `-softlayer-` machines in the inventory with other ones with `-ibmcloud-` names that we have obtained and tested (This is independent of the rename but we had to do it for other reasons)

inventory: Replace 'softlayer' machines with 'ibmcloud'

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml

Ref https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1641
Tested on a centos 7 machine. I was able to reproduce the error, and updating the checksum allowed the docker role to run without error

UnixPB: update docker-ce repo checksum for centos7

---

ansible/inventory.yml

The inventory for the OSUOSL Linux machines is out of sync with what we have. Fortunately Jenkins is correct, although Bastillion will need updates which I'll do as soon as I click "Create Pull Request" here.
**Updates required:**
- The ones in this PR
- Remove `ubuntu1804-1` from Bastillion as it's defined with the same IP as `ubuntu1604-1`
- Renaming `ubuntu1804-2` to `-1` in Bastillion
- Renaming `ubuntu1804-3` to `-2` in Bastillion
- Removing `ubuntu1804-ppc64le-4` from Bastillion as it does not exist
- Removing `centos74-3` from Bastillion as it does not exist
We should look at updating some of the machines we have here to cover newer OSs once the current GA cycle is out of the way
Assigning Will as reviewer as he raised the issues with me :-)
Signed-off-by: Stewart X Addison …

inventory: Sync OSUOSL Linux machines with reality

---

ansible/inventory.yml
ansible/plugins/inventory/adoptopenjdk_yaml.py

As per slack discussion @gdams it would be good to understand if [build machine -1](https://ci.adoptopenjdk.net/computer/build-inspira-solaris10u11-sparcv9-1/) is supposed to be online as it is not currently.
Initial test system was added (commented out) under https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1338

inventory: add missing inspira SPARC systems

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2017/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2019/tasks/main.yml

Fixes: #1546 
@gdams found some alternative links to retrieve the MSVS installers, that should be persistent (i.e. not have their checksum change every X weeks). This means we're able to reinstate the checksums again :-)
VPC Run: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/908/

winPB: Replace MSVS_2017/9 installer URLs and reinstate checksums

---

.github/ISSUE_TEMPLATE/ansible.md
.github/ISSUE_TEMPLATE/machineaccess.md
.github/ISSUE_TEMPLATE/newmachine.md
.github/ISSUE_TEMPLATE/systemdown.md
.github/ISSUE_TEMPLATE/teamaccess.md
.github/ISSUE_TEMPLATE/testcasefail.md
.github/PULL_REQUEST_TEMPLATE.md

I've been meaning to do this for a while. Add an initial set of issue and PR templates fo the repository to make it easier for people submitting issues/PRs to have them categorised correctly and supply all relevant information and think about ensuring documentation is available for others. We can update/refine as we go on (and see which issues don't fit into these!)

Add issue and PR templates to the repository

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Common/tasks/main.yml

Fixes: #1598 
Ensures the 8dot3 shortnames are enabled, and gives `Program Files (x86)` a shortname before any major installations. It was found when setting up the IBMCloud windows machines that the `incredibuild` processes were stopping the shortname from being assigned, giving an `Access is Denied` error message, despite being Administrator. 
The playbook has been checked on the Windows Vagrant VM , as well as put through VPC, however, these particular Windows installations already have shortnames enabled, with `Program Files (x86)` already having a shortname. This did, however, fix the Windows 2016 Dockerfile (#1610), so I can't see why it wouldn't work on an actual windows machine.

winPB: Create Shortname for 'Program Files (x86)' before major installations

---

ansible/inventory.yml

Fixes https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1683

inventory: add test-osuosl-aix71-ppc64-1

---

ansible/pbTestScripts/qemuPlaybookCheck.sh

Ref: #1483 
The RISC-V QPC run wasn't working as the path to the kernel changed (That kernel is provided by an `apt` package `opensbi`, so It possibly changed due to somebody upgrading the package)

QPC: Change kernel path for RISC-V VM

---

ansible/pbTestScripts/vagrantPlaybookCheck.sh

Fixes: #1719 
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/930/ (New VFs option ) & https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/931/ (Non New-VFs option)

pbTests: Fix paths when using VFs from old branch

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/trss.yml

Ref https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1679
Ive added the steps to create the forever services for the TRSS frontend and backend to the trss playbook as per https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1679#issuecomment-729766341
Will test on a ubuntu 18 vm shortly

TRSS: add forever service creation to TRSS playbook

---

ansible/plugins/inventory/adoptopenjdk_yaml.py

[fix_ansible_lint](https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1574/files) completely broke the ability for adoptopenjdk_yaml.py to parse the inventory unless you were in the same directory as `inventory.yml`. This means that AWX cannot utilise it. This is a minimal revert of some of the changes in there to allow it to work again.

Revert garbage inventory path from adoptopenjdk_yaml.py

---

ansible/pbTestScripts/vagrantPlaybookCheck.sh

pbTests: Fix -nh option on the VPC help screen

---

ansible/pbTestScripts/vagrantPlaybookCheck.sh

pbTests: Set remote_tmp for Unix VPC runs

---

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/yum/tasks/main.yml

- [ x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
The playbook includes packages not available, directly, using yum. RPM's previously not available, are now available and need to be removed from the 'additional' packages list.
This replaces #1411

aixPB: Remove packages already installed by yum

---

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/main.yml

aixPB: Modify order of executition to have requirements first

---

FAQ.md

* Mainly - remove duplicate --skip-tags in one of the examples
* also a few minor typo corrections
* modified headers - imho - clearer for people new to OJDK. -- optional

doc: typo corrections and header modifications

---

.github/ISSUE_TEMPLATE/ansible.md
.github/ISSUE_TEMPLATE/machineaccess.md
.github/ISSUE_TEMPLATE/newmachine.md
.github/ISSUE_TEMPLATE/testcasefail.md
.github/workflows/build_mac.yml
.github/workflows/build_vagrant.yml
.gitignore
CHAOS_MONKEY.md
CONTRIBUTING.md
FAQ.md
ONBOARDING.md
README.md
ansible/inventory.yml
ansible/pbTestScripts/vagrantPlaybookCheck.sh
ansible/playbooks/AdoptOpenJDK_AIX_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/yum/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Ant-Contrib/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/MacOSX.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/MacOSX.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Jenkins_User/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Superuser/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Xcode10/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/ant/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/macos_codesign/tasks/main.yml
ansible/plugins/inventory/adoptopenjdk_yaml.py
docs/README.md
docs/Setup-QEMU-Images.md
docs/Setup-RISCV-VMs.md

Fixes from Markdown and Yaml linters + spelling typos

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/main.yml

Since we generally recommed that end-users skip the `adoptopenjdk` tag, we should also make that tag skip the updating of the `hosts` file and other network configuration options to avoid a potentially destructive situation on the end-users' machines

unixPB: do not update hosts_file when 'adoptopenjdk' tag is skipped

---

ansible/pbTestScripts/README.md
ansible/pbTestScripts/vmDestroy.sh

pbTests: Add Solaris10 to vmDestroy.sh

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml

Signed-off-by: Sej <sarah_jackson@uk.ibm.com>
The `libdwarf-devel` and `libmpc-devel` packages are no longer in the base repos for RedHat 8, and have been moved to the CodeReady Linux Builder (CRB) repository which is restricted access.  
Moving these packages to the `Additional_Build_Tools_NOT_RHEL8` list ensures that they are still installed on earlier versions of RedHat.

move CRB packages out of common build tool list

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/OpenSSL/tasks/main.yml

Draft while undergoing testing 

winPB: Update OpenSSL to 1.1.1i and streamline updates

---

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/X11/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/openssl/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/xlc_v13/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/xlc_v16/tasks/main.yml
ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/yum/tasks/main.yml

The roles yum, x11, xlc 13 and 16 and openssl unnecessarily register a `result.$role` variable which isnt referenced later in the role, rendering it useless. Moreover, it causes an error during the execution of the playbook:
```
TASK [Install yum and dependencies] *****************************************************************************************************************************************************************************************************************************************************
task path: /Users/hkhel/AdoptOpenJDK/openjdk-infrastructure/ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/yum/tasks/main.yml:34
fatal: [p9-aix1-ojdk06.osuosl.org]: FAILED! => {"msg": "Invalid variable name in 'register' specified: 'result.yum'"}
```
```
TASK [Install X11.vfb - …
```

aixPB: remove unnecessary register: result.role

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/CentOS.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml

Ref: #1750 
We had the task to enable the PowerTools repo in there, it just had the incorrect path. `libdwarf-devel` resides in the PowerTools repo now, hence the need to enable it, otherwise we can't build OpenJ9.
Note: `libmpc-devel` can also be installed from the PowerTools repo, but looking at #1743 , we never had it in the CentOS build package list? Either way, If we need it, should be easy enough to just add it to the package list :-)

UnixPB: Enable PowerTools repo CentOS8, install libdwarf-devel

---

ansible/Dockerfile.CentOS6
ansible/Vagrantfile.CentOS6

ref: #1745 , #1756 
Fixes the issue that the repos for CentOS6 are outdated due to C6 coming to the end of it's lifespan November 2020. This PR just enables the baseURL, and changes it to CentOS's `vault` URL. 
As mentioned in #1756  , this may not be the best place for this fix. It is affecting the CentOS6 Docker containers too (#1745)- however the Vagrantfiles certainly do need it, as it can't install `libselinux-python` without it. 
^ I'd love to, but unfortunately, there's an issue with the machine that runs it, currently. I've tested this locally though and it does work.

vagrant: Fix CentOS6 mirrorlink issue

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Dragonwell/tasks/main.yml

Fix typo in Dragonwell download URL, and rename jdk8u272-ga to dragonwell-bootstrap-j2sdk-image

winPB:  Fix typo in Dragonwell Download url and rename bootstrap image

---

ansible/inventory.yml

ref https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1577
Machine is in [jenkins](https://ci.adoptopenjdk.net/computer/build-godaddy-ubuntu1604-x64-1/). Bastillion will need to be updated.

inventory: add linux installer node

---

ansible/README.md

Ive included a solution in the docs, regarding running the windows playbook, which fixes a python related error. Ive experienced it when running from a mac, but I dont think it is exclusive to macs.
```
objc[39516]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[39516]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
ERROR! A worker was found in a dead state
```

Docs: include troubleshoot for windows playbook

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/CentOS.yml

Fixes: #1745  (hopefully)
Ref: #1778 , #1765 
Changes the baseurl of the CentOS-SCL and CentOS-SCL-rh repo. I've used `win_shell` and `sed`, as opposed to `replace` / `lineinfile`, primarily because I couldn't get those modules' regex to work. The linter may not like that ...
Note, the above check may uncovered other issues with CentOS6, but it does fix the SCL repo issue.

unixPB: Fix CentOS6 SCL repo baseurl

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/README.md

Fixes: #1674 
The process in which we setup Windows machines (and connect them to Jenkins) isn't properly documented, as far as I know. Due to this, there was a bit of a difference in how @sxa and I did it, resulting in the folder problem that is spoken about in the referenced issue. As far as I tested, there wasn't any way around this, except logging into the Jenkins User before setting up the agent. In @sxa 's method of setting up Windows machines, the folder doesn't occur, so I've documented this process on how to setup the machines.
This will also make it easier for any newcomers to Infra :-)

winPB: Add README.md instructions on how to setup a Windows Machine

---

ansible/inventory.yml

This is an inventory change, but does not add any new machines

inventory: Add OSUOSL's machine names to description field

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/CentOS.yml

Fix to https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1780 which was changing the URL from `http://mirrorlist` to http://#mirrorlist` - doesn't cause a problem as the line is being commented out, but would make it harder to back it out :-)

unixPB: Adjust Cent6 repo editing to not change hostname

---

ansible/inventory.yml

ACLs on infra machines TBC therefore not yet added into bastillion
Leaving the original ansible server in here for now as it is still available, although no longer being used

inventory: add new awx and bastillion servers

---

ansible/inventory.yml

We have a couple of differnt types of Linux/aarch64 systems from packet - this PR adds the system type as a description to the inventory file to differentiate them.

inventory: add description to packet aarch64 systems

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/SLES.yml
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/SLES.yml

Updated repo to `SLE_12_SP5`, and moved `systemtap-sdt-devel` from `Build_Tool_Packages` package list to `Additional_Build_Tools_SLES15 `.
This fixes issue #1820
Signed-off-by: Sej <sarah_jackson@uk.ibm.com>

unixPB: Update playbook for SLES12SP5

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Debian.yml

Fixes: #1828
We need to make sure `gnupg` is installed on the Debian machine before the `Add AdoptOpenJDK GPG key` task is run. I added this as a comment, too. Also, added the `tags: patch_update` to the aforementioned task, for consistency.

unixPB: Ensure GPG is installed for Debian

---

ansible/playbooks/AdoptOpenJDK_Windows_Playbook/README.md

ref: #1773 , https://adoptopenjdk.slack.com/archives/C53GHCXL4/p1610356948467700, #1818 
Adding a note that IcedTea-Web is needed to run `.jnlp` files- It's tripped me up, and it has other people as well, so I feel it's necessary to mention.

docs: Add note about needing ITW to run Jenkins Agent

---

ansible/inventory.yml

ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1716#issuecomment-755202080
Just some mistakes I noticed whilst going through the list of machines that need to be added to Nagios. As these are inconsistent with the node names in Jenkins, my Nagios check (#1717) is unable to find them. I opted for changing the inventory entry as this is easier than renaming the node in Jenkins :-)

inv: Correct Docker marist s390x node name

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/additional_plugins/nagios_server_plugins/check_nagios_sync

ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1716#issuecomment-760803348 #1717 
A Nagios plugin adapted from the one added in #1762 , to check Nagios's server list to the inventory, to determine if any machines need removing. Seems like a good idea to have a consistent check, in case I miss PR's or Slack messages :-)
Currently not implemented in Nagios, in case there's any requested changes here.

unixPB: Add check_nagios_sync module to nagios_server_plugins

---

ansible/inventory.yml

ref: #1716 
Spotted by @sxa when I wasn't able to ssh to it, despite my key being on the machine.

inventory: Update test-ibmcloud-ubuntu1604-x64-1 IP

---

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/additional_plugins/nagios_server_plugins/check_inventory
ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/additional_plugins/nagios_server_plugins/check_nagios_sync

ref: #1717 #1844 
Just some things I noticed whilst setting up the `check_nagios_sync` module on the Nagios Server. The interpreter definition needs to be at the top of the script, and the `rm -rf` command for the latest module wasn't removing the old logs.

unixPB: Minor nagios_server_plugins fixes
